// <copyright file="PackageVersion.cs" company="MUnique">
// Licensed under the MIT License. See LICENSE file in the project root for full license information.
// </copyright>

namespace MUnique.OpenMU.LocalLauncher;

/// <summary>
/// Represents a package version, including an optional semantic-version prerelease suffix.
/// </summary>
internal readonly struct PackageVersion : IComparable<PackageVersion>
{
    private readonly Version _numericVersion;
    private readonly string[]? _prereleaseIdentifiers;

    private PackageVersion(Version numericVersion, string[]? prereleaseIdentifiers)
    {
        this._numericVersion = numericVersion;
        this._prereleaseIdentifiers = prereleaseIdentifiers;
    }

    /// <summary>Parses a package version generated by the local packaging workflow.</summary>
    /// <param name="value">The package version.</param>
    /// <param name="version">The parsed version.</param>
    /// <returns><see langword="true"/> when the value is valid.</returns>
    public static bool TryParse(string? value, out PackageVersion version)
    {
        version = default;
        if (string.IsNullOrWhiteSpace(value))
        {
            return false;
        }

        var separatorIndex = value.IndexOf('-');
        var numericPart = separatorIndex < 0 ? value : value[..separatorIndex];
        var components = numericPart.Split('.');
        if (components.Length is < 3 or > 4
            || components.Any(component => component.Length == 0 || component.Any(character => !char.IsAsciiDigit(character)))
            || !Version.TryParse(numericPart, out var numericVersion))
        {
            return false;
        }

        string[]? prereleaseIdentifiers = null;
        if (separatorIndex >= 0)
        {
            var prereleasePart = value[(separatorIndex + 1)..];
            prereleaseIdentifiers = prereleasePart.Split('.');
            if (prereleaseIdentifiers.Any(identifier =>
                    identifier.Length == 0
                    || identifier.Any(character => !char.IsAsciiLetterOrDigit(character) && character != '-')))
            {
                return false;
            }
        }

        version = new PackageVersion(numericVersion, prereleaseIdentifiers);
        return true;
    }

    /// <inheritdoc />
    public int CompareTo(PackageVersion other)
    {
        var numericComparison = this._numericVersion.CompareTo(other._numericVersion);
        if (numericComparison != 0)
        {
            return numericComparison;
        }

        if (this._prereleaseIdentifiers is null)
        {
            return other._prereleaseIdentifiers is null ? 0 : 1;
        }

        if (other._prereleaseIdentifiers is null)
        {
            return -1;
        }

        var sharedLength = Math.Min(this._prereleaseIdentifiers.Length, other._prereleaseIdentifiers.Length);
        for (var index = 0; index < sharedLength; index++)
        {
            var comparison = ComparePrereleaseIdentifier(this._prereleaseIdentifiers[index], other._prereleaseIdentifiers[index]);
            if (comparison != 0)
            {
                return comparison;
            }
        }

        return this._prereleaseIdentifiers.Length.CompareTo(other._prereleaseIdentifiers.Length);
    }

    private static int ComparePrereleaseIdentifier(string left, string right)
    {
        var leftIsNumeric = left.All(char.IsAsciiDigit);
        var rightIsNumeric = right.All(char.IsAsciiDigit);
        if (leftIsNumeric && rightIsNumeric)
        {
            var normalizedLeft = left.TrimStart('0');
            var normalizedRight = right.TrimStart('0');
            normalizedLeft = normalizedLeft.Length == 0 ? "0" : normalizedLeft;
            normalizedRight = normalizedRight.Length == 0 ? "0" : normalizedRight;
            var lengthComparison = normalizedLeft.Length.CompareTo(normalizedRight.Length);
            return lengthComparison != 0
                ? lengthComparison
                : string.Compare(normalizedLeft, normalizedRight, StringComparison.Ordinal);
        }

        if (leftIsNumeric != rightIsNumeric)
        {
            return leftIsNumeric ? -1 : 1;
        }

        return string.Compare(left, right, StringComparison.Ordinal);
    }
}
