INPUT = {
    23: "'Shadow Phantom Soldier' is looking for an adventurer who will do the jobs for the Shadow Phantom unit. Go check with him.",
    24: "'Shadow Phantom Soldier' is looking for an adventurer who will do the quests of the Shadow Phantom unit. Go check with him.",
    27: '...A bonus gift if I answer all the questions right?',
    28: "...Finally, the tutorial's finished!",
    29: '...Finding a merchant is more difficult than I thought.',
    30: "...Hmm. I didn't know such thing existed.",
    31: '...How do I do it?',
    32: '...I see it pays to know a lot of NPCs.',
    33: '...I wish to learn about...',
    34: "...I'm moved that the queen has made such orders.",
    35: "...Is that right? And then I'd like to learn about...",
    36: '...Shadow Phantom?;Guardians of the queen?',
    37: '...Skill attacks?',
    38: "...That's fantastic!",
    39: '...The icon next to the number 1, 2, 3, 4, and 5 slots....',
    40: '...The queen is very thoughtful!',
    41: "...There's nothing to it. But I would like to learn more....",
    42: '...This is Elveland, the kingdom of Summoners! So this is where my adventure begins.;How exhilarating!',
    43: '...This is Lorencia, the kingdom of Dark Wizards and Dark Knights! So this is where my adventure begins.;Excellent! My adventure begins!',
    44: '...This is Noria, the kingdom of Elves! So this is where my adventure begins.;How exhilarating!',
    45: '...Town Portal Scroll?',
    46: '...Uniria?',
    47: '...Whispers...',
    48: '...trade...',
    50: '1 million Zen for free mercenary registration and 500,000 Zen for deposit. Will you register as a free mercenary now? (Lv. 350 - Master Level)',
    51: "10 clubs from the Burnt Murderers in Vulcanus will do. Please remember that the 'Heroes' in the Burnt Murderers don't drop the item. Come back to me with 10 Burnt Murderer's Clubs to get the reward.",
    74: 'A band going after the sealed stone is using mechanical warriors to attack our forces in Kanturu Ruins. Please defeat Splinter Wolves, which are proving to be most troublesome.',
    75: 'A damage and defense increase buff? That sounds great!',
    76: "A fighting spirit doesn't benefit a hero. (Refuse)",
    77: "A group of monsters has appeared at Dungeon Levels 2 and 3 and is attacking our reconnaissance party. I'd like to ask you, traveler, to hunt down these monsters. Will you accept this quest? (Level 131-140)",
    78: 'A hero is only human in the end, the energy of insanity��',
    79: 'A hero is relentless. I accept. (Accept)',
    80: 'A hero without strong mind is little better than a corpse. Please continue challenging yourself until the end.',
    81: "A moment of carelessness can spell disaster for even the most experienced warriors. I hope you'll remain committed to your training at all times. I'm charged with issuing invitations to Devil Square, an arena where you can undergo the most amount of training in the least amount of time. Would you like to hear more? (All characters: Master Level)",
    83: 'A rumor has it that a group of monsters is chasing after the sealed stone. The rumor also says these monsters are likely to be Ghost Napins, but no one has actually seen them in person. It may just be a rumor, but will you eliminate these Ghost Napins and protect the sealed stone?',
    84: 'A search party dispatched to Aida reports that the number of Death Trees is rapidly increasing. Go to Aida and eliminate 50 Death Trees.',
    85: 'A search party that has been dispatched to Aida reports that the number of Death Trees is rapidly increasing. Go to Aida and eliminate 50 Death Trees.',
    86: 'A taint of insanity',
    87: 'A tutorial?;I look forward to it!',
    88: 'A wise decision. Chaos Castle is a battle field created by Lugard, the god of the heaven world, and Secrarium, the god of the underworld, for the balance of good and evil in this world. However, travelers started going to Chaos Castle and fighting on the side of Lugard, tipping the balance in disfavor of Secrarium.',
    89: "A wise decision. Defeat 50 Cursed Liches in Elveland (Area 2) and 50 Yetis in Devias (Area 2). Do that, and you'll receive 60,000 EXP points, 1,500,000 Zens, and 1 Jewel of Chaos as a reward from the Shadow Phantom Soldier.",
    90: "A wise decision. Defeat 50 Totem Golems in Elveland (Area 3) and 50 Elite Yetis in Devias (Area 3). Do that, and you'll receive 60,000 EXP points, 1,500,000 Zens, and 1 Jewel of Chaos as a reward from the Shadow Phantom Soldier.",
    91: 'A wise decision. Give me 1 million Zen and I will sign you up right away.',
    92: "A wise decision. The test I have in mind is for you to enter Devil Square Level 2 and achieve 100 points. Do this, and I'll give you 200,000 Zens as a reward. However, this applies only to Devil Square Level 2.",
    93: "A wise decision. The test I have in mind is for you to enter Devil Square Level 3 and achieve 130 points. Do this successfully and I'll give you 800,000 EXP points and 500,000 Zens as a reward. However, this applies only to Devil Square Level 3.",
    94: "A wise decision. The test I have in mind is for you to enter Devil Square Level 4 and achieve 160 points. Do this successfully and I'll give you 1 Jewel of Chaos and 500,000 Zens as a reward. However, this applies only to Devil Square Level 4.",
    95: "A wise decision. The test I have in mind is for you to enter Devil Square Level 5 and achieve 190 points. Do this successfully and I'll give you 1 Jewel of Soul as a reward. However, this applies only to Devil Square Level 5.",
    96: "A wise decision. The test I have in mind is for you to enter Devil Square Level 6 and achieve 210 points. Do this successfully and I'll give you 1 Jewel of Harmony as a reward. However, this applies only to Devil Square Level 6.",
    97: "A wise decision. The test I have in mind is for you to enter Devil Square Level 7 and achieve 240 points. Do this successfully and I'll give you 2 Jewels of Soul as a reward. However, this applies only to Devil Square Level 7.",
    98: "A wise decision. Try your hand at Blood Castle Level 1. Destroy the castle gate at least, and I'll give you 100,000 Zens as a reward. However, this applies only to Blood Castle Level 1.",
    99: "A wise decision. Try your hand at Blood Castle Level 2. Destroy the castle gate at least, and I'll give you 200,000 Zens as a reward. However, this applies only to Blood Castle Level 2.",
    100: "A wise decision. Try your hand at Blood Castle Level 3. Destroy the castle gate at least, and I'll give you 800,000 EXP points and 500,000 Zens as a reward. However, this applies only to Blood Castle Level 3.",
    101: "A wise decision. Try your hand at Blood Castle Level 4. Destroy the castle gate, and I'll give you 1 Jewel of Chaos and 500,000 Zens as a reward. However, this applies only to Blood Castle Level 4.",
    102: "A wise decision. Try your hand at Blood Castle Level 5. Destroy the castle gate, and I'll give you 1 Jewel of Soul as a reward. However, this applies only to Blood Castle Level 5.",
    103: "A wise decision. Try your hand at Blood Castle Level 6. Destroy the castle gate at least, and I'll give you 1 Jewel of Harmony as a reward. However, this applies only to Blood Castle Level 6.",
    104: "A wise decision. Try your hand at Blood Castle Level 7. Destroy the castle gate at least, and I'll give you 2 Jewels of Soul as a reward. However, this applies only to Blood Castle Level 7.",
    105: "A wise decision. Try your hand at Blood Castle Level 8. Destroy the castle gate at least, and I'll give you 2 Jewels of Bless as a reward. However, this applies only to Blood Castle Level 8.",
    106: "A wise decision. Watchers of Kundun say that they need the 'Lost Map' to enter the barrier of Kundun but it's getting harder to get the map. Please bring me 2 pages of 'Lost Map Lv. 4' and I will give you a quest with a handsome reward.",
    107: "A wise decision. Watchers of Kundun say that they need the 'Lost Map' to enter the barrier of Kundun but it's getting harder to get the map. Please bring me 3 pages of 'Lost Map Lv. 3' and I will give you a quest with a handsome reward.",
    108: 'A wrong Letter of Request has been delivered to you. Please talk to Mercenary Guild Manager Tercia.',
    118: 'Accept a gens quest.',
    119: 'Accept a quest.',
    120: 'Accept the quest.',
    121: "According to our investigation, Necrons and Death Centurions absorb the energy of insanity while the sealed stone is taking rest. Please get rid of 30 Necrons and 20 Death Centurions to keep the energy of insanity from spreading. I'll prepare a reward when you finish this job. (Party Possible)",
    122: 'According to the latest intelligence, Blood Assassins have been dispatched to assassinate key figures of the Gens. Eliminate 50 Blood Assassins and protect the key Gens figures.',
    123: 'Accumulate EXP points to level up. You can find out how many more points you need to reach the next level by checking your Character Stats window or the EXP bar located at the bottom of your screen.',
    130: 'Advancement of the Reconnaissance Party (1)',
    131: 'Advancement of the Reconnaissance Party (2)',
    132: 'Advancement of the Reconnaissance Party (3)',
    133: 'Advancement of the reconnaissance party....',
    134: 'Advancing into the Floating Castle...',
    136: 'After all, I do need new equipment. Should I give it a shot?',
    137: 'After learning a skill from a scroll, you can activate that skill by assigning it to the Skill window.',
    138: 'After learning a skill from a scroll, you can activate that skill by assigning it to the Skill window.;Can you see the numbered slots at the bottom center of the screen? Click on the icon outlined in green, to the right of the number five slot.',
    139: 'After learning a skill from an orb, you can activate that skill by assigning it to the Skill window.',
    140: 'After learning a skill from an orb, you can activate that skill by assigning it to the Skill window.;Can you see the numbered slots at the bottom center of the screen? Click on the icon outlined in green, to the right of the number five slot.',
    141: 'After receiving the buff, you will see an icon on the top left corner of the screen, a blue light effect surrounding the character, and have one hour of enhanced damage and defense.',
    142: 'Agility Elves, whose priority is defense, can learn skills by equipping weapons, and Energy Elves, whose priority is wizardry, by purchasing orbs.',
    148: "Ah, I'll have to go far back in time to explain that.;Runedil, the former queen of Elves, was saddened by the loss of all the new warriors of the MU empire, who gave up their lives to constant warring.",
    149: "Ah, you came at last. The task is to get me some equipment for the war supplies. There's no business more profitable than the war supplies delivery. It's not like the good old days, but enough for a stable income. Especially Tantalos's Armor and Burnt Murderer's Club are expensive ones. (Lv. 350 - 400)",
    150: "Ah, you've answered incorrectly. Take the items, ingredients, and the money you need for combining to the Goblin in Noria to create a new item. Make sure to try it at least once. Let's skip to the next question.",
    151: "Ah, you've answered incorrectly. To trade, press D and select Trade or face the character and type in '/trade' in the Chat window. Let's skip to the next question.",
    152: "Ah, you've answered incorrectly. Type in '/Request off' in the Chat window to turn down party requests. To start receiving party requests again, type in '/Request on' in the Chat window. Let's skip to the next question.",
    153: "Ah, you've answered incorrectly. Use M to find out and travel to accessible areas with ease. Discovering areas that are right for your level, and hunting there, can also be very fun.;On to the next question.",
    154: "Ah, you've answered incorrectly. When you want to talk to a friend and you know his or her ID, or if you want to pass on private messages, send whispers by using Tab from the Chat window. Let's skip to the next question.",
    155: "Ah, you've answered incorrectly.; You'll be able to repair your equipment with ease by using the Repair button from the Inventory window once you reach level 50. However, this is more costly than repairing through an NPC.;Let's move on to the next question.",
    156: "Ah. So that's what happened....",
    163: "All right, I'll take it. (Accept)",
    164: 'All right. (Accept)',
    168: 'Alquamoses are the most troublesome creatures in Icarus, the path that leads to the Floating Castle. Stardust used by Alquamoses is proving to be devastating to our reconnaissance party. Will you eliminate these Alquamoses to allow our reconnaissance party to advance? (Level 245-249)',
    169: "Alright! Let's get started with the tutorial.",
    170: "Alright. I'll go all out on this one.",
    171: 'Also, if you find yourself far away from a town or cornered while on a hunt, the Town Portal Scroll can come in really handy. Are you familiar with using it?',
    194: "Apples can be purchased from potion merchants. In Lorencia, look for Potion Girl Amy, who is located across the bridge (128,85). In Elveland, look for Silvia, who is in the 1 o'clock direction from the center of the square (45,227). In Noria, look for Elf Lala, who is slightly to the north from the town's center (172,124).",
    199: "Are you familiar with a hidden training ground known as Devil Square? It's an opportune place to develop your skills. Why don't you listen to what I have to say and then decide? (Basic character: Level 131-180, Advanced character: Level 111-160)",
    200: "Are you familiar with a hidden training ground known as Devil Square? It's an opportune place to develop your skills. Why don't you listen to what I have to say and then decide? (Basic character: Level 15-130, Advanced character: Level 10-110)",
    212: 'As the clan gets stronger, so do you. Please come back if you change your mind. (The quest has been cancelled.)',
    220: 'Ask about Gens Duprian.',
    221: 'Ask about Gens Vanert.',
    222: 'Ask about the gens dispute.',
    224: 'Assault of Burning Lava Giants',
    225: "At Devias 2, you'll encounter Hommerds roaming around and shrieking out foul laughs. Defeat 30 Hommerds and return to me for a reward.",
    226: "At Devias 2, you'll encounter Yetis covered in white fur. Defeat 30 Yetis and return to me for a reward.",
    227: "At Devias 2, you'll encounter blade-wielding Assassins. Defeat 30 Assassins and return to me for a reward.",
    228: "At Devias 2, you'll encounter semi-transparent Ice Monsters. Defeat 25 Ice Monsters and return to me for a reward.",
    229: "At Devias 2, you'll encounter semi-transparent Ice Monsters. Defeat 30 Ice Monsters and return to me for a reward.",
    230: "At Devias 4, you'll encounter shrieking ice creatures. Defeat 3 Ice Queens and return to me for a reward.",
    231: "At Dungeon Level 1, you'll encounter Larvae harassing travelers near the entrance. Defeat 40 Larvae and return to me for a reward.",
    232: "At Dungeon Level 1, you'll encounter one-eyed giants that carry axes known as Cyclopses. Defeat 40 Cyclopses and return to me for a reward.",
    233: "At Dungeon Level 1, you'll encounter one-eyed giants that carry axes known as Cyclopses. Defeat 50 Cyclopses and return to me for a reward.",
    234: "At Dungeon Level 2, you'll encounter Hell Hounds that use sharp magic. Defeat 50 Hell Spiders and return to me for a reward.",
    235: "At Dungeon Level 2, you'll encounter Skeleton Archers that hide and fire arrows. Defeat 50 Skeleton Archers and return to me for a reward.",
    236: "At Dungeon Level 2, you'll encounter Thunder Liches that use thunder magic. Defeat 50 Thunder Liches and return to me for a reward.",
    237: "At Dungeon Level 2, you'll encounter poison-drooling Hell Hounds. Defeat 50 Hell Hounds and return to me for a reward.",
    238: "At Dungeon Level 2, you'll encounter poison-drooling Poison Bull Fighters. Defeat 50 Poison Bull Fighters and return to me for a reward.",
    239: "At Dungeon Level 3, you'll encounter lead monsters known as Gorgons. Defeat 15 Gorgons and return to me for a reward.",
    240: "At Dungeon Levels 2 and 3, you'll encounter Dark Knights casting darkness in their paths. Defeat 50 Dark Knights and return to me for a reward.",
    241: "At Elveland 2, you'll encounter Cursed Liches that carry around a burning staff. Defeat 50 Cursed Liches and return to me for a reward.",
    242: "At Elveland 3 (179, 81), you'll encounter foul, furry creatures. Defeat 50 Grizzlies and return to me for a reward.",
    243: "At Elveland 3 (203, 37), you'll encounter the captains of foul, furry creatures known as Grizzlies. Defeat 50 Captain Grizzlies and return to me for a reward.",
    244: "At Elveland 3, you'll encounter Totem Golems born from totems. Defeat 50 Totem Golems and return to me for a reward.",
    245: "At Icarus, you'll encounter Mega Crusts, which are even more fearsome than Alquamoses. Defeat 80 Mega Crusts and return to me for a reward.",
    246: "At Icarus, you'll encounter Queen Rainiers, which disguise their deathly aura with beauty. Defeat 80 Queen Rainiers and return to me for a reward.",
    247: "At Icarus, you'll encounter stardust-carrying Alquamoses. Defeat 80 Alquamoses and return to me for a reward.",
    248: "At Tarkan 1, you'll encounter Bloody Wolves and their scent of death. Defeat 60 Bloody Wolves and return to me for a reward.",
    249: "At Tarkan 1, you'll encounter giant axe-wielding Mutants. Defeat 60 Mutants and return to me for a reward.",
    252: "At the Lost Tower Level 1, you'll encounter Shadows, which are embodiments of evil intent. Defeat 50 Shadows and return to me for a reward.",
    253: "At the Lost Tower Level 7, you'll encounter Balrogs wielding huge scythes and guarding the entrance. Defeat 15 Balrogs and return to me for a reward.",
    254: "At the Lost Tower Level 7, you'll encounter Death Gorgons that have become stronger through death. Defeat 60 Death Gorgons and return to me for a reward.",
    255: "At the Lost Tower Levels 1 and 2, you'll encounter Poison Shadows, which are poison-spewing embodiments of evil intent. Defeat 50 Poison Shadows and return to me for a reward.",
    256: "At the Lost Tower Levels 2 and 3, you'll encounter corrupt beings known as Cursed Wizards. Defeat 50 Cursed Wizards and return to me for a reward.",
    257: "At the Lost Tower Levels 3 and 4, you'll encounter Death Cows and their cloud of evil energy. Defeat 50 Death Cows and return to me for a reward.",
    258: "At the Lost Tower Levels 5 and 6, you'll encounter Death Knights that were begotten from evil. Defeat 50 Death Knights and return to me for a reward.",
    259: "At the Lost Tower Levels 5 and 6, you'll encounter Death Knights that were begotten from evil. Defeat 60 Death Knights and return to me for a reward.",
    273: 'Attack on the Supply Corps!',
    320: 'Barriers that have been installed in regions where monsters frequently mobilize are under attack. We must teach these monsters a lesson by striking down their superiors. Will you accept this quest? (Level 198-201)',
    324: 'Be the last one standing in Chaos Castle, deliver a weapon to Archangel in Blood Castle, and survive until the end of Devil Square. Complete all three and return to the Phantom Soldier to receive your reward.',
    326: "Beam Knights seem to be up to something in Tarkan. Go to Tarkan level 2 and hunt down 100 Beam Knights. Come see me once that's done to receive a Devil's Invitation + 5 as a reward. They are strong foes, and you should hunt them with the help of others.",
    331: 'Before attacking the supply warehouse, we plan to defeat the monsters guarding it first. Once those monsters have been dealt with, the reconnaissance party will handle the assault on the warehouse. Will you accept this quest? (Level 56-65)',
    346: 'Better grab a chance than to regret it. Well, come back later if you change your mind. (The quest has been cancelled.)',
    370: 'Blood Castle Adaptation (1)',
    371: 'Blood Castle Adaptation (2)',
    372: 'Blood Castle Adaptation (3)',
    373: 'Blood Castle Adaptation (4)',
    374: 'Blood Castle Challenge (1)',
    375: 'Blood Castle Challenge (2)',
    376: 'Blood Castle Challenge (3)',
    377: 'Blood Castle Challenge (4)',
    379: "Blood Castle builds and tests the fellowship of you and your brothers in arms. However, it's not an easy place to reach. Go to the Shadow Phantom Soldier and accept a quest that will earn you an Invisibility Cloak, which you'll need to enter Blood Castle.",
    380: "Blood Castle builds and tests the fellowship of you and your brothers in arms. If you wish to find out the strength of your party's bond, inquire with the Shadow Phantom Soldier about Blood Castle.",
    381: "Blood Castle is an excellent place to build your party's bond. I have a quest that will earn you an item you'll need to enter Blood Castle. Will you accept this quest? (Basic character: Level 181-230, Advanced character: Level 161-210)",
    382: 'Blood Castle...',
    441: 'Burning Lava Giants have infested the lava fields of Vulcanus and caused our gens members to disperse. Make haste and exterminate these Burning Lava Giants in Vulcanus.',
    443: "By a 'simple quest', do you mean killing monsters?",
    444: 'Call from the Gens',
    445: 'Can you explain in more detail?',
    478: 'Change of the Underwater Temple',
    496: 'Chaos Castle Adaptation (1)',
    497: 'Chaos Castle Adaptation (2)',
    498: 'Chaos Castle Adaptation (3)',
    499: 'Chaos Castle Adaptation (4)',
    500: 'Chaos Castle Challenge (1)',
    501: 'Chaos Castle Challenge (2)',
    502: 'Chaos Castle Challenge (3)',
    503: 'Chaos Castle Challenge (4)',
    504: 'Chaos Castle is a place where you can test your own limitations. If you want to find out your limitations, go inquire with a Shadow Phantom Soldier about the castle.',
    505: "Chaos Castle will push you to your limits and shouldn't be taken lightly. Be sure to prepare yourself before going there. Go to the Shadow Phantom Soldier and accept a quest that will earn you the items you'll need at Chaos Castle.",
    506: 'Chaos Castle...',
    518: 'Character and Server Selection',
    522: 'Check the location and client of the request from the Letter of Request.',
    523: 'Check the request information. (Accept)',
    524: 'Checking the Letter of Request',
    539: 'Clear Illusion Temple and return to the Shadow Phantom Soldier to receive 3,000,000 Exp.',
    540: 'Clear Illusion Temple and return to the Shadow Phantom Soldier to receive 5,000,000 Exp.',
    541: 'Clear Illusion Temple and return to the Shadow Phantom Soldier to receive 8,000,000 Exp.',
    542: 'Clear Illusion Temple and return to the Shadow Phantom Soldier to receive 800,000 Exp.',
    543: 'Clearing a Path to Icarus',
    545: "Close the Quest window and click on me again. After that, select 'Receive damage and defense increase buff.'",
    546: "Close the Quest window and click on me again. After that, select 'Receive damage and defense increase buff.' This buff is available to anyone under level 220.;After receiving the buff, you will see an icon on the top left corner of the screen, a blue light effect surrounding the character, and have one hour of enhanced damage and defense.",
    549: 'Collect 20 units of Stardust from Queen Rainiers in Icarus and bring them to Zyro to get the reward.',
    553: 'Come back and see me once you reach level 25. I will give you a Uniria as a reward for your achievement.',
    554: "Come back once you've reached level 25.;I will then reward you with a Uniria as a gift.",
    555: 'Come back when you reach a certain level, and I will give you a Uniria as a reward.',
    556: "Come back when you're ready and I'll give you a full briefing then. (The quest has been cancelled.)",
    561: "Complete Archangel's quest in Blood Castle Level 1 and then return to the Shadow Phantom Soldier to claim your reward. However, this applies only to Blood Castle Level 1.",
    562: "Complete Archangel's quest in Blood Castle Level 2 and then return to the Shadow Phantom Soldier to claim your reward. However, this applies only to Blood Castle Level 2.",
    563: "Complete Archangel's quest in Blood Castle Level 3 and then return to the Shadow Phantom Soldier to claim your reward. However, this applies only to Blood Castle Level 3.",
    564: "Complete Archangel's quest in Blood Castle Level 4 and then return to the Shadow Phantom Soldier to claim your reward. However, this applies only to Blood Castle Level 4.",
    565: "Complete Archangel's quest in Blood Castle Level 5 and then return to the Shadow Phantom Soldier to claim your reward. However, this applies only to Blood Castle Level 5.",
    566: "Complete Archangel's quest in Blood Castle Level 6 and then return to the Shadow Phantom Soldier to claim your reward. However, this applies only to Blood Castle Level 6.",
    567: "Complete Archangel's quest in Blood Castle Level 7 and then return to the Shadow Phantom Soldier to claim your reward. However, this applies only to Blood Castle Level 7.",
    568: "Complete Archangel's quest in Blood Castle Level 8 and then return to the Shadow Phantom Soldier to claim your reward. However, this applies only to Blood Castle Level 8.",
    570: 'Completion of the request',
    575: 'Congratulations on becoming a member of Gens Duprian.  Much will be asked of you in the name of our cause. Come see me whenever you require assistance concerning the gens.',
    576: 'Congratulations on becoming a member of Gens Vanert. Much will be asked of you in the name of our cause. Come see me whenever you require assistance concerning the gens.',
    577: 'Congratulations. You have completed the first mission. Then I will give you the second mission right away. Will you accept this mission? (Basic character: Level 240 - 270, Advanced character: Level 220 - 260)',
    578: 'Congratulations. You have completed the first mission. Then I will give you the second mission right away. Will you accept this mission? (Basic character: Level 300 - 320, Advanced character: Level 271 - 320)',
    579: 'Congratulations. You have completed the first mission. Then I will give you the second mission right away. Will you accept this mission? (Level 331 - 350)',
    580: 'Congratulations. You have completed the first mission. Then I will give you the second mission right away. Will you accept this mission? (Level 351 - 380)',
    581: 'Congratulations. You have completed the first mission. Then I will give you the second mission right away. Will you accept this mission? (Level 381 - 400)',
    582: 'Congratulations. You have completed the first mission. Then I will give you the second mission right away. Will you accept this mission? (Master level)',
    583: 'Congratulations. You have contributed more to the cause of the gens than any other member. Duprian Winston rewards your accomplishments. I hope to see even greater achievements from you next month.',
    584: "Congratulations. You've completed the tutorial. Take this Ring of Hero and this Ring of Warrior. They are gifts to you from the queen.",
    585: 'Conquer the Dungeon! (1)',
    586: 'Conquer the Dungeon! (2)',
    587: 'Conquer the Dungeon! (3)',
    588: 'Conquer the Dungeon! (4)',
    589: 'Conquer the Dungeon! (5)',
    590: 'Conquer the Dungeon! (6)',
    591: 'Continue listening.',
    592: 'Continue the conversation.',
    593: 'Continuing Attacks on Barriers (1)',
    594: 'Continuing Attacks on Barriers (2)',
    595: 'Continuing Attacks on Barriers (3)',
    596: 'Continuing Requests for Help (1)',
    597: 'Continuing Requests for Help (2)',
    598: 'Continuing Requests for Help (3)',
    599: 'Continuing Requests for Help (4)',
    603: 'Courage is the most important trait for a hero. If you lack the proper courage, you can never be reborn as a hero.',
    650: "Cutting down the enemy clan's force will be the best revenge. Teach them a lesson by eliminating 5 of them who infiltrated in Vulcanus. Kill the enemy clan member in Vulcanus and come back to me to get the reward. (Can proceed only in Vulcanus)",
    680: 'Dark Knights are unique in that they are powerful swordsmen who rely on both weapons and orbs. Let me give you a weapon to use so that you can understand better.',
    681: 'Dark Knights can learn additional skills by going to Lorencia and purchasing orbs from Pasi the Mage (119,112). After purchasing an orb, right-click on it to learn the skill.',
    682: 'Dark Knights can learn additional skills by going to Lorencia and purchasing scrolls from Pasi the Mage (119,112). After purchasing a scroll, right-click on it to learn the skill.',
    726: 'Dark Wizards are unique in that they are capable of mastering various magic spells from scrolls and parchments. Let me give you a scroll as a gift so that you can understand what I mean.',
    727: 'Dark Wizards can learn additional skills by going to Lorencia and purchasing scrolls from Pasi the Mage (119,112) or weapons from Hanzo the Blacksmith (116,142).',
    740: "Death Knights from the Lost Tower Levels 5 through 7 are causing great harm to travelers there. Go to the Lost Tower and defeat 80 Death Knights. Come see me when that's done to receive an Invisibility Cloak + 3 as a reward. At your current level, it'll be too dangerous for you to hunt the monsters alone. It'll be better if you hunt in a party.",
    762: 'Defeat 10 monsters in Chaos Castle, deliver a weapon to Archangel in Blood Castle, and survive until the end of Devil Square. Complete all three and return to the Phantom Soldier to receive your reward.',
    763: 'Defeat 100 Queen Rainiers in Icarus and then go back to the Shadow Phantom Soldier to receive a choice between 10 Large SD Potions and 30 Complex Potions as your reward.',
    764: 'Defeat 15 Agons from near the south side (173, 222) of town and return to me for a reward.',
    765: 'Defeat 15 Giants from near the Devias entrance (22, 45) on the east side of town and return to me for a reward.',
    766: 'Defeat 15 Liches from near the Dungeon entrance (159, 205) on the southwest side of town and return to me for a reward.',
    767: 'Defeat 15 Polluted Butterflies from near the tombstone (121, 156) on the north side of town and return to me for a reward.',
    768: 'Defeat 20 Giants from near the Devias entrance (22, 45) on the east side of town and return to me for a reward.',
    769: 'Defeat 20 Hideous Rabbits from near the face sculpture on the north side (151, 146) of town and return to me for a reward.',
    770: 'Defeat 20 Skeleton Warriors from near the Dungeon entrance (123, 227) on the southwest side of town and return to me for a reward.',
    771: 'Defeat 20 Stone Golems from near the southwest side (30, 214) of town and return to me for a reward.',
    772: 'Defeat 20 monsters in Chaos Castle, deliver a weapon to Archangel in Blood Castle, and survive until the end of Devil Square. Complete all three and return to the Phantom Soldier to receive your reward.',
    773: 'Defeat 30 monsters in Chaos Castle, deliver a weapon to Archangel in Blood Castle, and survive until the end of Devil Square. Complete all three and return to the Phantom Soldier to receive your reward.',
    774: 'Defeat 40 Larvae from Dungeon Level 1 and go back to the Shadow Phantom Soldier to receive a choice of two rewards from 30 Healing Potions, 30 Mana Potions, and 4 Small SD Potions.',
    775: 'Defeat 5 monsters in Chaos Castle, deliver a weapon to Archangel in Blood Castle, and survive until the end of Devil Square. Complete all three and return to the Phantom Soldier to receive your reward.',
    776: "Defeat 50 Cursed Liches in Elveland (Area 2) and 50 Yetis in Devias (Area 2). Do that, and you'll receive 60,000 EXP points, 1,500,000 Zens, and 1 Jewel of Chaos as a reward from the Shadow Phantom Soldier.",
    777: "Defeat 50 Totem Golems in Elveland (Area 3) and 50 Elite Yetis in Devias (Area 3). Do that, and you'll receive 60,000 EXP points, 1,500,000 Zens, and 1 Jewel of Chaos as a reward from the Shadow Phantom Soldier.",
    778: 'Defeat 60 Hell Spiders from Dungeon Level 2 and go back to the Shadow Phantom Soldier to receive a choice of two rewards from 15 Large Healing Potions, 15 Large Mana Potions, and 8 Small SD Potions.',
    779: 'Defeat 80 Dark Knights from Dungeon Level 3 and go back to the Shadow Phantom Soldier to receive a choice of two rewards from 30 Large Healing Potions, 30 Large Mana Potions, and 15 Small Complex Potions.',
    830: 'Devil Square Adaptation (1)',
    831: 'Devil Square Adaptation (2)',
    832: 'Devil Square Adaptation (3)',
    833: 'Devil Square Adaptation (4)',
    834: 'Devil Square Challenge (1)',
    835: 'Devil Square Challenge (2)',
    836: 'Devil Square Challenge (3)',
    837: 'Devil Square Challenge (4)',
    839: "Devil Square is a place where you can develop your abilities quickly. Prepare thoroughly before entering as this is not a place to be taken lightly. Go to the Shadow Phantom Soldier and accept the quest to earn a Devil's Invitation, which you'll need to enter Devil Square.",
    840: 'Devil Square is a place where you can hone and develop your skills fast. If you want to get stronger quickly, inquire with the Shadow Phantom Soldier about Devil Square.',
    841: 'Devil Square is the place where the Elf Tree once stood. The Elf Tree was created by the mother of all Elves, an underground Elf known as Aria. This tree had the ability to produce Elves regularly. Then Secrarium tricked Lugard and appeared in Noria, at the location of the Elf Tree.',
    842: 'Devil Square provides an opportunity to train yourself and build your experience. I have a little test that will tell me of your skills and experience. Would you like to take this test? (All characters: Master Level)',
    843: 'Devil Square provides an opportunity to train yourself and build your experience. I have a little test that will tell me of your skills and experience. Would you like to take this test? (Basic character: 330-400 Level, Advanced character: Level 311-400)',
    844: 'Devil Square provides an opportunity to train yourself and build your experience. I have a little test that will tell me of your skills and experience. Would you like to take this test? (Basic character: Level 131-180, Advanced character: Level 111-160)',
    845: 'Devil Square provides an opportunity to train yourself and build your experience. I have a little test that will tell me of your skills and experience. Would you like to take this test? (Basic character: Level 181-230, Advanced character: Level 161-210)',
    846: 'Devil Square provides an opportunity to train yourself and build your experience. I have a little test that will tell me of your skills and experience. Would you like to take this test? (Basic character: Level 231-280, Advanced character: Level 211-260)',
    847: 'Devil Square provides an opportunity to train yourself and build your experience. I have a little test that will tell me of your skills and experience. Would you like to take this test? (Basic character: Level 281-330, Advanced character: Level 261-310)',
    848: 'Devil Square provides an opportunity to train yourself and build your experience. Would you like to train at Devil Square? (Basic character: Level 15-130, Advanced character: Level 10-110)',
    849: 'Devil Square...',
    853: 'Devils located on Levels 4 through 6 of the Lost Tower should suffice. Go to the Lost Tower and defeat 100 Devils. Come see me after that, and I will give you a choice between 15 SD Potions and 15 Complex Potions as your reward. When you claim your rewards, make sure you have at least 15 empty slots in your Inventory. Remember that.',
    854: "Did you launch the Character Stats window?;That window contains the character's name and level, the name of the current server, and character statuses.",
    855: 'Did you say the space bar?',
    860: "Dispose of the Plunderers' Leader!",
    861: 'Dispose of the Town Plunderers!',
    872: "Doesn't sound too difficult....",
    927: "Dreadfears in Kanturu Relics are causing great harm to travelers there. Go to Kanturu Relics and hunt down 100 Dreadfears. Come see me when that's done to receive an Invisibility Cloak + 8 as a reward. At your current level, it'll be too dangerous for you to hunt the monsters alone. It'll be better if you hunt in a party.",
    928: "Due to Lev's illusion spells, however, the souls of the dead followers remained in this world to defend the temple. These souls believed Lev's return would allow them to reclaim their bodies and continued to safeguard the temple. Today, the temple is guarded by the alliance in case Lev does actually return and Illusion Sorcery uses ancient relics to lure in unsuspecting travelers to their cause.",
    937: 'Dungeon Sweep!',
    947: "Dural, the first master of the guild was a legendary commander who led us to a great victory against Kundun's army. He had to seclude himself from the world since Gaion's rebellion and the order of exterminating 5 major clans. The newly formed mercenary guild severed whatever relations with Gaion, but 5 major clans still want the mercenary guild to get rid of Gaion.",
    948: 'EXP Points and Leveling Up',
    954: 'Earn valuable equipment by completing simple quests?',
    981: 'Eliminate 1 Hero Zombie Fighter and 1 Hero Reborn Gladiator and then go back to your Gens Steward to get the reward.',
    982: 'Eliminate 20 Bloody Slayer and 10 Vicious Bloody Slayer and then go back to your Gens Steward to get the reward.',
    983: 'Eliminate 30 Aegis and 20 Rogue Centurions and go back to Beina to get the reward.',
    984: 'Eliminate 30 Bloody Soldiers and 20 Death Angels in Kalima 6 and go back to Beina to get the reward.',
    985: 'Eliminate 30 Necrons and 20 Death Centurions and then go back to Beina to get the reward.',
    986: 'Eliminate 5 players of your enemy Gens and then go back to your Gens Steward to get the reward.',
    987: 'Eliminate 50 Blood Assassins, and I will give you a reward.',
    988: 'Eliminate 50 Burning Lava Giants and return to me for a reward.',
    989: 'Eliminate 50 Death Riders and return to me for a reward.',
    990: 'Eliminate 50 Death Trees and return to me for a reward.',
    991: 'Eliminate 50 Ghost Napins and return to me for a reward.',
    992: "Eliminate 50 Iron Riders to put a stop to their guerilla attacks, and I'll give you a reward.",
    993: "Eliminate 50 Sapi-Duos to stop the attacks against our gens members, and I'll give you a reward.",
    994: 'Eliminate 50 Silver Valkyries and return to me for a reward.',
    995: 'Eliminate 50 Splinter Wolves and return to me for a reward.',
    996: 'Eliminate Advisor Jerind and Gaion Kharein and then go back to Mercenary Guild Manager Tercia to get the reward.',
    997: 'Eliminate Blood Assassins',
    998: 'Eliminate Kundun and 10 Schrikers, the guard soldiers and then go back to Beina to get the reward.',
    999: 'Eliminate Plundering Silver Valkyries',
    1000: 'Eliminate Raymond and Erkanne in Varka and then go back to Mercenary Guild Manager Tercia to get the reward.',
    1001: 'Eliminate Sapi-Duos',
    1002: 'Eliminate Splinter Wolves',
    1024: "Elveland shouldn't be so difficult.",
    1030: 'Elves can learn additional skills by going to Noria and purchasing orbs from Elf Lala (173,124) or weapons from Eo the Craftsman (195,123).',
    1036: 'End the Spread of Death Trees',
    1042: "Enter Devil Square Level 1, defeat the monsters that appear, and survive to the bitter end. Come back afterwards, and I'll give you 100,000 EXP points and 200,000 Zens as a reward. However, this applies only to Devil Square Level 1.",
    1043: "Enter Devil Square Level 2, defeat the monsters that appear, and survive to the bitter end. Come back to me afterwards, and I'll give you 400,000 EXP points and 300,000 Zens as a reward. However, this applies only to Devil Square Level 2.",
    1044: "Enter Devil Square Level 3, defeat the monsters that appear, and survive to the bitter end. Come back to me afterwards, and I'll give you 1,000,000 EXP points and 1 Jewel of Chaos as a reward. However, this applies only to Devil Square Level 3.",
    1045: "Enter Devil Square Level 4, defeat the monsters that appear, and survive to the bitter end. I'll give you 1 Jewel of Soul as a reward when you return. However, this applies only to Devil Square Level 4.",
    1046: "Enter Devil Square Level 5, defeat the monsters that appear, and survive to the bitter end. I'll give you 1 Jewel of Bless as a reward when you return. However, this applies only to Devil Square Level 5.",
    1047: "Enter Devil Square Level 6, defeat the monsters that appear, and survive to the bitter end. I'll give you 1 Jewel of Life as a reward when you return. However, this applies only to Devil Square Level 6.",
    1048: "Enter Devil Square Level 7, defeat the monsters that appear, and survive to the bitter end. I'll give you 2 Jewels of Bless as a reward when you return. However, this applies only to Devil Square Level 7.",
    1049: "Enter into Aida 2 and you will find Witch Queens. They always carry 'Kalt Stone' on themselves so eliminate them and take the jewel from them. Bring me 10 Kalt Stones. (Party Possible)",
    1095: "Evil energy has escaped from the Lost Tower and is now corrupting the souls of Devias residents, turning them into monsters. I'd like to ask you to purify their souls and give them eternal rest for us. Will you accept this quest? (Level 186-189)",
    1103: 'Excellent! Bring on the test!',
    1104: 'Excellent! I will be back in a flash.',
    1105: "Excellent! It's time for the next quest. Since you are now familiar with hunting, let's get you to go after a tougher monster.",
    1106: "Excellent! Let's get started with the tutorial.",
    1107: 'Excellent! What is the name of the monster you want me to hunt down?',
    1108: 'Expanding businesses',
    1114: 'Explain potions to me once more.',
    1122: 'Fast growth...',
    1123: 'Fastest Way to Train (1)',
    1124: 'Fastest Way to Train (2)',
    1125: 'Fastest Way to Train (3)',
    1126: 'Fastest Way to Train (4)',
    1127: 'Fastest Way to Train (5)',
    1130: 'Final Test to become a Hero',
    1131: 'Finally, a quest! You want me to buy 5 apples from a merchant?',
    1132: "Find 2 pages of 'Lost Map Lv. 4' and return to 'Shadow Phantom Soldier'.",
    1133: "Find 2 pages of 'Lost Map Lv. 5' and return to 'Shadow Phantom Soldier'.",
    1134: "Find 3 pages of 'Lost Map Lv. 3' and return to 'Shadow Phantom Soldier'.",
    1135: 'Find General Goods Merchant Zyro',
    1136: 'Find General Goods Merchant Zyro and check the details of his request to the mercenary guild.',
    1137: 'Find General Goods Merchant Zyro who goes round Noria, Elveland, Lorencia and Devias and sell things.',
    1138: 'Find Priestess Beina of the Underwater Temple in Kalima 6 and check the request information.',
    1139: 'Find merchant Zyro, who goes round Noria, Elveland, Lorencia and Devias and sell things.',
    1141: 'Find the guild office manager Tercia and pay 500,000 Zen as a deposit to receive Lv. 1 Letter of Request which contains the quest of the day.',
    1142: 'Find your Gens Steward.',
    1168: 'First task is to collect the Stardust, which is the base material of the popular cosmetic product, Della. The ladies in a queue threaten me so I had to ask the mercenary guild. You can extract a small amount of Stardust from Queen Rainiers in the Icarus. Please bring me 20 units of Stardust. (Party Possible)',
    1169: "First you need to eliminate Kundun's combatants who attack the temple entrance and then get rid of the enemies who cast spell on the sealed stone. I'll give you the 2nd goal when you finish 1st goal and come back to me. Here's the 1st goal; go to Kalima 6 and eliminate 30 Aegis and 20 Rogue Centurions, Kundun's combatants. (Party Possible)",
    1188: "Free mercenary doesn't really belong to the mercenary guild; anybody can receive a request and get the reward only if he or she has certain sum of money for registration. We take the deposit for each request, but it's fully refundable as you finish the request. Don't you worry. We request you what you can handle.",
    1191: 'From the Chat window, use the Ctrl button.',
    1192: 'From the Chat window, use the Shift button.',
    1193: 'From the Chat window, use the Tab button.',
    1202: 'Gain EXP points to level up.;You can find out how many more points you need to reach the next level by checking your Character Stats window or the EXP bar located at the bottom of your screen.;The bar is divided into ten segments, and filling them up will elevate you to the next level.',
    1218: 'Gens Duprian is a guild of the greatest heroes in Arca and at its heart is the Duprian clan, the mightiest noble bloodline in MU. We are led by Duprian Winston, a knight who knows no equal in the whole of the MU empire.',
    1219: 'Gens Ranking Reward',
    1221: 'Gens Vanert is a noble family led by Vanert Reicht, the greatest socialite in the whole of the MU empire. The master strives around the clock to put a stop to Duprian Winston and his dream of absolute rule over the empire.',
    1222: 'Gens dispute��? Gens Vanert��s rebellion is more like it. The gens dispute started because of the greed of Vanert Reicht, the commanding knight of Gens Vanert. Exactly five years ago, a band of heroes who were searching in La Cleon for a stone with the power to seal away Kundun were slaughtered. At the time, we believed it was the work of Selupan, a giant spider and the ruler of La Cleon, but soon learned that it was actually Gens Vanert. It is the duty of our proud Gens Duprian champions to retaliate and fight.',
    1223: 'Gens ranking rewards are given out in the first week of each month.',
    1224: 'Get rid of Kundun and 10 Schrikers, the guard soldiers in the innermost depth of Kalima 6 and come back to me to get reward. (Party Possible)',
    1243: 'Give me a letter of request.',
    1244: 'Give me some time to prepare. (Refuse)',
    1252: 'Glory to the Gens',
    1253: 'Go ahead and learn the Fire Ball skill.',
    1254: 'Go back.',
    1255: 'Go beyond the walls of Elveland and hunt down 3 Strange Rabbits.',
    1256: "Go beyond the walls of Elveland and hunt down 3 Strange Rabbits.;If you find yourself in trouble, press the Q button to recover your HP. I'm sure this hunt is well within your abilities.",
    1257: 'Go beyond the walls of Elveland and hunt down 30 Polluted Butterflies.',
    1258: "Go beyond the walls of Elveland and hunt down 30 Polluted Butterflies. I'm sure this hunt is well within your abilities.",
    1259: 'Go beyond the walls of Lorencia and hunt down 3 Budge Dragons.',
    1260: "Go beyond the walls of Lorencia and hunt down 3 Budge Dragons.;If you find yourself in trouble, press the Q button to recover your HP. I'm sure this hunt is well within your abilities.",
    1261: 'Go beyond the walls of Lorencia and hunt down 30 Hounds.',
    1262: "Go beyond the walls of Lorencia and hunt down 30 Hounds. I'm sure this hunt is well within your abilities.",
    1263: 'Go beyond the walls of Noria and hunt down 3 Chain Scorpions.',
    1264: "Go beyond the walls of Noria and hunt down 3 Chain Scorpions.;If you find yourself in trouble, press the Q button to recover your HP. I'm sure this hunt is well within your abilities.",
    1265: 'Go beyond the walls of Noria and hunt down 30 Beetle Monsters.',
    1266: "Go beyond the walls of Noria and hunt down 30 Beetle Monsters. I'm sure this hunt is well within your abilities.",
    1267: 'Go find the merchant in town and bring back 5 apples.',
    1268: "Go find the merchant in town and bring back 5 apples.;The NPC's name will be shown in light blue, and the point symbol will turn into a tooth symbol when you scroll over it with your mouse.",
    1269: 'Go past the castle gate and defeat two Red Skulls who have hidden the Absolute Weapon. This will buy you some more time and reveal a casket containing the weapon. Destroy the casket, defeat more monsters, and return the Absolute Weapon to Archangel to successfully complete the Blood Castle quest.',
    1270: 'Go see the potion merchant again and buy just 1 Town Portal Scroll.',
    1271: "Go to Devias 4 and defeat 5 Ice Queens. Once that's done, you'll be able to receive a reward from the Shadow Phantom Soldier.",
    1272: "Go to Devias 4 and defeat 5 Ice Queens. When you return, I'll give you Ancient Gloves + 7 as a reward.",
    1273: "Go to Devias 4 and defeat 5 Ice Queens. When you return, I'll give you Eclipse Gloves + 7 as a reward.",
    1274: 'Go to Devil Square Level 1. Defeat the monsters that appear and survive to the bitter end to receive a reward from the Shadow Phantom Soldier. However, this applies only to Devil Square Level 1.',
    1275: 'Go to Devil Square Level 2. Defeat the monsters that appear and survive to the bitter end to receive a reward from the Shadow Phantom Soldier. However, this applies only to Devil Square Level 2.',
    1276: 'Go to Devil Square Level 3. Defeat the monsters that appear and survive to the bitter end to receive a reward from the Shadow Phantom Soldier. However, this applies only to Devil Square Level 3.',
    1277: 'Go to Devil Square Level 4. Defeat the monsters that appear and survive to the bitter end to receive a reward from the Shadow Phantom Soldier. However, this applies only to Devil Square Level 4.',
    1278: 'Go to Devil Square Level 5. Defeat the monsters that appear and survive to the bitter end to receive a reward from the Shadow Phantom Soldier. However, this applies only to Devil Square Level 5.',
    1279: 'Go to Devil Square Level 6. Defeat the monsters that appear and survive to the bitter end to receive a reward from the Shadow Phantom Soldier. However, this applies only to Devil Square Level 6.',
    1280: 'Go to Devil Square Level 7. Defeat the monsters that appear and survive to the bitter end to receive a reward from the Shadow Phantom Soldier. However, this applies only to Devil Square Level 7.',
    1281: "Go to Dungeon Level 2 and defeat 50 Chief Skeleton Warriors and 30 Thunder Liches. Once that's done, you'll be able to receive a reward from the Shadow Phantom Soldier.",
    1282: "Go to Dungeon Level 2 and defeat 50 Hell Hounds and 30 Hell Spiders. Once that's done, you'll be able to receive a reward from the Shadow Phantom Soldier.",
    1283: "Go to Dungeon Level 2 and defeat 50 Hell Spiders and 30 Chief Skeleton Warriors. Once that's done, you'll be able to receive a reward from the Shadow Phantom Soldier.",
    1284: "Go to Dungeon Level 2 and defeat 50 Poison Bull Fighters and 30 Dark Knights. Once that's done, you'll be able to receive a reward from the Shadow Phantom Soldier.",
    1285: "Go to Dungeon Level 2 and defeat 50 Skeleton Archers and 30 Hell Hounds. Once that's done, you'll be able to receive a reward from the Shadow Phantom Soldier.",
    1286: "Go to Dungeon Level 2. Defeat 40 Hell Hounds and return to the Shadow Phantom Soldier to receive an Invisibility Cloak + 1, which you'll need to enter Blood Castle.",
    1287: "Go to Dungeon Level 2. Defeat 50 Chief Skeleton Warriors and 30 Thunder Liches, and I'll give you a Dragon Helm + 8 as a reward.",
    1288: "Go to Dungeon Level 2. Defeat 50 Chief Skeleton Warriors and 30 Thunder Liches, and I'll give you a Guardian Helm + 8 as a reward.",
    1289: "Go to Dungeon Level 2. Defeat 50 Chief Skeleton Warriors and 30 Thunder Liches, and I'll give you a Legendary Armor + 8 as a reward.",
    1290: "Go to Dungeon Level 2. Defeat 50 Chief Skeleton Warriors and 30 Thunder Liches, and I'll give you a Red Wing Armor + 8 as a reward.",
    1291: "Go to Dungeon Level 2. Defeat 50 Cyclopses and 30 Ghosts, and I'll give you Legendary Gloves + 8 as a reward.",
    1292: "Go to Dungeon Level 2. Defeat 50 Cyclopses and 30 Ghosts, and I'll give you Red Wing Gloves + 8 as a reward.",
    1293: "Go to Dungeon Level 2. Defeat 50 Hell Hounds and 30 Hell Spiders, and I'll give you Dragon Boots + 8 as a reward.",
    1294: "Go to Dungeon Level 2. Defeat 50 Hell Hounds and 30 Hell Spiders, and I'll give you Guardian Boots + 8 as a reward.",
    1295: "Go to Dungeon Level 2. Defeat 50 Hell Hounds and 30 Hell Spiders, and I'll give you a Legendary Helm + 8 as a reward.",
    1296: "Go to Dungeon Level 2. Defeat 50 Hell Hounds and 30 Hell Spiders, and I'll give you a Red Wing Helm + 8 as a reward.",
    1297: "Go to Dungeon Level 2. Defeat 50 Hell Spiders and 30 Chief Skeleton Warriors, and I'll give you Legendary Pants + 8 as a reward.",
    1298: "Go to Dungeon Level 2. Defeat 50 Hell Spiders and 30 Chief Skeleton Warriors, and I'll give you Red Wing Pants + 8 as a reward.",
    1299: "Go to Dungeon Level 2. Defeat 50 Skeleton Archers and 30 Hell Hounds, and I'll give you Dragon Gloves + 8 as a reward.",
    1300: "Go to Dungeon Level 2. Defeat 50 Skeleton Archers and 30 Hell Hounds, and I'll give you Guardian Gloves + 8 as a reward.",
    1301: "Go to Dungeon Level 2. Defeat 50 Skeleton Archers and 30 Hell Hounds, and I'll give you Legendary Boots + 8 as a reward.",
    1302: "Go to Dungeon Level 2. Defeat 50 Skeleton Archers and 30 Hell Hounds, and I'll give you Red Wing Boots + 8 as a reward.",
    1303: "Go to Dungeon Level 3 and defeat 50 Dark Knights and 10 Gorgons. Once that's done, you'll be able to receive a reward from the Shadow Phantom Soldier.",
    1304: "Go to Dungeon Level 3. Defeat 50 Dark Knights and 10 Gorgons, and I'll give you a Dragon Armor + 8 as a reward.",
    1305: "Go to Dungeon Level 3. Defeat 50 Dark Knights and 10 Gorgons, and I'll give you a Guardian Armor + 8 as a reward.",
    1306: "Go to Dungeon Level 3. Defeat 50 Poison Bull Fighters, 5 Dark Knights, and 1 Gorgon, and I'll give you a Legendary Staff + 7 as a reward.",
    1307: "Go to Dungeon Level 3. Defeat 50 Poison Bull Fighters, 5 Dark Knights, and 1 Gorgon, and I'll give you a Red Wing Stick + 7 as a reward.",
    1308: "Go to Dungeon Level 3. Defeat 50 Poison Bull Fighters, 50 Dark Knights, and 30 Gorgons, and I'll give you a Bluewing Crossbow + 8 + Skill as a reward.",
    1309: "Go to Dungeon Level 3. Defeat 50 Poison Bull Fighters, 50 Dark Knights, and 30 Gorgons, and I'll give you two Double Blades + 8 + Skill as a reward.",
    1310: "Go to Dungeon Level 3. Defeat 60 Gorgons and return to the Shadow Phantom Soldier to receive an Invisibility Cloak + 2, which you'll need to enter Blood Castle.",
    1311: "Go to Dungeon Levels 1 and 2 and defeat 50 Cyclopses and 30 Ghosts. Once that's done, you'll be able to receive a reward from the Shadow Phantom Soldier.",
    1312: "Go to Dungeon Levels 1 and 2 and defeat 50 Skeleton Archers and 30 Hell Hounds. Once that's done, you'll be able to receive a reward from the Shadow Phantom Soldier.",
    1313: "Go to Dungeon Levels 2 and 3 and defeat 50 Poison Bull Fighters, 5 Dark Knights, and 1 Gorgon. Once that's done, you'll be able to receive a reward from the Shadow Phantom Soldier.",
    1314: "Go to Dungeon Levels 2 and 3 and defeat 50 Poison Bull Fighters, 50 Dark Knights, and 30 Gorgons. Once that's done, you'll be able to receive a reward from the Shadow Phantom Soldier.",
    1315: "Go to Dungeon Levels 2 and 3. Defeat 50 Poison Bull Fighters and 30 Dark Knights, and I'll give you Dragon Pants + 8 as a reward.",
    1316: "Go to Dungeon Levels 2 and 3. Defeat 50 Poison Bull Fighters and 30 Dark Knights, and I'll give you Guardian Pants + 8 as a reward.",
    1317: "Go to Elveland 2. Defeat 40 Cursed Liches and return to the Shadow Phantom Soldier to receive a Devil's Invitation + 1, which you will need to enter Devil Square.",
    1318: "Go to Elveland 3 and defeat 100 Captain Grizzlies. I'll give you an Ancient Helm + 7 and Ancient Pants + 7 as a reward.",
    1319: "Go to Elveland 3 and defeat 100 Captain Grizzlies. I'll give you an Eclipse Helm + 7 and Eclipse Pants + 7 as a reward.",
    1320: "Go to Elveland 3 and defeat 100 Captain Grizzlies. Once that's done, you'll be able to receive a reward from the Shadow Phantom Soldier.",
    1321: "Go to Elveland 3 and defeat 100 Grizzlies. I'll give you Ancient Boots + 7 as a reward.",
    1322: "Go to Elveland 3 and defeat 100 Grizzlies. I'll give you Eclipse Boots + 7 as a reward.",
    1323: "Go to Elveland 3 and defeat 100 Grizzlies. Once that's done, you'll be able to receive a reward from the Shadow Phantom Soldier.",
    1324: "Go to Icarus, kill 20 Alquamoses and 10 Alpha Crusts and return to 'Shadow Phantom Soldier' to claim your reward.",
    1325: "Go to Icarus, kill 20 Alquamoses and 20 Drakans and return to 'Shadow Phantom Soldier' to claim your reward.",
    1326: "Go to Icarus, kill 20 Alquamoses and return to 'Shadow Phantom Soldier' with 1 Crystal Sword (Attack power +12) to claim your reward.",
    1327: "Go to Icarus, kill 20 Alquamoses and return to 'Shadow Phantom Soldier' with 1 Sword of Destruction (Attack power +12) to claim your reward.",
    1328: "Go to Icarus, kill 30 Queen Rainiers and return to 'Shadow Phantom Soldier' to claim your reward.",
    1329: "Go to Icarus. Defeat 100 Phantom Knights and return to the Shadow Phantom Soldier to receive an Invisibility Cloak + 6, which you'll need to enter Blood Castle.",
    1330: 'Go to Icarus. Defeat 130 Giant Drakans and return to the Shadow Phantom Soldier to receive a Scroll of Blood + 5, which you will need to enter Illusion Temple.',
    1331: "Go to Icarus. Defeat 80 Alquamoses and return to the Shadow Phantom Soldier to receive a Devil's Invitation + 3, which you will need to enter Devil Square.",
    1332: "Go to Icarus. Defeat 80 Mega Crusts and return to the Shadow Phantom Soldier to receive an Invisibility Cloak + 4, which you'll need to enter Blood Castle.",
    1333: 'Go to Icarus. Defeat 90 Drakans and return to the Shadow Phantom Soldier to receive a Scroll of Blood + 3, which you will need to enter Illusion Temple.',
    1334: "Go to Kanturu Relics. Defeat 100 Dreadfears and return to the Shadow Phantom Soldier to receive an Invisibility Cloak + 8, which you'll need to enter Blood Castle.",
    1335: "Go to Kanturu Relics. Defeat 100 Twin Tails and return to the Shadow Phantom Soldier to receive an Invisibility Cloak + 7, which you'll need to enter Blood Castle.",
    1336: "Go to Kanturu Ruins, kill 20 Splinter Wolves and 10 Blade Hunters and return to 'Shadow Phantom Soldier' to claim your reward.",
    1337: "Go to Kanturu Ruins, kill 20 Splinter Wolves and 20 Satyroses and return to 'Shadow Phantom Soldier' to claim your reward.",
    1338: "Go to Kanturu Ruins, kill 20 Splinter Wolves and 5 Kentauroses and return to 'Shadow Phantom Soldier' to claim your reward.",
    1339: "Go to Kanturu Ruins, kill 20 Splinter Wolves and return to 'Shadow Phantom Soldier' with 1 Ancient Stick (Wizardry damage +12) to claim your reward.",
    1340: "Go to Kanturu Ruins, kill 30 Iron Riders and return to 'Shadow Phantom Soldier' to claim your reward.",
    1341: "Go to La Cleon. Defeat 120 Ice Walkers and return to the Shadow Phantom Soldier to receive a Devil's Invitation + 6, which you will need to enter Devil Square.",
    1342: 'Go to Lost Tower Level 4-6 and defeat 100 Devils. Go back to the Shadow Phantom Soldier to receive a choice between 15 SD Potions and 15 Complex Potions as your reward.',
    1343: 'Go to Tarkan 2 and defeat 30 Zaikans. Go see the Shadow Phantom Soldier again to receive a choice between 20 Large SD Potions and 30 Large Complex Potions as your reward.',
    1344: "Go to Tarkan 2. Defeat 100 Beam Knights and return to the Shadow Phantom Soldier to receive a Devil's Invitation + 5, which you will need to enter Devil Square.",
    1345: "Go to Tarkan 2. Defeat 100 Tantaloses and return to the Shadow Phantom Soldier to receive an Invisibility Cloak + 5, which you'll need to enter Blood Castle.",
    1346: 'Go to Tarkan 2. Defeat 30 Death Beam Knights and return to the Shadow Phantom Soldier to receive a Scroll of Blood + 4, which you will need to enter Illusion Temple.',
    1347: "Go to Tarkan, kill 20 Mutants and 10 Beam Knights and return to 'Shadow Phantom Soldier' to claim your reward.",
    1348: "Go to Tarkan, kill 20 Mutants and 20 Tantaloses and return to 'Shadow Phantom Soldier' to claim your reward.",
    1349: "Go to Tarkan, kill 20 Mutants and return to 'Shadow Phantom Soldier' with 1 Staff of Resurrection (Wizardry damage +12) to claim your reward.",
    1350: "Go to Tarkan, kill 20 Mutants and return to 'Shadow Phantom Soldier' with 10 Unirias to claim your reward.",
    1351: "Go to Tarkan, kill 30 Iron Wheels and return to 'Shadow Phantom Soldier' to claim your reward.",
    1352: "Go to Tarkan. Defeat 100 Iron Wheels and return to the Shadow Phantom Soldier to receive a Devil's Invitation + 4, which you will need to enter Devil Square.",
    1353: 'Go to Tarkan. Defeat 50 Bloody Wolves and return to the Shadow Phantom Soldier to receive a Scroll of Blood + 1, which you will need to enter Illusion Temple.',
    1354: 'Go to Tarkan. Defeat 70 Iron Wheels and return to the Shadow Phantom Soldier to receive a Scroll of Blood + 2, which you will need to enter Illusion Temple.',
    1355: "Go to Varka and eliminate Advisor Jerind and Gaion Kharein. When you finish the job and come back to me, I'll give you the reward from the guild. Also, you can get the refund without the Lv. 1 Request Completion Certificate when you complete this task.",
    1356: "Go to Vulcanus and eliminate 50 Blood Assassins, and I'll give you a reward.",
    1357: "Go to the Lost Tower Level 1 and defeat 100 Shadows. I'll give you an Ancient Armor + 7 and a Chaos Dragon Axe + 4 + Option as a reward.",
    1358: "Go to the Lost Tower Level 1 and defeat 100 Shadows. I'll give you an Eclipse Armor + 7 and a Chaos Dragon Axe + 4 + Option as a reward.",
    1359: "Go to the Lost Tower Level 1 and defeat 100 Shadows. Once that's done, you'll be able to receive a reward from the Shadow Phantom Soldier.",
    1360: "Go to the Lost Tower Level 1 and defeat 50 Shadows and 50 Poison Shadows. Once that's done, you'll be able to receive a reward from the Shadow Phantom Soldier.",
    1361: "Go to the Lost Tower Level 1. Defeat 50 Shadows and 30 Poison Shadows, and I'll give you Ancient Gloves + 8 as a reward.",
    1362: "Go to the Lost Tower Level 1. Defeat 50 Shadows and 30 Poison Shadows, and I'll give you Eclipse Gloves + 8 as a reward.",
    1363: "Go to the Lost Tower Level 1. Defeat 50 Shadows and 50 Poison Shadows, and I'll give you Ashcrow Gloves + 7 as a reward.",
    1364: "Go to the Lost Tower Level 1. Defeat 50 Shadows and 50 Poison Shadows, and I'll give you Iris Gloves + 7 as a reward.",
    1365: "Go to the Lost Tower Level 2 and defeat 50 Poison Shadows and 30 Cursed Wizards. Once that's done, you'll be able to receive a reward from the Shadow Phantom Soldier.",
    1366: "Go to the Lost Tower Level 2. Defeat 50 Poison Shadows and 30 Cursed Wizards, and I'll give you Ancient Boots + 8 as a reward.",
    1367: "Go to the Lost Tower Level 2. Defeat 50 Poison Shadows and 30 Cursed Wizards, and I'll give you Ashcrow Boots + 7 as a reward.",
    1368: "Go to the Lost Tower Level 2. Defeat 50 Poison Shadows and 30 Cursed Wizards, and I'll give you Eclipse Boots + 8 as a reward.",
    1369: "Go to the Lost Tower Level 2. Defeat 50 Poison Shadows and 30 Cursed Wizards, and I'll give you Iris Boots + 7 as a reward.",
    1370: "Go to the Lost Tower Level 3 and defeat 50 Cursed Wizards and 50 Death Cows. Once that's done, you'll be able to receive a reward from the Shadow Phantom Soldier.",
    1371: "Go to the Lost Tower Level 3. Defeat 50 Cursed Wizards and 50 Death Cows, and I'll give you an Ancient Helm + 8 as a reward.",
    1372: "Go to the Lost Tower Level 3. Defeat 50 Cursed Wizards and 50 Death Cows, and I'll give you an Ashcrow Helm + 7 and Ashcrow Pants + 7 as a reward.",
    1373: "Go to the Lost Tower Level 3. Defeat 50 Cursed Wizards and 50 Death Cows, and I'll give you an Eclipse Helm + 8 as a reward.",
    1374: "Go to the Lost Tower Level 3. Defeat 50 Cursed Wizards and 50 Death Cows, and I'll give you an Iris Helm + 7 and Iris Pants + 7 as a reward.",
    1375: "Go to the Lost Tower Level 4 and defeat 50 Death Cows and 30 Devils. Once that's done, you'll be able to receive a reward from the Shadow Phantom Soldier.",
    1376: "Go to the Lost Tower Level 4. Defeat 50 Death Cows and 30 Devils, and I'll give you Ashcrow Gloves + 8 as a reward.",
    1377: "Go to the Lost Tower Level 4. Defeat 50 Death Cows and 30 Devils, and I'll give you Iris Gloves + 8 as a reward.",
    1378: "Go to the Lost Tower Level 7 and defeat 50 Death Gorgons and 10 Balrogs. Once that's done, you'll be able to receive a reward from the Shadow Phantom Soldier.",
    1379: "Go to the Lost Tower Level 7 and defeat 50 Death Knights and 50 Death Gorgons. Once that's done, you'll be able to receive a reward from the Shadow Phantom Soldier.",
    1380: "Go to the Lost Tower Level 7 and defeat 50 Death Knights, 30 Death Gorgons, and 20 Balrogs. Once that's done, you'll be able to receive a reward from the Shadow Phantom Soldier.",
    1381: "Go to the Lost Tower Level 7. Defeat 50 Death Gorgons and 10 Balrogs, and I'll give you an Ashcrow Armor + 8 as a reward.",
    1382: "Go to the Lost Tower Level 7. Defeat 50 Death Gorgons and 10 Balrogs, and I'll give you an Iris Armor + 8 as a reward.",
    1383: "Go to the Lost Tower Level 7. Defeat 50 Death Knights and 30 Death Gorgons, and I'll give you Ashcrow Pants + 8 as a reward.",
    1384: "Go to the Lost Tower Level 7. Defeat 50 Death Knights and 30 Death Gorgons, and I'll give you Iris Pants + 8 as a reward.",
    1385: "Go to the Lost Tower Level 7. Defeat 50 Death Knights, 30 Death Gorgons, and 20 Balrogs, and I'll give you a Crystal Sword + 7 + Skill as a reward.",
    1386: "Go to the Lost Tower Level 7. Defeat 50 Death Knights, 30 Death Gorgons, and 20 Balrogs, and I'll give you an Aquagold Crossbow + 7 + Skill as a reward.",
    1387: "Go to the Lost Tower Levels 2 and 3. Defeat 60 Death Cows and return to the Shadow Phantom Soldier to receive a Devil's Invitation + 2, which you will need to enter Devil Square.",
    1388: "Go to the Lost Tower Levels 3 and 4 and defeat 100 Death Cows. I'll give you Ancient Pants + 8 as a reward.",
    1389: "Go to the Lost Tower Levels 3 and 4 and defeat 100 Death Cows. I'll give you Eclipse Pants + 8 as a reward.",
    1390: "Go to the Lost Tower Levels 3 and 4 and defeat 100 Death Cows. I'll give you an Ashcrow Armor + 7 and a Chaos Dragon Axe + 4 + Option as a reward.",
    1391: "Go to the Lost Tower Levels 3 and 4 and defeat 100 Death Cows. I'll give you an Iris Armor + 7 and a Chaos Dragon Axe + 4 + Option as a reward.",
    1392: "Go to the Lost Tower Levels 3 and 4 and defeat 100 Death Cows. Once that's done, you'll be able to receive a reward from the Shadow Phantom Soldier.",
    1393: "Go to the Lost Tower Levels 4 and 5 and defeat 100 Devils. I'll give you Ashcrow Boots + 8 as a reward.",
    1394: "Go to the Lost Tower Levels 4 and 5 and defeat 100 Devils. I'll give you Iris Boots + 8 as a reward.",
    1395: "Go to the Lost Tower Levels 4 through 6 and defeat 100 Devils. I'll give you an Ancient Armor + 8 as a reward.",
    1396: "Go to the Lost Tower Levels 4 through 6 and defeat 100 Devils. I'll give you an Eclipse Armor + 8 as a reward.",
    1397: "Go to the Lost Tower Levels 4 through 6 and defeat 100 Devils. Once that's done, you'll be able to receive a reward from the Shadow Phantom Soldier.",
    1398: "Go to the Lost Tower Levels 4 through 6, and you'll encounter Devils that use dark magic. Defeat 50 Devils and return to me for a reward.",
    1399: "Go to the Lost Tower Levels 4 through 6, and you'll encounter Devils that use dark magic. Defeat 60 Devils and return to me for a reward.",
    1400: "Go to the Lost Tower Levels 5 through 7 and defeat 100 Death Knights. I'll give you a Legendary Staff + 8 as a reward.",
    1401: "Go to the Lost Tower Levels 5 through 7 and defeat 100 Death Knights. I'll give you a Red Wing Stick + 8 as a reward.",
    1402: "Go to the Lost Tower Levels 5 through 7 and defeat 100 Death Knights. I'll give you an Ashcrow Helm + 8 as a reward.",
    1403: "Go to the Lost Tower Levels 5 through 7 and defeat 100 Death Knights. I'll give you an Iris Helm + 8 as a reward.",
    1404: "Go to the Lost Tower Levels 5 through 7 and defeat 100 Death Knights. Once that's done, you'll be able to receive a reward from the Shadow Phantom Soldier.",
    1405: "Go to the Lost Tower. Defeat 80 Death Knights and return to the Shadow Phantom Soldier to receive an Invisibility Cloak + 3, which you'll need to enter Blood Castle.",
    1406: 'Go to the Swamp of Peace and defeat 100 Shadow Pawns. Go see the Shadow Phantom Soldier again to receive a choice between 30 Large SD Potions and 45 Large Complex Potions as your reward.',
    1407: "Go to the Swamp of Peace. Defeat 140 Shadow Knights and return to the Shadow Phantom Soldier to receive a Devil's Invitation + 7, which you will need to enter Devil Square.",
    1408: 'Go to the Swamp of Peace. Defeat 150 Shadow Looks and return to the Shadow Phantom Soldier to receive a Scroll of Blood + 6, which you will need to enter Illusion Temple.',
    1409: 'Go to the area between Tarkan 1 and Tarkan 2, and you will see these assassins known as Iron Wheels. Defeat 60 Iron Wheels and return to me for a reward.',
    1439: "Good decision. The first mission for the second trial involves defeating 10 Guardsmen in Chaos Castle, delivering Archangel's weapon in Blood Castle, and surviving until the end of Devil Square. Complete the mission and you'll be rewarded with either a Jewel of Bless, a Jewel of Soul, a Jewel of Chaos, or a Jewel of Harmony.",
    1440: "Good decision. The first mission of the fifth trial involves surviving in Chaos Castle, delivering Archangel's weapon in Blood Castle, and surviving until the end of Devil Square. Complete the mission and you'll be rewarded with either a Jewel of Bless, a Jewel of Life, a Jewel of Harmony, or two Jewels of Soul.",
    1441: "Good decision. The first mission of the fourth trial involves defeating 30 Guardsmen in Chaos Castle, delivering Archangel's weapon in Blood Castle, and surviving until the end of Devil Square. Complete the mission and you'll be rewarded with either a Jewel of Bless, a Jewel of Life, a Jewel of Harmony, or two Jewels of Soul.",
    1442: "Good decision. The first mission of the last trial involves surviving in Chaos Castle, delivering Archangel's weapon in Blood Castle, and surviving until the end of Devil Square. Complete this mission successfully and you may be reborn as hero. Your fame will echo across the whole continent of MU. You'll be rewarded with either a Jewel of Bless, two Jewels of Life, or two Jewels of Soul upon completion.",
    1443: "Good decision. This mission requires you to raise your worth by claiming victory in Illusion Temple. Complete the mission and you'll be rewarded with 800,000 Exp.",
    1444: 'Good job. The energy of insanity is safely contained since Necrons and Death Centurions have been eliminated. But the portion they already absorbed has been transferred to Kundun so we need to directly attack him. Can you help us? (Lv. 350 - 400)',
    1445: 'Good job. You made it easier for us to protect the temple entrance. The 2nd goal is to punish the enemies attacking the sealed stone. Etramu saved the empire by changing his body into a sealed stone, but his soul is getting engulfed with madness. Do you want to proceed? (Lv. 350 - 400)',
    1456: "Grand Wizard Etramu vowed to destroy Illusion Sorcery and formed an army to subjugate its followers. Under Etramu's command, the alliance engaged the followers of Illusion Sorcery with formidable force. Despite having been driven all the way back to Illusion Temple, the followers continued to resist. As battle raged on, Lev disappeared and left the followers of Illusion Sorcery in confusion. Ultimately, they all met their death at the hands of the alliance on the temple grounds.",
    1470: 'Great! I finally get the chance to show off what I can do.',
    1471: "Great! I'll finish this tutorial in no time!",
    1511: "Have you been to Chaos Castle? If not, it'll be an excellent opportunity to prove your strength. Why don't you listen to what I have to say and then decide? (Basic character: Level 50-119, Advanced character: Level 30-99)",
    1512: "Have you cleared today's request? Show me Lv. 1 Request Completion Certificate then.",
    1513: "Have you ever heard of Blood Castle's barrier? Would you like to hear Archangel's request to help defend Blood Castle's barrier and join in the fight for the castle? (Basic character: Level 15-80, Advanced character: Level 10-60)",
    1514: "Have you ever heard of Blood Castle's barrier? Would you like to hear Archangel's request to help defend Blood Castle's barrier and join the fight for the castle? (Basic character: Level 81-130, Advanced character: Level 61-110)",
    1515: "Have you ever heard of Illusion Temple and the ancient relics hidden there? It's a place where travelers can find both wealth and fame. Why don't you listen to what I have to say and then decide? (All characters: Level 220-270)",
    1516: "Have you ever heard of Illusion Temple and the ancient relics hidden there? It's a place where travelers can find both wealth and fame. Why don't you listen to what I have to say and then decide? (All characters: Level 271-320)",
    1517: "Having set his eyes on the tree's power of birth, Secrarium corrupted the Elf Tree and transformed it into an Immoral Tree that gave birth to monsters.  The monsters horde grew to astronomical proportions, and the kingdoms of the MU continent combined their forces to entrap the immoral tree in a space of nothingness.",
    1518: "Having trustworthy comrades at your side makes all the difference when it comes to Blood Castle quests. However, it will still be hard for you to obtain an Invisibility Cloak that's right for your level. I have a quest that will earn you an item you'll need to enter Blood Castle. Will you accept this quest? (Basic character: Level 331-400, Advanced character: Level 311-400)",
    1528: 'Hear what the Shadow Phantom Soldier has to say and take the Blood Castle challenge. Successfully complete the Blood Castle quest to receive a valuable reward.',
    1529: 'Hear what the Shadow Phantom Soldier has to say and take the Chaos Castle challenge. If you survive Chaos Castle, you can claim a hefty reward.',
    1530: 'Hear what the Shadow Phantom Soldier has to say and take the Devil Square challenge. Training at Devil Square will earn you a valuable reward.',
    1531: 'Hear what the Shadow Phantom Soldier has to say and take the Illusion Temple challenge. Win at Illusion Temple to claim a valuable reward.',
    1542: 'Help the reconnaissance party....',
    1545: "Here is the Letter of Request for you. Right click on the letter to check the information. Please note that you cannot receive refund of 500,000 Zen deposit if you give up the quest. You also need to bring the 'Request Completion Certificate' to get the refund. Once again, you need to press (T) and click 'Start Quest' button at the bottom to check the information again once you close the information window. Good bye, then.",
    1546: 'Here it is.',
    1547: 'Here you go.',
    1548: "Here's your first question.;How do you trade with a character that's in front of you?",
    1550: 'Heroic Courage',
    1551: 'Heroic Fighting Spirit',
    1552: 'Heroic Mentality',
    1553: 'Heroic Qualities',
    1554: 'Heroic Tenacity',
    1555: "Hi, I'm Priestess Beina, protector of this Underwater Temple. The sealed stone got stronger thanks to your effort, but Kundun's army is also getting stronger now. We investigated the sealed stone and found that Kundun's army absorbs its energy while Etramu's soul is taking a rest. Please help us and confine the energy of insanity within the sealed stone. (Lv. 350 - 400)",
    1556: "Hi, I'm Priestess Beina, protector of this Underwater Temple. This temple is Kundun's first target since Etramu keeps his body in the sealed stone. We're always short of fighters so I request help to the mercenary guild. Would you check the request? (Lv. 350 - 400)",
    1557: 'Hidden history of the rebellion',
    1561: "High ranking monsters deep inside the Lost Tower have launched a surprise attack on our reconnaissance party. Under the captain's orders to retaliate, we are now forming a punishment force. Will you accept this quest? (Level 206-209)",
    1564: 'Hmm, Letter of Request����',
    1565: 'Hmm, free mercenary����',
    1566: "Hmm... that doesn't sound all that bad.",
    1567: 'Hmm... you are a wise warrior. Go now and achieve great things in the name Gens Vanert, knowing that I will always be here to assist you.',
    1568: 'Hmm...First, press M and then...',
    1569: 'Hmm...a test...',
    1570: 'Hold on, I will find a quest suitable for you. Wait a moment please. (Level 260-289)',
    1571: 'Hold on, I will find a quest suitable for you. Wait a moment please. (Level 290-319)',
    1572: 'Hold on, I will find a quest suitable for you. Wait a moment please. (Level 320-349)',
    1580: "How can I turn him down...?;Alright, let's give it a try!",
    1581: 'How do I check coordinates?',
    1582: 'How do I get it?',
    1583: 'How do you do? I am Gregory, the Gens Duprian Steward. What is your business with our gens?',
    1584: "How have you been? On behalf of the master of our clan, I thank you for answering the call of the clan. I personally hate to let the wandering mercenaries do this job, so I requested to send someone of the clan. I hope this didn't offend you. (Lv. 350 - 400)",
    1585: 'How much is the registration fee and the deposit?',
    1586: 'How will you help, exactly?',
    1587: 'However, journeys such as this are bound to be perilous.;If you wish, we can provide you with a simple tutorial. What do you say?',
    1588: "Hunt down 10 Spiders from around town, and I'll give you a reward.",
    1590: 'Hunting down measly Spiders is beneath me. (Refuse)',
    1591: 'Hunting down monsters....',
    1592: 'Hunting monsters will earn you EXP points, drop items, and Zens.',
    1600: 'I accept the mission. (Accept)',
    1601: 'I accept your quest. (Accept)',
    1602: 'I already knew that.',
    1603: "I already knew that. What's the next quest?",
    1604: 'I am not ready yet. (Refuse)',
    1605: 'I can almost see the end! (Accept)',
    1606: "I can't pass up on this. (Accept)",
    1607: "I didn't mean to pester you. But as the clan gets stronger, so do you. Please come back if you change your mind. (The quest has been cancelled.)",
    1608: "I don't feel like doing it. (Refuse)",
    1609: "I don't have the time right now. (Refuse)",
    1610: "I don't have the time right now. I'll do it next time.",
    1611: "I don't have the time. I'm sorry. (Refuse)",
    1612: "I don't have time right now. I'll come back later. (Refuse)",
    1613: "I don't know how this story can help me. (Refuse)",
    1614: "I don't need to be judged like this! (Refuse)",
    1615: "I don't think I have time for that right now. (Refuse)",
    1616: "I don't want to decide right now. Just describe them for me.",
    1617: 'I give up. Going any further is beyond me. (Refuse)',
    1618: 'I got it!',
    1619: 'I guess Lugard was tricked by Secrarium. How do I participate?',
    1620: 'I have a monster hunt quest that will take you deeper into the Dungeon than before. Will you accept this quest? (Level 101-110)',
    1621: "I have a quest that will earn you an item you'll need to enter Blood Castle. Will you accept this quest? (Basic character: Level 131-180, Advanced character: Level 111-160)",
    1622: "I have a quest that will take you deep inside the Dungeon. It'll be harder than last time, but there's a better reward. Will you accept this quest? (Level 121-130)",
    1623: 'I have a quest that will take you deep inside the Dungeon. There have been reports of monsters attempting to make their way above ground under the command of Gorgons. I want you to defeat these monsters. (Level 111-120)',
    1624: 'I have a simple quest that will earn you a Scroll of Blood, which will grant you access to Illusion Temple. Will you accept? (All characters: Level 321-350)',
    1625: 'I have a simple quest that will earn you an invitation granting you access to Devil Square. Will you accept this quest? (Basic character: Level 181-230, Advanced character: Level 161-210)',
    1626: 'I have no time right now. (Refuse)',
    1627: 'I have plenty of experience.;To each his own!',
    1628: 'I hope you realize that a hero without a fighting spirit is merely a coward.',
    1629: 'I know it well. I hear you need a special item to go there....',
    1630: 'I know it well. I hear you need an item to participate in the event....',
    1631: 'I learned a skill!',
    1632: 'I need you to accept a small quest first as a test. Are you up to it? There is of course a reasonable reward for finishing.',
    1633: 'I neither have the skills nor the warriors I need to take on this quest. Give me more time.',
    1634: "I regret we can't be of any help to you.;Here, at least take this present. I hope, the next time we meet, a great warrior stands before my eyes.;Enjoy your time out there.",
    1635: 'I respect your decision to go on this journey.;Allow me to teach you a few simple but essential things you need to know before your adventure in MU begins.',
    1636: "I see you've now mastered hunting. When you hunt monsters, you can employ normal attacks by left-clicking or use skill attacks by right-clicking.",
    1637: "I see you've successfully completed your first hunt! Did you find it difficult? Hunting monsters will earn you EXP points, drop items, and Zens.;You can pick up items dropped by defeated monsters using the mouse or automatically by pressing the space bar.",
    1638: 'I see.',
    1639: 'I see. How do I enter?',
    1640: "I simply can't go on anymore. (Refuse)",
    1641: 'I think I have enough courage already. (Refuse)',
    1642: 'I think a quest involving the Dungeon, which is a headache for Lorencia, should be suitable for you. I want you to wipe out the monsters in the Dungeon, one by one. Will you accept this quest? (Level 91-100)',
    1643: 'I trust you are quite used to Devil Square by now. However, obtaining an invitation to Devil Square remains a difficult task. Luckily, I have a quest that will earn you an invitation. Will you accept this quest? (Basic character: Level 231-280, Advanced character: Level 211-260)',
    1644: 'I trust you are somewhat familiar with Blood Castle by now. You should now focus on building the bond between you and your comrades to the point where you can rely on each another unconditionally.',
    1645: "I trust you are somewhat familiar with Chaos Castle by now. However, it should still be difficult for you to acquire the necessary item. I have a quest for you. One through which you can earn the items you'll need in Chaos Castle.... Will you accept? (Basic character: Level 240-299, Advanced character: Level 220-279)",
    1646: 'I trust you are somewhat familiar with Chaos Castle by now. The event will now be even more challenging because you will face more powerful users and corrupt guardsmen.',
    1647: "I trust you are somewhat familiar with Devil Square by now. You'll now be moved to a place where even more powerful monsters spawn. There's no need to worry, however. You can expect rapid growth as long as you and your comrades execute coordinated attacks.",
    1648: "I trust you are somewhat familiar with Illusion Temple by now. You'll now be moved to a place where even more powerful monsters spawn. There's no need to worry, however. You can expect rapid growth as long as you and your comrades learn to work together.",
    1649: "I understand well. What's the next quest?",
    1650: 'I understand.',
    1651: 'I understand. I will do what I can.',
    1652: 'I want to be an Elf who focuses on defense!',
    1653: 'I want to be an Elf who focuses on wizardry!',
    1654: 'I want to hear more. (Accept)',
    1655: 'I will give you a quest that will earn you the item you need to enter the event. Will you accept this quest? (Basic character: Level 120-179, Advanced character: Level 100-159)',
    1656: "I will give you the queen's gifts if you pass a test to see if there's anything else you need to know and if you have the basic knowledge to travel throughout the MU realm. How about it?",
    1657: 'I will guide you through MU game play.',
    1658: 'I will help you. Tell me what to do. (Accept)',
    1659: 'I will inform you when a request of your level is delivered. Thank you.',
    1660: 'I will sign up. (Accept)',
    1661: "I will teach you basic hunting and controls through a simple tutorial.;It's not that difficult, and I'm sure you'll finish it in no time.",
    1662: 'I will teach you hunting and control commands through a simple tutorial.',
    1663: "I will tell you then. Devildom's royal guards, who were summoned when Kundun succumbed to Secrarium, posed a great threat to the heaven world. To protect their base, the Twelve Saints formed a barrier around Blood Castle.",
    1664: "I'd rather you give me the gifts without the test.",
    1665: "I'll explain this in more detail. What else do you wish to know?",
    1666: "I'll give you a full briefing when you're ready, then. May the grace of God be with you�� (The quest has been cancelled)",
    1667: "I'll give you a full briefing when you're ready, then. May the grace of God be with you�� (The quest has been cancelled.)",
    1668: "I'll head for Vulcanus immediately. (Accept)",
    1669: "I'll just take the queen's gifts without taking the test.",
    1670: "I'll stay focused until the very end! (Accept)",
    1671: "I'll test you to see if you have the basic knowledge required for travel throughout the MU empire and give you the queen's gifts if you pass.",
    1672: "I'm always up for hunting down monsters....",
    1673: "I'm busy now. I'll come back later. (Refuse)",
    1674: "I'm glad we can help. We aren't difficult to find.;Simply look for and talk to the Shadow Phantom Soldier in any of the towns.",
    1675: "I'm here for your request.",
    1676: "I'm not ready yet. Please wait. (Refuse)",
    1677: "I'm sorry to hear that. There are many ways to become stronger, but they'll all take time. Remember that well.",
    1678: "I'm sorry to hear that. You can't repeat the first mission if you abandon the second mission. You must complete the second mission before you can repeat the first mission. Please return if you change your mind.",
    1679: "I'm sorry. I don't have the time right now. (Refuse)",
    1680: "I'm sorry. I don't have the time. (Refuse)",
    1681: "I'm sure you are well aware of Kundun. The weakest and most disorganized monsters of Kundun's army are frequently attacking and plundering civilians just outside of town. I wanted to ask you to eliminate these plundering monsters.... Will you accept this quest? (Level 15-25)",
    1682: "I'm sure you have a long trail of defeated monsters behind you. However, travelers widely vary in terms of their skills. If you're unsure of your own skills, proving yourself at Chaos Castle should give you some clarity. I have a quest for you. One through which you can earn the items you'll need in Chaos Castle.... Will you accept? (All characters: Master Level)",
    1683: "I'm too busy to help right now.",
    1701: "Ice Walkers are attacking and weakening the barrier that was formed to separate La Cleon and Devias from one another. Go to La Cleon and defeat 120 Ice Walkers. Come see me once that's done to receive a Devil's Invitation + 6 as a reward. They are strong foes, and you should hunt them with the help of others.",
    1705: 'If you are an Agility Elf, whose priority is defense, you can equip a weapon and use its skills. If you are an Energy Elf, whose priority is wizardry, you can purchase orbs to learn skills.',
    1706: 'If you are equipped with a weapon imbued with a skill, you can activate that skill by assigning it to the Skill window.',
    1707: 'If you are equipped with a weapon imbued with a skill, you can activate that skill by assigning it to the Skill window.;Can you see the numbered slots at the bottom center of the screen? Click on the icon outlined in green, to the right of the number five slot.',
    1708: "If you don't want to receive party requests while hunting, simply type in 'Party off' in the Chat window. To start receiving party requests again, type in 'Request on' in the Chat window.",
    1709: 'If you find yourself far away from a town or cornered while on a hunt, the Town Portal Scroll can come in really handy.',
    1710: 'If you leave the gens, your contribution will be reset.;Do you still wish to leave?',
    1711: 'If you want to find out when you can enter, simply move your mouse over the Armor of Guardsman. If you want to enter, simply right-click on the armor at a designated time. Come see me when you have time, and I will give you a quest that will earn you the item needed to enter the event.',
    1722: "Illusion Spells, the foundation of Illusion Sorcery, was discovered by an Archaeologist named Mirage. Mirage found the spells' power to be too dangerous and sealed it. His partner Lev, however, stole the spells to brainwash people and establish Illusion Sorcery. Illusion Sorcery gradually grew larger and brought chaos to the continent.",
    1723: 'Illusion Temple Adaptation (1)',
    1724: 'Illusion Temple Adaptation (2)',
    1725: 'Illusion Temple Adaptation (3)',
    1726: 'Illusion Temple Challenge (1)',
    1727: 'Illusion Temple Challenge (2)',
    1728: 'Illusion Temple Challenge (3)',
    1730: 'Illusion Temple is a place where you can acquire items and equipment for fast growth. If you wish to possess such items and equipment for yourself, inquire with the Shadow Phantom Soldier about Illusion Temple.',
    1731: 'Illusion Temple is a place where you can find both wealth and fame. If you take the temple challenge, you might acquire something essential for your training. Would you like to take the challenge? (All characters: Level 271-320)',
    1732: 'Illusion Temple is a place where you can find both wealth and fame. If you take the temple challenge, you might acquire something essential for your training. Would you like to take the challenge? (All characters: Level 321-350)',
    1733: 'Illusion Temple is a place where you can find both wealth and fame. If you take the temple challenge, you might acquire something essential for your training. Would you like to take the challenge? (All characters: Level 351-380)',
    1734: 'Illusion Temple is a place where you can find both wealth and fame. If you take the temple challenge, you might acquire something essential for your training. Would you like to take the challenge? (All characters: Master Level)',
    1735: 'Illusion Temple...',
    1743: "In Blood Castle, you'll be fighting against time. Good armor and weapons will, of course, help you complete your quest, but more than anything else solidarity of your party is what will count there. Will you accept Archangel's quest? (All characters: Master Level)",
    1744: "In Blood Castle, you'll be fighting against time. Good armor and weapons will, of course, help you complete your quest. But more than anything else solidarity of your party is what will count there. Will you accept Archangel's quest? (Basic character: Level 231-280, Advanced character: Level 211-260)",
    1745: "In Blood Castle, you'll be fighting against time. Good armor and weapons will, of course, help you complete your quest. But more than anything else, solidarity of your party is what will count there. Will you accept Archangel's quest? (Basic character: Level 131-180, Advanced character: Level 111-160)",
    1746: "In Blood Castle, you'll be fighting against time. Good armor and weapons will, of course, help you complete your quest. But more than anything else, solidarity of your party is what will count there. Will you accept Archangel's quest? (Basic character: Level 15-80, Advanced character: Level 10-60)",
    1747: "In Blood Castle, you'll be fighting against time. Good armor and weapons will, of course, help you complete your quest. But more than anything else, solidarity of your party is what will count there. Will you accept Archangel's quest? (Basic character: Level 181-230, Advanced character: Level 161-210)",
    1748: "In Blood Castle, you'll be fighting against time. Good armor and weapons will, of course, help you complete your quest. But more than anything else, solidarity of your party is what will count there. Will you accept Archangel's quest? (Basic character: Level 281-330, Advanced character: Level 261-310)",
    1749: "In Blood Castle, you'll be fighting against time. Good armor and weapons will, of course, help you complete your quest. But more than anything else, solidarity of your party is what will count there. Will you accept Archangel's quest? (Basic character: Level 331-400, Advanced character: Level 311-400)",
    1750: "In Blood Castle, you'll be fighting against time. Good armor and weapons will, of course, help you complete your quest. But more than anything else, solidarity of your party is what will count there. Will you accept Archangel's quest? (Basic character: Level 81-130, Advanced character: Level 61-110)",
    1751: "In MU, it's possible to combine different items to create new ones. In fact, trying out different combinations of items adds a whole new dimension to MU.;Whom should you seek out in order to combine items?",
    1752: 'In the MU world, you can use the M button to travel with ease, provided that your level is high enough and you have enough money for the destination. Discovering areas that are right for your level and hunting there can also be very fun.',
    1857: 'Inland Supply Route!',
    1879: 'Iron Riders have been launching guerilla attacks against our forces stationed throughout Kanturu Ruins. Eliminate these Iron Riders and relieve the stress of our gens members.',
    1882: 'Is it time for me to return to the Dungeon?',
    1883: "Is the bond of your Blood Castle party still strong? If not, I suggest you return to Blood Castle to strengthen it. I have a quest that will earn you an item you'll need to enter Blood Castle. Will you accept this quest? (Basic character: Level 231-280, Advanced character: Level 211-260)",
    1884: 'Is there anything I need to be cautious of?',
    1885: 'Is there anything I should be aware of about Illusion Temple?',
    1886: 'Is there anything I should know about Devil Square?',
    1887: 'It all makes sense now.',
    1888: "It doesn't matter with the travelers, but you have to be careful when you kill a corrupt guardsman. Corrupt guardsmen will explode and may even push you off the arena. If this happens, you will be disqualified.",
    1889: 'It really is easy to enter. What does the event involve, exactly?',
    1890: "It seems Cursed Liches are tormenting the residents of Elveland with their dark spells and curses. Hunt down 40 of those Cursed Liches, and I'll give you a Devil's Invitation +1 as a reward. I suggest you work with others for faster results.",
    1891: 'It seems you have mighty warriors who are willing to fight at your side. Facing the challenges of Blood Castle together will certainly strengthen your bond with your comrades. Will you return to Blood Castle and carry out another quest of Archangel? (All characters: Master Level)',
    1892: 'It seems you have mighty warriors who are willing to fight at your side. Facing the challenges of Blood Castle together will certainly strengthen your bond with your comrades. Will you return to Blood Castle and carry out another quest of Archangel? (Basic character: Level 131-180, Advanced character: Level 111-160)',
}
