import json

translations = {
"3369": "Sayang sekali. Hadiah untuk quest ini cukup besar... Kalau kamu berubah pikiran, datanglah kembali sebelum mencapai level 320. (Quest telah dibatalkan.)",
"3370": "Sayang sekali. Hadiah untuk quest ini cukup besar... Kalau kamu berubah pikiran, datanglah kembali sebelum mencapai level 350. (Quest telah dibatalkan.)",
"3371": "Sayang sekali. Kamu tidak boleh melewatkan ini kalau ingin cepat naik level... Temui aku lagi sebelum mencapai level 15 kalau ingin menerima quest-nya. (Quest telah dibatalkan.)",
"3372": "Sayang sekali. Kamu tidak boleh melewatkan ini kalau ingin cepat naik level... (Quest telah dibatalkan.)",
"3373": "Sayang sekali. Kamu tidak boleh melewatkan ini kalau ingin cepat naik level.... (Quest telah dibatalkan.)",
"3374": "Sayang sekali. Kamu tidak boleh melewatkan ini kalau ingin cepat naik level.... Kembalilah sebelum mencapai level 230 kalau kamu berubah pikiran. (Quest telah dibatalkan.)",
"3375": "Sayang sekali. Kamu tidak boleh melewatkan ini kalau ingin cepat naik level.... Temui aku lagi sebelum mencapai level 235 kalau kamu memutuskan untuk menerima quest-nya. (Quest telah dibatalkan.)",
"3376": "Sayang sekali. Kamu tidak boleh melewatkan ini kalau ingin cepat naik level.... Temui aku lagi sebelum mencapai level 240 kalau kamu memutuskan untuk menerima quest-nya. (Quest telah dibatalkan.)",
"3377": "Sayang sekali. Kamu tidak boleh melewatkan ini kalau ingin cepat naik level.... Temui aku lagi sebelum mencapai level 250 kalau kamu memutuskan untuk menerima quest-nya. (Quest telah dibatalkan.)",
"3378": "Sayang sekali. Kamu tidak boleh melewatkan ini kalau ingin cepat naik level.... Temui aku lagi sebelum mencapai level 255 kalau kamu memutuskan untuk menerima quest-nya. (Quest telah dibatalkan.)",
"3379": "Sayang sekali. Kamu tidak boleh melewatkan ini kalau ingin cepat naik level.... Temui aku lagi sebelum mencapai level 26 kalau ingin menerima permintaan ini. (Quest telah dibatalkan.)",
"3380": "Sayang sekali. Kamu tidak boleh melewatkan ini kalau ingin cepat naik level.... Temui aku lagi sebelum mencapai level 260 kalau kamu memutuskan untuk menerima quest-nya. (Quest telah dibatalkan.)",
"3381": "Sayang sekali. Kamu tidak boleh melewatkan ini kalau ingin cepat naik level.... Temui aku lagi sebelum mencapai level 36 kalau ingin menerima permintaan ini. (Quest telah dibatalkan.)",
"3382": "Sayang sekali. Kamu tidak boleh melewatkan ini kalau ingin cepat naik level.... Temui aku lagi sebelum mencapai level 46 kalau ingin menerima permintaan ini. (Quest telah dibatalkan.)",
"3383": "Sayang sekali. Kamu tidak boleh melewatkan ini kalau ingin cepat naik level.... Temui aku lagi sebelum mencapai level 56 kalau ingin menerima quest-nya. (Quest telah dibatalkan.)",
"3384": "Sayang sekali. Kamu tidak boleh melewatkan ini kalau ingin cepat naik level.... Temui aku lagi sebelum mencapai level 66 kalau ingin menerima quest-nya. (Quest telah dibatalkan.)",
"3385": "Sayang sekali. Kamu tidak boleh melewatkan ini kalau ingin cepat naik level.... Temui aku lagi sebelum mencapai level 80 kalau ingin menerima quest-nya. (Quest telah dibatalkan.)",
"3386": "Sayang sekali. Kamu tidak boleh melewatkan ini kalau ingin cepat naik level... Temui aku lagi sebelum mencapai level 245 kalau kamu memutuskan untuk menerima quest-nya. (Quest telah dibatalkan.)",
"3387": "Pasukan ekspedisi Atlans melaporkan bahwa komandan utama Pasukan Jahat menggunakan Vepar untuk memburu anggota Gens yang sedang mencari batu segel. Kalahkan Vepar-Vepar ini dan lindungi anggota Gens.",
"3388": "Awal Permintaan",
"3390": "Jendela Character Stats akan memberitahumu nama dan level karaktermu, nama server saat ini, dan informasi status karakter.",
"3391": "Jendela Character Stats akan memberitahumu nama karaktermu, nama server saat ini, dan kelas karaktermu.",
"3392": "Jendela Character Stats akan memberitahumu nama karaktermu, nama server saat ini, dan kelas karaktermu. Kamu dapat terhubung ke channel yang berbeda dalam satu server yang sama menggunakan karakter yang sama.;Ada empat kelas karakter dasar: Elf, Dark Knight, Dark Wizard, dan Summoner. Capai level 220 dengan salah satu karakter dasar ini untuk membuka Magic Gladiator, dan level 250 untuk membuka Dark Lord.",
"3393": "Dungeon seharusnya tidak terlalu sulit.",
"3394": "Dungeon seharusnya tidak terlalu sulit. Lagipula, aku butuh peralatan baru. Haruskah aku mencobanya?",
"3395": "Skill Falling Slash sekarang seharusnya sudah menjadi salah satu skill yang bisa kamu gunakan. Coba klik ikon-nya.",
"3396": "Skill Fire Ball sekarang seharusnya sudah menjadi salah satu skill yang bisa kamu gunakan. Coba klik ikon-nya.",
"3397": "NPC Goblin di Noria.",
"3399": "Jendela Inventory akan menampilkan item yang kamu miliki dan peralatan yang kamu pakai.",
"3400": "Jendela Inventory akan menampilkan item yang kamu miliki dan peralatan yang kamu pakai.;Klik sebuah item untuk mengubah posisinya atau, jika itu item konsumsi, klik kanan untuk menggunakannya. Kamu paham?",
"3401": "Lost Tower terbukti cukup merepotkan. Aku menerima kabar tentang pergerakan monster di wilayah di mana anggota tim pengintai menghilang. Sepertinya para monster merencanakan sesuatu. Aku ingin kamu menghentikan pergerakan mereka. Maukah kamu menerima quest ini? (Level 194-197)",
"3403": "NPC Seed Master di Elveland.",
"3404": "Shadow Phantom Guardians punya quest untukmu, pendekar. Aku sarankan kamu menerimanya, kalau kamu menginginkan peralatan untuk perjalananmu ke depan. Temui Shadow Phantom Soldier sebelum kamu mencapai level 131.",
"3405": "Shadow Phantom Guardians punya quest untukmu, pendekar. Aku sarankan kamu menerimanya, kalau kamu menginginkan peralatan baru untuk perjalananmu ke depan. Temui Shadow Phantom Soldier sebelum kamu mencapai level 101.",
"3406": "Shadow Phantom Guardians punya quest untukmu, pendekar. Aku sarankan kamu menerimanya, kalau kamu menginginkan peralatan baru untuk perjalananmu ke depan. Temui Shadow Phantom Soldier sebelum kamu mencapai level 111.",
"3407": "Shadow Phantom Guardians punya quest untukmu, pendekar. Aku sarankan kamu menerimanya, kalau kamu menginginkan peralatan baru untuk perjalananmu ke depan. Temui Shadow Phantom Soldier sebelum kamu mencapai level 121.",
"3408": "Shadow Phantom Guardians punya quest untukmu, pendekar. Aku sarankan kamu menerimanya, kalau kamu menginginkan peralatan baru untuk perjalananmu ke depan. Temui Shadow Phantom Soldier sebelum kamu mencapai level 141.",
"3409": "Shadow Phantom Guardians punya quest untukmu, pendekar. Aku sarankan kamu menerimanya, kalau kamu menginginkan peralatan baru untuk perjalananmu ke depan. Temui Shadow Phantom Soldier sebelum kamu mencapai level 161.",
"3410": "Shadow Phantom Guardians punya quest untukmu, pendekar. Aku sarankan kamu menerimanya, kalau kamu menginginkan peralatan baru untuk perjalananmu ke depan. Temui Shadow Phantom Soldier sebelum kamu mencapai level 166.",
"3411": "Shadow Phantom Guardians punya quest untukmu, pendekar. Aku sarankan kamu menerimanya, kalau kamu menginginkan peralatan baru untuk perjalananmu ke depan. Temui Shadow Phantom Soldier sebelum kamu mencapai level 171.",
"3412": "Shadow Phantom Guardians punya quest untukmu, pendekar. Aku sarankan kamu menerimanya, kalau kamu menginginkan peralatan baru untuk perjalananmu ke depan. Temui Shadow Phantom Soldier sebelum kamu mencapai level 180.",
"3413": "Shadow Phantom Guardians punya quest untukmu, pendekar. Aku sarankan kamu menerimanya, kalau kamu menginginkan peralatan baru untuk perjalananmu ke depan. Temui Shadow Phantom Soldier sebelum kamu mencapai level 186.",
"3414": "Shadow Phantom Guardians punya quest untukmu, pendekar. Aku sarankan kamu menerimanya, kalau kamu menginginkan peralatan baru untuk perjalananmu ke depan. Temui Shadow Phantom Soldier sebelum kamu mencapai level 190.",
"3415": "Shadow Phantom Guardians punya quest untukmu, pendekar. Aku sarankan kamu menerimanya, kalau kamu menginginkan peralatan baru untuk perjalananmu ke depan. Temui Shadow Phantom Soldier sebelum kamu mencapai level 194.",
"3416": "Shadow Phantom Guardians punya quest untukmu, pendekar. Aku sarankan kamu menerimanya, kalau kamu menginginkan peralatan baru untuk perjalananmu ke depan. Temui Shadow Phantom Soldier sebelum kamu mencapai level 198.",
"3417": "Shadow Phantom Guardians punya quest untukmu, pendekar. Aku sarankan kamu menerimanya, kalau kamu menginginkan peralatan baru untuk perjalananmu ke depan. Temui Shadow Phantom Soldier sebelum kamu mencapai level 202.",
"3418": "Shadow Phantom Guardians punya quest untukmu, pendekar. Aku sarankan kamu menerimanya, kalau kamu menginginkan peralatan baru untuk perjalananmu ke depan. Temui Shadow Phantom Soldier sebelum kamu mencapai level 206.",
"3419": "Shadow Phantom Guardians punya quest untukmu, pendekar. Aku sarankan kamu menerimanya, kalau kamu menginginkan peralatan baru untuk perjalananmu ke depan. Temui Shadow Phantom Soldier sebelum kamu mencapai level 210.",
"3420": "Shadow Phantom Guardians punya quest untukmu, pendekar. Aku sarankan kamu menerimanya, kalau kamu menginginkan peralatan baru untuk perjalananmu ke depan. Temui Shadow Phantom Soldier sebelum kamu mencapai level 91.",
"3421": "Shadow Phantom Guardians telah berbuat banyak untukku....",
"3422": "Shadow Phantom Soldier sedang mencari seseorang yang bisa diandalkan untuk menjalankan quest Shadow Phantom Guardians. Temui Shadow Phantom Soldier lagi.",
"3423": "Shadow Phantom Soldier akan memberimu hadiah kecil kalau kamu berhasil tumbuh cepat di Devil Square. Terima ujian dari Shadow Phantom Soldier dan hadapi tantangan Devil Square.",
"3424": "Shadow Phantom Soldier akan memberimu hadiah kecil kalau kamu menang di Illusion Temple. Terima ujian dari Shadow Phantom Soldier dan hadapi tantangan Illusion Temple.",
"3425": "Shadow Phantom Soldier akan memberimu Armor of Guardsman, yang kamu butuhkan untuk masuk ke Chaos Castle. Terima armor-nya dan hadapi tantangan Chaos Castle.",
"3426": "Unit Shadow Phantom kesulitan mengendalikan jumlah Alquamos dan Drakan yang terus bertambah di Icarus, gerbang menuju Castle in Heaven. Pergilah ke Icarus dan bunuh 20 Alquamos serta 20 Drakan. Aku akan memberimu hadiah kalau kamu kembali dan melaporkannya padaku.",
"3427": "Unit Shadow Phantom kesulitan menghadapi Queen Rainier di Icarus, gerbang menuju Castle in Heaven. Pergilah ke Icarus dan bunuh 30 Queen Rainier. Aku akan memberimu hadiah kalau kamu kembali dan melaporkannya padaku.",
"3428": "Unit Shadow Phantom di Icarus, gerbang menuju Castle in Heaven, sedang dalam kesulitan karena Alquamos dan Alpha Crust menghalangi rute pasokan mereka. Pergilah ke Icarus dan bunuh 20 Alquamos serta 10 Alpha Crust. Aku akan memberimu hadiah kalau kamu kembali dan melaporkannya padaku.",
"3429": "Unit Shadow Phantom di Kanturu Ruins menderita karena serangan Iron Rider. Pergilah ke Kanturu Ruins dan bunuh 30 Mutant. Aku akan memberimu hadiah kalau kamu kembali dan melaporkannya padaku.",
"3430": "Unit Shadow Phantom melaporkan bahwa Watchers of Kundun kekurangan beberapa persediaan penting. Aku memberikan quest dengan hadiah melimpah bagi mereka yang membawakanku persediaan untuk para Watcher. Apakah kamu tertarik? (Level 260-289)",
"3431": "Unit Shadow Phantom melaporkan bahwa Watchers of Kundun kekurangan beberapa persediaan penting. Aku memberikan quest dengan hadiah melimpah bagi mereka yang membawakanku persediaan untuk para Watcher. Apakah kamu tertarik? (Level 320-349)",
"3432": "Skill Summon Goblin sekarang seharusnya sudah menjadi salah satu skill yang bisa kamu gunakan. Coba klik ikon-nya.",
"3433": "NPC Trainer di Lorencia.",
"3434": "Skill Triple Shot sekarang seharusnya sudah menjadi salah satu skill yang bisa kamu gunakan. Coba klik ikon-nya.",
"3435": "Jawabannya sudah jelas!",
"3436": "Penghalang di Lost Tower sekarang agak stabil dan aman. Namun, masih ada monster-monster peringkat tinggi yang ingin memanfaatkan setiap kesempatan yang ada. Maukah kamu melenyapkan monster-monster ini untuk kita? (Level 210-219)",
"3438": "Hambatan terbesar untuk masuk ke Devil Square, arena latihan untuk pertumbuhan cepat, mungkin adalah mendapatkan surat undangan. Aku punya quest sederhana yang akan memberimu surat undangan ke Devil Square. Maukah kamu menerima quest ini? (Karakter dasar: Level 330-400, Karakter lanjutan: Level 311-400)",
"3440": "Ikatan antara rekan seperjuanganku dan aku belum cukup kuat.",
"3441": "Ikatan persaudaraan.... Tentu saja rekan seperjuangan harus dipercaya dan dihargai.",
"3442": "Kapten memintaku berterima kasih atas kontribusimu dalam quest sebelumnya. Kapten juga mengatakan kamu telah membuktikan kemampuanmu dan siap untuk quest yang lebih krusial. Maukah kamu menerima quest ini? (Level 171-179)",
"3444": "Koordinat saat ini karakter ditampilkan di pojok kiri atas layar. Pergerakan ke arah �� atau �� mengubah angka pertama, dan pergerakan ke arah �� atau �� mengubah angka kedua.",
"3446": "Konflik antar Gens memperebutkan batu segel semakin memanas. Terdesak, pasukan Gens lawan menyerang pihak kita menggunakan Sapi-Duo. Kalahkan Sapi-Duo ini.",
"3447": "Energi gelap yang dipancarkan Gorgon telah melemah cukup banyak, dan monster-monster tampak sudah agak tenang karenanya. Ini saat yang tepat untuk memperketat serangan terhadap Gorgon. Maukah kamu menerima quest ini? (Level 131-140)",
"3452": "Sesepuh mengatakan Spider sedang memintal sarang di dinding luar kota dan meminta kita untuk memberantas mereka. Meskipun permintaan ini ditujukan kepada Shadow Phantom Guardians, aku yakin pekerjaan ini cocok bagi para pendekar yang baru memulai perjalanan. Maukah kamu menerima quest ini? (Level 1-14)",
"3453": "Munculnya monster yang tak henti-hentinya di Devil Square akan sangat membantumu berlatih. Luncurkan serangan gabungan bersama rekan party-mu untuk hasil yang lebih baik. Maukah kamu berlatih di Devil Square? (Karakter dasar: Level 15-130, Karakter lanjutan: Level 10-110)",
"3454": "Munculnya monster yang tak henti-hentinya di Devil Square akan sangat membantumu berlatih. Luncurkan serangan gabungan bersama rekan party-mu untuk hasil yang lebih baik. Maukah kamu mencoba menaklukkan Devil Square? (Semua karakter: Master Level)",
"3455": "Munculnya monster yang tak henti-hentinya di Devil Square akan sangat membantumu berlatih. Luncurkan serangan gabungan bersama rekan party-mu untuk hasil yang lebih baik. Maukah kamu mencoba menaklukkan Devil Square? (Karakter dasar: Level 330-400, Karakter lanjutan: Level 311-400)",
"3456": "Munculnya monster yang tak henti-hentinya di Devil Square akan sangat membantumu berlatih. Luncurkan serangan gabungan bersama rekan party-mu untuk hasil yang lebih baik. Maukah kamu mencoba menaklukkan Devil Square? (Karakter dasar: Level 131-180, Karakter lanjutan: Level 111-160)",
"3457": "Munculnya monster yang tak henti-hentinya di Devil Square akan sangat membantumu berlatih. Luncurkan serangan gabungan bersama rekan party-mu untuk hasil yang lebih baik. Maukah kamu mencoba menaklukkan Devil Square? (Karakter dasar: Level 231-280, Karakter lanjutan: Level 211-260)",
"3458": "Munculnya monster yang tak henti-hentinya di Devil Square akan sangat membantumu berlatih. Luncurkan serangan gabungan bersama rekan party-mu untuk hasil yang lebih baik. Maukah kamu mencoba menaklukkan Devil Square? (Karakter dasar: Level 281-330, Karakter lanjutan: Level 261-310)",
"3459": "Munculnya monster yang tak henti-hentinya di Devil Square akan membantu latihanmu. Luncurkan serangan gabungan bersama rekan party-mu untuk hasil yang lebih baik. Maukah kamu mencoba menaklukkan Devil Square? (Karakter dasar: Level 181-230, Karakter lanjutan: Level 161-210)",
"3466": "Rintangan terakhir, ya? Aku menerima misi ini. (Terima)",
"3467": "Gerbang menuju Blood Castle mungkin merupakan hambatan terbesar. Ikuti ujian Shadow Phantom Soldier lalu hadapi tantangan Blood Castle.",
"3468": "Master guild tidak bisa meninggalkan gens.",
"3469": "Master guild bukan anggota gens tersebut. Master guild harus menjadi anggota gens agar kamu bisa bergabung dengan gens itu.",
"3470": "Semakin tinggi level, semakin jauh jarak yang bisa kamu tempuh. Namun, dengan tombol M, kamu bisa berpindah ke area yang jauh dalam sekejap. Berapakah level minimum dan jumlah Zen yang kamu butuhkan untuk masuk ke Dungeon?",
"3474": "Jumlah Bloody Wolf di Tarkan yang semakin banyak mulai mengkhawatirkan. Burulah 50 Bloody Wolf, dan aku akan memberimu Scroll of Blood + 1 sebagai hadiah.",
"3475": "Jumlah Iron Wheel di Tarkan yang semakin banyak mulai mengkhawatirkan. Burulah 70 Iron Wheel, dan aku akan memberimu Scroll of Blood + 2 sebagai hadiah.",
"3479": "Yang terakhir harus dihadapi adalah Bloody Soldier dan Death Angel yang merapal mantra pada batu segel. Bunuh 30 Bloody Soldier dan 20 Death Angel lalu kembalilah padaku untuk mengambil hadiah. (Bisa Party)",
"3480": "Kerugian yang disebabkan oleh intrik Queen Rainier terus menumpuk. Maukah kamu membantu melenyapkan lebih banyak Queen Rainier ini? (Level 255-259)",
"3481": "Kantor guild tentara bayaran baru saja didirikan di Devias. Temui manajer kantor guild Tercia.",
"3483": "Monster-monster itu bertingkah aneh. Sepertinya Iron Wheel yang peringkatnya lebih tinggi dari Bloody Wolf sedang merencanakan sesuatu. Aku ingin meminta bantuanmu untuk melenyapkan Iron Wheel ini. Maukah kamu menerimanya? (Level 240-244)",
"3485": "Jumlah Alquamos belum berkurang, dan tim pengintai kita terus menderita kerugian. Maukah kamu membantu melenyapkan lebih banyak Alquamos ini? (Level 245-249)",
"3486": "Jumlah Death Beam Knight di Tarkan 2 meningkat tak terkendali. Burulah 30 Death Beam Knight, dan aku akan memberimu Scroll of Blood + 4 sebagai hadiah.",
"3487": "Jumlah Drakan di Icarus meningkat tak terkendali. Burulah 90 Drakan, dan aku akan memberimu Scroll of Blood + 3 sebagai hadiah.",
"3488": "Jumlah Giant Drakan di Icarus meningkat tak terkendali. Burulah 130 Giant Drakan, dan aku akan memberimu Scroll of Blood + 5 sebagai hadiah.",
"3489": "Jumlah Mega Crust belum berkurang, dan tim pengintai kita terus menderita kerugian. Maukah kamu membantu melenyapkan lebih banyak Mega Crust ini? (Level 250-254)",
"3490": "Jumlah Shadow Look di Swamp of Peace meningkat tak terkendali. Burulah 150 Shadow Look, dan aku akan memberimu Scroll of Blood + 6 sebagai hadiah.",
"3491": "Tujuan saat ini adalah menyelesaikan quest Archangel di Blood Castle. Ikuti ujian Shadow Phantom Soldier lalu hadapi tantangan Blood Castle.",
"3492": "Tujuannya seharusnya adalah mempertahankan tempat ini, kalau begitu.",
"3493": "Bola yang kuberikan akan mengajarkanmu skill Summon Goblin. Klik kanan pada item tersebut untuk mempelajari skill-nya. Silakan pelajari skill-nya.",
"3494": "Perintah ratu adalah membantu para pendekar yang memulai perjalanan mereka agar setidaknya bisa membela diri dari pasukan Kundun.",
"3495": "Quest untuk melenyapkan Totem Golem dan Cursed Lich di Elveland sebenarnya ditetapkan oleh sesepuh Elveland. Beliau mengatakan sekarang jumlah monster yang muncul lebih banyak dan meminta kita untuk memberantas mereka. Maukah kamu menerima quest ini? (Level 80-90)",
"3503": "Tim pengintai telah mengirimkan permintaan kepada kita. Mereka mengatakan dengan melenyapkan monster peringkat lebih tinggi yang mengendalikan yang peringkat rendah, pekerjaan mereka akan jauh lebih mudah. Kalahkan monster-monster ini. Maukah kamu menerima quest ini? (Level 166-170)",
"3504": "Tim pengintai telah berhasil memasuki Tarkan, tetapi sekarang terpaksa berhadapan dengan Bloody Wolf. Mereka peringkat lebih tinggi dari monster biasa. Aku ingin meminta bantuanmu untuk melenyapkan Bloody Wolf ini. Maukah kamu menerimanya? (Level 235-239)",
"3505": "Tim pengintai sedang maju, tetapi Mutant mulai berkumpul dalam jumlah lebih banyak. Maukah kamu membantu melenyapkan lebih banyak Mutant? (Level 230-234)",
"3506": "Tim pengintai sedang kesulitan menghadapi serangan mendadak terhadap mereka. Aku ingin meminta bantuanmu untuk melenyapkan monster-monster ini. Maukah kamu menerima quest ini? (Level 180-189)",
"3507": "Tim pengintai melaporkan bahwa persediaan curian dikirimkan ke Lost Tower melalui Devias. Memutus rute pasokan Kundun di Devias akan menjadi pukulan telak bagi musuh. Maukah kamu menerima quest ini? (Level 36-45)",
"3508": "Tim pengintai melaporkan situasi telah banyak membaik. Aku berterima kasih atas nama kapten kita. Namun, masih ada monster yang mengganggu upaya pengintaian kita. Sepertinya monster-monster ini peringkatnya agak lebih tinggi dari sebelumnya dan terbukti sulit dihadapi. Aku ingin meminta bantuanmu untuk melenyapkan monster-monster ini. Maukah kamu menerima quest ini? (Level 171-179)",
"3509": "Hadiahnya sudah dibagikan.",
"3510": "Gulungan yang kuberikan akan mengajarkanmu skill Fire Ball. Klik kanan pada item tersebut untuk mempelajari skill-nya. Silakan pelajari skill-nya.",
"3513": "Tesnya cukup sederhana, dan tidak apa-apa kalau kamu tidak menjawab semuanya dengan benar. Namun, kalau kamu berhasil, ada hadiah bonus kecil.;Kamu yakin tidak ingin mengikuti tesnya?",
"3514": "Shadow Phantom Soldier di kota ini sedang mencari seseorang yang bisa diandalkan untuk menjalankan quest baik besar maupun kecil. Temui Shadow Phantom Soldier lagi.",
"3517": "Senjata yang kuberikan adalah Double Axe. Untuk memakainya, masukkan item Double Axe ke slot peralatan di Inventory-mu. Silakan pasang senjatanya.",
"3518": "Senjata yang kuberikan adalah crossbow. Untuk memakainya, masukkan item crossbow ke slot peralatan di Inventory-mu. Silakan pasang senjatanya.",
"3521": "Kalau begitu aku akan memberimu misi kedua saat ini juga. Raihlah kemenangan di Illusion Temple. Selesaikan misinya dan kamu akan dihadiahi 5.000.000 Exp. Tolong bawa MU menuju masa kejayaan yang besar.",
"3522": "Kalau begitu aku akan memberimu misi kedua saat ini juga. Aku tahu kemenangan di Illusion Temple sulit diraih. Teruslah bertahan dan berusaha, dan kemenangan akan menjadi milikmu. Selesaikan misinya dan kamu akan dihadiahi 8.000.000 Exp.",
"3523": "Kalau begitu aku akan memberimu misi kedua saat ini juga. Lindungi barang suci dan jangan menyerah sebelum kamu menang di Illusion Temple. Selesaikan misinya dan kamu akan dihadiahi 8.000.000 Exp.",
"3524": "Kalau begitu aku akan memberimu misi kedua saat ini juga. Kejutkan rival-rivelmu dengan meraih kemenangan di Illusion Temple. Selesaikan misinya dan kamu akan dihadiahi 5.000.000 Exp.",
"3525": "Kalau begitu aku akan memberimu misi kedua saat ini juga. Jangan takut menghadapi banyak musuh sekaligus, dan raihlah kemenangan di Illusion Temple. Selesaikan misinya dan kamu akan dihadiahi 3.000.000 Exp.",
"3526": "Kalau begitu kamu harus menaklukkan Illusion Temple. Temui Phantom Soldier untuk memulai quest Illusion Temple.",
"3527": "Kalau begitu kamu harus menaklukkan Illusion Temple. Temui Phantom Soldier untuk menjalankan quest Illusion Temple.",
"3528": "Ada banyak cara untuk membuktikan kemampuanmu di benua MU. Kamu bisa menjadi yang terakhir bertahan di Chaos Castle, atau bekerja sama dengan rekan seperjuangan untuk bertempur melintasi Blood Castle, Devil Square, atau Illusion Temple. Para pendekar menganggap prestasi seperti itu sebagai salah satu pencapaian paling berharga yang bisa diraih.",
"3530": "Ada banyak jenis monster yang bersembunyi di Dungeon. Dan yang ada di Level 2 menjadi sangat merepotkan. Aku ingin memintamu untuk memberantas mereka. Maukah kamu menerima quest ini? (Level 101-110)",
"3531": "Terlalu banyak monster yang menjaga jalan antara Dungeon Level 2 dan Level 3, menghalangi tim pengintai kita mencapai level ketiga. Aku ingin memintamu untuk melenyapkan monster-monster ini. Maukah kamu menerima quest ini? (Level 121-130)",
"3532": "Ada tempat bernama Icarus, yang bisa diakses melalui level tertinggi Lost Tower. Kamu bisa mencapai level tersebut jika memiliki kemampuan terbang. Namun, sekelompok monster telah muncul dan sekarang menghalangi masuk ke Icarus. Maukah kamu melenyapkan monster-monster ini untuk kita? (Level 220-229)",
"3533": "Tidak ada quest yang tersedia. Silakan kembali lagi nanti.",
"3534": "Sekarang ada sekelompok monster yang terus-menerus menyerang penghalang kita yang menampung energi Lost Tower. Devil dan Cursed Wizard tampaknya memberikan kerusakan paling besar pada penghalang tersebut. Maukah kamu melenyapkan monster-monster ini untuk kita? (Level 191-199)",
"3535": "Ada rumor tentang Dark Knight dan Gorgon dari level terendah Dungeon yang merencanakan sesuatu yang jahat. Pergilah ke Dungeon Level 3 dan kalahkan 80 Dark Knight. Lakukan ini, dan aku akan memberimu pilihan dua hadiah dari 30 Large Healing Potion, 30 Large Mana Potion, dan 15 Small Complex Potion. Saat mengambil hadiah, pastikan kamu memiliki setidaknya 20 slot kosong di Inventory-mu. Ingat itu.",
"3536": "Katanya Death Cow, yang didorong oleh energi jahat, sedang melakukan sesuatu yang mencurigakan di Lost Tower. Burulah 60 Death Cow, dan aku akan memberimu Devil's Invitation + 2 sebagai hadiah. Akan lebih bijaksana jika mengerjakan quest ini bersama orang lain yang bisa kamu percayai.",
"3537": "Katanya jumlah Alquamos di Icarus semakin bertambah dan menyebabkan cukup banyak masalah bagi para pendekar. Pergilah ke Icarus dan burulah 80 Alquamos. Temui aku setelah selesai untuk menerima Devil's Invitation + 3 sebagai hadiah. Mereka adalah musuh yang kuat, dan kamu sebaiknya berburu dengan bantuan orang lain.",
"3538": "Keadaannya menjadi serius....",
"3540": "Pintu ini tidak akan selalu terbuka untukmu.",
"3541": "Ini adalah pengetahuan umum.",
"3542": "Ini adalah akhir dari tutorial. Silakan nikmati pengalaman MU-mu.",
"3543": "Yang ini mungkin agak menantang, ya? Aku menerima misi ini. (Terima)",
"3544": "Quest ini seharusnya tidak menjadi masalah.",
"3545": "Kali ini, tujuannya adalah bertahan hidup di Chaos Castle. Temui Shadow Phantom Soldier, ikuti ujian ekstremnya, lalu hadapi tantangan Chaos Castle.",
"3548": "Mereka yang ingin mengabdi pada sebuah gens harus mencari steward klan yang bersangkutan.",
"3565": "Untuk mengetahui kapan kamu bisa masuk, tekan tombol F1. Lalu, bawa Devil's Invitation yang sesuai dengan levelmu kepada Charon di Noria lima menit sebelum waktu masuk yang kamu pilih. Kamu akan dikirim ke Devil Square. Temui aku kalau kamu punya waktu, dan aku akan memberimu quest yang akan memberimu item yang dibutuhkan untuk masuk ke Devil Square.",
"3566": "Untuk mengetahui kapan kamu bisa masuk, tekan tombol F1. Lalu, bawa Scroll of Blood yang sesuai dengan levelmu kepada Mirage di Elveland lima menit sebelum waktu masuk yang kamu pilih. Kamu kemudian akan dikirim ke Illusion Temple. Temui aku kalau kamu punya waktu, dan aku akan memberimu quest yang akan memberimu item yang dibutuhkan untuk masuk ke Illusion Temple.",
"3567": "Untuk mengetahui kapan kamu bisa masuk, cukup tekan tombol F1. Kalau ingin masuk, bawa Invisibility Cloak yang sesuai dengan levelmu kepada Messenger of Archangel sebelum waktu mulai yang dijadwalkan. Temui aku kalau kamu punya waktu, dan aku akan memberimu quest yang akan memberimu Invisibility Cloak agar kamu bisa masuk ke Blood Castle.",
"3569": "Untuk tumbuh cepat dan menjadi pendekar yang kuat, kamu harus menyelesaikan berbagai event map. Temui Phantom Soldier jika ingin menjalankan quest event map.",
"3571": "Untuk memulihkan keseimbangan dalam event pertempuran, Secrarium mengajukan penawaran kepada Lugard dan mengusulkan penerapan aturan baru. Aturan ini mewajibkan semua orang yang berpartisipasi dalam event tersebut mengenakan armor penjaga. Lugard, yang menganggap tawaran itu adil, menerimanya.",
"3576": "Sebagai permulaan, aku akan memberimu misi sederhana untuk melihat apakah kamu memiliki kualitas yang tepat untuk menjadi pahlawan. Maukah kamu menerima misi ini? (Karakter dasar: Level 240 - 270, Karakter lanjutan: Level 220 - 260)",
"3581": "Permintaan hari ini sudah ditutup. Kembalilah pada jam yang sama besok dan aku akan memberimu permintaan baru. Terima kasih.",
"3583": "Terlalu mudah! Untuk memperbaiki peralatan tanpa bantuan NPC, aku harus berada di...",
"3588": "Town Portal Scroll dapat dibeli dari pedagang ramuan di kota-kota. Ini adalah item sekali pakai yang akan membawamu kembali ke kota terakhir yang kamu kunjungi.;Karena kita sedang membahasnya, maukah kamu pergi membeli Town Portal Scroll dari pedagang? Akan lebih mudah dipahami kalau kamu mencobanya sendiri.",
"3597": "Pendekar, kamu sekarang sudah cukup kuat untuk memberikan perbedaan di medan perang Kundun. Tim pengintai Shadow Phantom Guardians telah mengajukan permintaan sederhana. Mereka punya quest sederhana tentang pemusnahan monster dan senjata ampuh akan diberikan sebagai hadiah. Maukah kamu menerima quest ini? (Level 161-165)",
"3604": "Coba pasang Double Axe-nya.",
"3605": "Coba pasang crossbow-nya.",
"3606": "Coba pelajari skill Summon Goblin.",
"3607": "Cobalah Blood Castle Level 1 dan selesaikan quest Archangel. Kembalilah setelahnya, dan aku akan memberimu 100.000 poin EXP dan 200.000 Zen sebagai hadiah. Namun, ini hanya berlaku untuk Blood Castle Level 1.",
"3608": "Cobalah Blood Castle Level 1. Hancurkan gerbang kastil dan kembalilah menemui Shadow Phantom Soldier untuk mengklaim hadiahmu. Namun, ini hanya berlaku untuk Blood Castle Level 1.",
"3609": "Cobalah Blood Castle Level 2 dan selesaikan quest Archangel. Kembalilah setelahnya, dan aku akan memberimu 400.000 poin EXP dan 300.000 Zen sebagai hadiah. Namun, ini hanya berlaku untuk Blood Castle Level 2.",
"3610": "Cobalah Blood Castle Level 2. Hancurkan gerbang kastil dan kembalilah menemui Shadow Phantom Soldier untuk mengklaim hadiahmu. Namun, ini hanya berlaku untuk Blood Castle Level 2.",
"3611": "Cobalah Blood Castle Level 3 dan selesaikan quest Archangel. Kembalilah setelahnya, dan aku akan memberimu 1.000.000 poin EXP dan 1 Jewel of Chaos sebagai hadiah. Namun, ini hanya berlaku untuk Blood Castle Level 3.",
"3612": "Cobalah Blood Castle Level 3. Hancurkan gerbang kastil dan kembalilah menemui Shadow Phantom Soldier untuk mengklaim hadiahmu. Namun, ini hanya berlaku untuk Blood Castle Level 3.",
"3613": "Cobalah Blood Castle Level 4 dan selesaikan quest Archangel. Aku akan memberimu 1 Jewel of Soul sebagai hadiah saat kamu kembali. Namun, ini hanya berlaku untuk Blood Castle Level 4.",
"3614": "Cobalah Blood Castle Level 4. Hancurkan gerbang kastil dan kembalilah menemui Shadow Phantom Soldier untuk mengklaim hadiahmu. Namun, ini hanya berlaku untuk Blood Castle Level 4.",
"3615": "Cobalah Blood Castle Level 5 dan selesaikan quest Archangel. Aku akan memberimu 1 Jewel of Bless sebagai hadiah saat kamu kembali. Namun, ini hanya berlaku untuk Blood Castle Level 5.",
"3616": "Cobalah Blood Castle Level 5. Hancurkan gerbang kastil dan kembalilah menemui Shadow Phantom Soldier untuk mengklaim hadiahmu. Namun, ini hanya berlaku untuk Blood Castle Level 5.",
"3617": "Cobalah Blood Castle Level 6 dan selesaikan quest Archangel. Aku akan memberimu 1 Jewel of Life sebagai hadiah saat kamu kembali. Namun, ini hanya berlaku untuk Blood Castle Level 6.",
"3618": "Cobalah Blood Castle Level 6. Hancurkan gerbang kastil dan kembalilah menemui Shadow Phantom Soldier untuk mengklaim hadiahmu. Namun, ini hanya berlaku untuk Blood Castle Level 6.",
"3619": "Cobalah Blood Castle Level 7 dan selesaikan quest Archangel. Aku akan memberimu 2 Jewel of Bless sebagai hadiah saat kamu kembali. Namun, ini hanya berlaku untuk Blood Castle Level 7.",
"3620": "Cobalah Blood Castle Level 7. Hancurkan gerbang kastil dan kembalilah menemui Shadow Phantom Soldier untuk mengklaim hadiahmu. Namun, ini hanya berlaku untuk Blood Castle Level 7.",
"3621": "Cobalah Blood Castle Level 8 dan selesaikan quest Archangel. Aku akan memberimu 2 Jewel of Life sebagai hadiah saat kamu kembali. Namun, ini hanya berlaku untuk Blood Castle Level 8.",
"3622": "Cobalah Blood Castle Level 8. Hancurkan gerbang kastil dan kembalilah menemui Shadow Phantom Soldier untuk mengklaim hadiahmu. Namun, ini hanya berlaku untuk Blood Castle Level 8.",
"3623": "Cobalah Chaos Castle Level 1. Kembalilah padaku setelah mengalahkan 1 Guardsman, dan aku akan memberimu 100.000 Zen sebagai hadiah. Namun, ini hanya berlaku untuk Chaos Castle Level 1.",
"3624": "Cobalah Chaos Castle Level 1. Kalahkan 1 Guardsman dan kembalilah menemui Shadow Phantom Soldier untuk mengklaim hadiahmu. Namun, ini hanya berlaku untuk Chaos Castle Level 1.",
"3625": "Cobalah Chaos Castle Level 2. Kembalilah padaku setelah mengalahkan 3 Guardsman, dan aku akan memberimu 200.000 Zen sebagai hadiah. Namun, ini hanya berlaku untuk Chaos Castle Level 2."
}

with open('out_data/id/_batch3_partial.json', 'w', encoding='utf-8') as f:
    json.dump(translations, f, ensure_ascii=False, indent=1)

print(f"Saved {len(translations)} translations")
