get_filename_component(REPO_ROOT "${CMAKE_CURRENT_LIST_DIR}/../.." ABSOLUTE)

function(require_block source marker needle)
    string(FIND "${source}" "${marker}" start)
    if(start LESS 0)
        message(FATAL_ERROR "Missing input bridge: ${marker}")
    endif()
    string(SUBSTRING "${source}" ${start} 4400 block)
    string(FIND "${block}" "${needle}" found)
    if(found LESS 0)
        message(FATAL_ERROR "${marker} must contain ${needle}")
    endif()
endfunction()

file(READ "${REPO_ROOT}/src/source/App/Platform/Windows/Winmain.cpp" main)
require_block("${main}" "void HandleMouseButton(" "g_MessageBox->RecordPointerButton")
require_block("${main}" "void HandleMobileMouseAction(" "HandleMouseButton(mouse)")
foreach(marker "void CancelVirtualMouseButton(" "void CancelMobileMouseButton(" "void HandleFocusChange(")
    require_block("${main}" "${marker}" "g_MessageBox->CancelPointerInput()")
endforeach()

file(READ "${REPO_ROOT}/src/source/UI/NewUI/Dialogs/NewUIMessageBox.h" manager)
require_block("${manager}" "T* NewMessageBox(const CNewUIMessageBoxFactory" "SynchronizePointerOwner()")
message(STATUS "Message-box edge bridge contract passed; runtime UI acceptance remains separate")
