cmake_minimum_required(VERSION 3.24)
get_filename_component(REPO_ROOT "${CMAKE_CURRENT_LIST_DIR}/../.." ABSOLUTE)

function(assert_contains text needle context)
    string(FIND "${text}" "${needle}" position)
    if(position LESS 0)
        message(FATAL_ERROR "${context}: missing ${needle}")
    endif()
endfunction()

file(READ "${REPO_ROOT}/src/source/App/Platform/Windows/Winmain.cpp" main)
assert_contains("${main}" "SDL_SetHintWithPriority(SDL_HINT_TOUCH_MOUSE_EVENTS, \"0\", SDL_HINT_OVERRIDE)" "Raw SDL mouse polling must not bypass item contact ownership")
foreach(needle "event.motion.which == SDL_TOUCH_MOUSEID" "event.button.which == SDL_TOUCH_MOUSEID"
    "BeginItemContact(logicalContact)" "CaptureNextContact()" "HandleItemContact(logicalContact)"
    "TickItemContact(static_cast<std::uint64_t>(SDL_GetTicks()))" "CancelItemContact()" "FinishItemContactSequence()")
    assert_contains("${main}" "${needle}" "Mobile input integration")
endforeach()

file(READ "${REPO_ROOT}/src/source/UI/Items/Touch/InventoryTouchOperations.cpp" operations)
assert_contains("${operations}" "TryConsumeItem(control, control->FindItem(index), index)" "Consume/learn-only touch use")
if(operations MATCHES "HandleRightClick|HandleItemDrop|SellItem|TryEquip")
    message(FATAL_ERROR "Dedicated touch use must not contain an equip/sell/drop/right-click fallback")
endif()

file(READ "${REPO_ROOT}/src/source/UI/NewUI/Inventory/NewUIInventoryCtrl.cpp" control)
assert_contains("${control}" "if (g_pNewUI3DRenderMng) g_pNewUI3DRenderMng->Remove3DRenderObj(this)" "Failed pick must not dereference an absent renderer")
assert_contains("${control}" "if (m_pNewItemMng) m_pNewItemMng->DeleteDuplicatedItem(m_pPickedItem)" "Failed pick must not dereference an absent item manager")
foreach(method "Release()" "HideInventory()" "LockInventory()" "SetRepairMode(bool bRepair)")
    string(FIND "${control}" "CNewUIInventoryCtrl::${method}" start)
    if(start LESS 0)
        message(FATAL_ERROR "Missing lifecycle method ${method}")
    endif()
    string(SUBSTRING "${control}" ${start} 220 block)
    assert_contains("${block}" "CancelItemContactForOwner(this)" "Touch cancellation before ${method}")
endforeach()

file(READ "${REPO_ROOT}/src/source/UI/Items/Touch/InventoryTouchAdapter.cpp" adapter)
assert_contains("${adapter}" "!g_pNewItemMng || !g_pNewUI3DRenderMng || EquipmentItem" "Do not capture while inventory services or a request are unavailable")
assert_contains("${adapter}" "UI::Input::BlocksWorldInput(key, layerState)" "Persistent HUD managers must not disable inventory contacts")
file(READ "${REPO_ROOT}/src/source/UI/NewUI/NewUISystem.cpp" interfaces)
assert_contains("${interfaces}" "UI::Input::BlocksWorldInput(key, layerState)" "World and inventory input must use the same state-aware layer policy")

file(READ "${REPO_ROOT}/src/source/UI/NewUI/HUD/NewUIMainFrameWindow.cpp" hotkeys)
foreach(needle "return !UseSlot(slot)" "return m_ItemHotKey.UseSlot(slot)"
    "bool SEASON3B::CNewUIItemHotKey::UseSlot(int slot)" "GetSlotIdentity(slot, iIndex, key)")
    assert_contains("${hotkeys}" "${needle}" "QWER and touch must share validated quick-slot use")
endforeach()

file(READ "${REPO_ROOT}/src/source/Character/CharSelMainWin.cpp" character)
assert_contains("${character}" "CWin::Create(artWinW, btnArtH, -2)" "Character bar must use art units exactly once")
foreach(button CREATE MENU CONNECT DELETE)
    assert_contains("${character}" "m_aBtn[CSMW_BTN_${button}].Create(kButtonSourceWidth, kButtonSourceHeight" "Preserve full texture and original frame stride")
endforeach()
assert_contains("${character}" "m_aBtn[i].SetSizeArt(btnArtW, btnArtH)" "Resize the button quad instead of cropping its texture")
string(FIND "${character}" "CWin::Create(artWinW, btnArtH, -2)" parent_create)
string(FIND "${character}" "m_asprBack[CSMW_SPR_DECO].Create(" child_create)
if(NOT parent_create LESS child_create)
    message(FATAL_ERROR "CWin recreation must release old children before their new resources are created")
endif()
assert_contains("${character}" "m_aBtn[CSMW_BTN_CONNECT].IsClick()" "Explicit touch enter button")
assert_contains("${character}" "::StartGame()" "Enter starts the real character scene")
message(STATUS "Mobile item integration contracts passed; full UI/rendering/server behavior still requires emulator QA")
