#pragma once

// Split chunk of legacy Core/Globals/_enum.h (P2).
// Enum names/values/order are unchanged.
#include "Core/Platform/WinCompat.h"  // BYTE and fixed underlying types

enum CLASS_TYPE : BYTE
{
    CLASS_UNDEFINED = 0xFF,
    CLASS_START = 0,

    CLASS_WIZARD = 0,
    CLASS_KNIGHT,
    CLASS_ELF,
    CLASS_DARK,
    CLASS_DARK_LORD,
    CLASS_SUMMONER,
    CLASS_RAGEFIGHTER,

    CLASS_SOULMASTER,
    CLASS_BLADEKNIGHT,
    CLASS_MUSEELF,
    CLASS_BLOODYSUMMONER,

    CLASS_GRANDMASTER,
    CLASS_BLADEMASTER,
    CLASS_HIGHELF,
    CLASS_DUELMASTER,
    CLASS_LORDEMPEROR,
    CLASS_DIMENSIONMASTER,
    CLASS_TEMPLENIGHT,

    CLASS_END = CLASS_TEMPLENIGHT
};

enum CLASS_SKIN_INDEX : BYTE
{
    SKIN_CLASS_WIZARD = 0,
    SKIN_CLASS_KNIGHT,
    SKIN_CLASS_ELF,
    SKIN_CLASS_DARK,
    SKIN_CLASS_DARK_LORD,
    SKIN_CLASS_SUMMONER,
    SKIN_CLASS_RAGEFIGHTER,
    SKIN_CLASS_SOULMASTER,
    SKIN_CLASS_BLADEKNIGHT,
    SKIN_CLASS_MUSEELF,
    SKIN_CLASS_BLOODYSUMMONER = 12,
    SKIN_CLASS_GRANDMASTER = 14,
    SKIN_CLASS_BLADEMASTER,
    SKIN_CLASS_HIGHELF,
    SKIN_CLASS_DUELMASTER, 
    SKIN_CLASS_LORDEMPEROR,
    SKIN_CLASS_DIMENSIONMASTER,
    SKIN_CLASS_TEMPLENIGHT,
};

enum SERVER_CLASS_TYPE : BYTE
{
    DarkWizard = 0,
    SoulMaster = 2,
    GrandMaster = 3,
    DarkKnight = 4,
    BladeKnight = 6,
    BladeMaster = 7,
    FairyElf = 8,
    MuseElf = 10,
    HighElf = 11,
    MagicGladiator = 12,
    DuelMaster = 13,
    DarkLord = 16,
    LordEmperor = 17,
    Summoner = 20,
    BloodySummoner = 22,
    DimensionMaster = 23,
    RageFighter = 24,
    FistMaster = 25,
};

enum MonsterSkillType
{
    ATMON_SKILL_BIGIN = 0,
    ATMON_SKILL_THUNDER = 1,
    ATMON_SKILL_WIND = 2,
    ATMON_SKILL_FIRELAY = 3,
    ATMON_SKILL_CHARM = 4,
    ATMON_SKILL_TOUCH = 5,
    ATMON_SKILL_NUM1 = 6,
    ATMON_SKILL_NUM2 = 7,
    ATMON_SKILL_NUM3 = 8,
    ATMON_SKILL_NUM4 = 9,
    ATMON_SKILL_NUM5 = 10,
    ATMON_SKILL_NUM6 = 11,
    ATMON_SKILL_NUM7 = 12,
    ATMON_SKILL_NUM8 = 13,
    ATMON_SKILL_NUM9 = 14,
    ATMON_SKILL_NUM10 = 15,
    ATMON_SKILL_NUM11 = 16,
    ATMON_SKILL_NUM12 = 17,
    ATMON_SKILL_NORMAL = 18,
    ATMON_SKILL_STORM = 19,
    ATMON_SKILL_SUMMON = 20,
    ATMON_SKILL_HELL = 21,
    ATMON_SKILL_TELEPORT = 22,
    ATMON_SKILL_SHOCK = 23,
    ATMON_SKILL_CRYSTAL = 24,
    ATMON_SKILL_MAYASTORM = 25,
    ATMON_SKILL_MAYACRYSTAL = 26,
    ATMON_SKILL_COURSED_STUN = 27,
    ATMON_SKILL_COURSED_POISON = 28,
    ATMON_SKILL_SERUFAN_POISONGEM = 34,
    ATMON_SKILL_SERUFAN_COOLSTORM = 35,
    ATMON_SKILL_SERUFAN_COOLSHOCK = 36,
    ATMON_SKILL_SERUFAN_FALLING = 37,
    ATMON_SKILL_SERUFAN_SUMMON = 38,
    ATMON_SKILL_SERUFAN_HEAL = 39,
    ATMON_SKILL_SERUFAN_FREEZE = 40,
    ATMON_SKILL_SERUFAN_TELEPORT = 41,
    ATMON_SKILL_SERUFAN_SUPERMAN = 42,
    ATMON_SKILL_EMPIREGUARDIAN_BERSERKER = 59,
    ATMON_SKILL_EMPIREGUARDIAN_GAION_02_BLOODATTACK = 64,
    ATMON_SKILL_EMPIREGUARDIAN_GAION_03_GIGANTIKSTORM = 65,
    ATMON_SKILL_EMPIREGUARDIAN_GAION_04_FLAMEATTACK = 66,
    ATMON_SKILL_EMPIREGUARDIAN_GAION_01_GENERALATTACK = 67,
    ATMON_SKILL_EX_BLOODYGOLUEM_ATTACKSKILL = 68,
    ATMON_SKILL_EX_BLOODYWITCHQUEEN_ATTACKSKILL = 69,
    ATMON_SKILL_EX_BERSERKERWARRIOR_ATTACKSKILL = 70,
    ATMON_SKILL_EX_KENTAURUSWARRIOR_ATTACKSKILL = 14,
    ATMON_SKILL_EX_GENOSIDEWARRIOR_ATTACKSKILL = 71,
    ATMON_SKILL_EX_SAPIQUEEN_ATTACKSKILL = 72,
    ATMON_SKILL_EX_ICENAPIN_ATTACKSKILL = 73,
    ATMON_SKILL_EX_SHADOWMASTER_ATTACKSKILL = 74,
    ATMON_SKILL_EX_DARKMEMUD_ATTACKSKILL = 75,
    ATMON_SKILL_EX_DARKGIANT_ATTACKSKILL = 76,
    ATMON_SKILL_EX_DARKAIONNIGHT_ATTACKSKILL = 32,
    ATMON_SKILL_EX_DARKCOOLERTIN_ATTACKSKILL = 77,
    ATMON_SKILL_END,
};

enum    PetCommandType
{
    AT_PET_COMMAND_DEFAULT = 120,
    AT_PET_COMMAND_RANDOM,
    AT_PET_COMMAND_OWNER,
    AT_PET_COMMAND_TARGET,
    AT_PET_COMMAND_END,
};

enum    OptionType
{
    AT_ATTACK1 = 120,
    AT_ATTACK2,

    AT_STAND1,
    AT_STAND2,
    AT_MOVE1,
    AT_MOVE2,

    AT_DAMAGE1,
    AT_DIE1,
    AT_SIT1,
    AT_POSE1,
    AT_HEALING1,
    AT_GREETING1,
    AT_GOODBYE1,
    AT_CLAP1,
    AT_GESTURE1,
    AT_DIRECTION1,
    AT_UNKNOWN1,
    AT_CRY1,
    AT_CHEER1,
    AT_AWKWARD1,
    AT_SEE1,
    AT_WIN1,
    AT_SMILE1,
    AT_SLEEP1,
    AT_COLD1,
    AT_AGAIN1,
    AT_RESPECT1,
    AT_SALUTE1,
    AT_RUSH1,
    AT_SCISSORS,
    AT_ROCK,
    AT_PAPER,
    AT_HUSTLE,
    AT_PROVOCATION,
    AT_LOOK_AROUND,
    AT_CHEERS,
    AT_JACK1,
    AT_JACK2,
    AT_SANTA1_1,
    AT_SANTA1_2,
    AT_SANTA1_3,
    AT_SANTA2_1,
    AT_SANTA2_2,
    AT_SANTA2_3,
    AT_RAGEBUFF_1,
    AT_RAGEBUFF_2,
    AT_SET_OPTION_IMPROVE_STRENGTH = AT_RAGEBUFF_2 + 1,
    AT_SET_OPTION_IMPROVE_DEXTERITY,
    AT_SET_OPTION_IMPROVE_ENERGY,
    AT_SET_OPTION_IMPROVE_VITALITY,
    AT_SET_OPTION_IMPROVE_CHARISMA,
    AT_SET_OPTION_IMPROVE_ATTACK_MIN,
    AT_SET_OPTION_IMPROVE_ATTACK_MAX,
    AT_SET_OPTION_IMPROVE_MAGIC_POWER,
    AT_SET_OPTION_IMPROVE_DAMAGE,
    AT_SET_OPTION_IMPROVE_ATTACKING_PERCENT,
    AT_SET_OPTION_IMPROVE_DEFENCE,
    AT_SET_OPTION_IMPROVE_MAX_LIFE,
    AT_SET_OPTION_IMPROVE_MAX_MANA,
    AT_SET_OPTION_IMPROVE_MAX_AG,
    AT_SET_OPTION_IMPROVE_ADD_AG,
    AT_SET_OPTION_IMPROVE_CRITICAL_DAMAGE_PERCENT,
    AT_SET_OPTION_IMPROVE_CRITICAL_DAMAGE,
    AT_SET_OPTION_IMPROVE_EXCELLENT_DAMAGE_PERCENT,
    AT_SET_OPTION_IMPROVE_EXCELLENT_DAMAGE,
    AT_SET_OPTION_IMPROVE_SKILL_ATTACK,
    AT_SET_OPTION_DOUBLE_DAMAGE,
    AT_SET_OPTION_DISABLE_DEFENCE,
    AT_SET_OPTION_IMPROVE_SHIELD_DEFENCE,
    AT_SET_OPTION_TWO_HAND_SWORD_IMPROVE_DAMAGE,

    AT_SET_OPTION_IMPROVE_ATTACK_2,
    AT_SET_OPTION_IMPROVE_ATTACK_1,
    AT_SET_OPTION_IMPROVE_DEFENCE_3,
    AT_SET_OPTION_IMPROVE_DEFENCE_4,
    AT_SET_OPTION_IMPROVE_MAGIC,
    AT_SET_OPTION_ICE_MASTERY,
    AT_SET_OPTION_POSION_MASTERY,
    AT_SET_OPTION_THUNDER_MASTERY,
    AT_SET_OPTION_FIRE_MASTERY,
    AT_SET_OPTION_EARTH_MASTERY,
    AT_SET_OPTION_WIND_MASTERY,
    AT_SET_OPTION_WATER_MASTERY,

    AT_IMPROVE_MAX_MANA,
    AT_IMPROVE_MAX_AG,
};
//publicfile end

//npcbreederfile start
enum
{
    BREEDER_NONE = 0,
    BREEDER_START,
    BREEDER_RECOVERY,
    BREEDER_REVIVAL,
    BREEDER_END
};

enum
{
    REVIVAL_NONE = 0,
    REVIVAL_DARKHORSE,
    REVIVAL_DARKSPIRIT,
    REVIVAL_END
};

enum
{
    REVIVAL_SUCCESS = 0,
    REVIVAL_ERROR_ZEN,
    REVIVAL_ERROR_LEVEL,
    REVIVAL_ERROR_END
};

enum
{
    ITEM_ETC_TYPE = 0,
    ITEM_DARKHORSE,
    ITEM_DARKSPIRIT,
    ITEM_BLESS_GEM,
    ITEM_SPIRIT_GEM,
    ITEM_CHAOS_GEM,
    ITEM_CREATING_GEM,
    ITEM_LIFE_GEM,
    ITEM_END
};
//npcbreederfile end

//gm_kanturu_2nd start
enum POPUP_MESSAGE
{
    POPUP_NONE = 0,
    POPUP_USER_OVER,
    POPUP_NOT_MUNSTONE,
    POPUP_FAILED,
    POPUP_FAILED2,
    POPUP_UNIRIA = 5,
    POPUP_CHANGERING,
    POPUP_NOT_HELPER,
};
//gm_kanturu_2nd end

//csquest start
enum
{
    TYPE_QUEST = 0,
    TYPE_DEVIL_SQUARE,
    TYPE_BLOOD_CASTLE,
    TYPE_CURSEDTEMPLE,
    TYPE_QUEST_END
};

enum
{
    QUEST_VIEW_NONE = 0,
    QUEST_VIEW_NPC,
    QUEST_VIEW_PREVIEW,
    QUEST_VIEW_END
};

enum    //
{
    QUEST_ITEM = 1,
    QUEST_MONSTER,
};

enum
{
    QUEST_NONE = 0,
    QUEST_ING = 1,
    QUEST_END,
    QUEST_NO,
    QUEST_READY,
    QUEST_ERROR,
};

enum
{
    QUEST_CHANGE_UP_1 = 0,
    QUEST_CHANGE_UP_2,
    QUEST_CHANGE_UP_3,
    QUEST_COMBO,
    QUEST_3RD_CHANGE_UP_1,
    QUEST_3RD_CHANGE_UP_2,
    QUEST_3RD_CHANGE_UP_3,
    QUEST_LIST_END
};
//csquest end

//cspetsystem start
enum
{
    PET_FLYING = 0,
    PET_FLY,
    PET_ESCAPE,
    PET_STAND,
    PET_STAND_START,
    PET_ATTACK,
    PET_ATTACK_MAGIC,
    PET_END
};

enum    PET_TYPE
{
    PET_TYPE_NONE = -1,
    PET_TYPE_DARK_SPIRIT = 0,
    PET_TYPE_DARK_HORSE,
    PET_TYPE_END
};

enum    PET_COMMAND
{
    PET_CMD_DEFAULT = 0,
    PET_CMD_RANDOM,
    PET_CMD_OWNER,
    PET_CMD_TARGET,
    PET_CMD_END
};
//cspetsystem end

//csparts start
enum
{
    PARTS_LION = 4,
    PARTS_WEBZEN,
    PARTS_ATTACK_TEAM_MARK,
    PARTS_ATTACK_TEAM_MARK2,
    PARTS_ATTACK_TEAM_MARK3,
    PARTS_ATTACK_KING_TEAM_MARK,
    PARTS_ATTACK_KING_TEAM_MARK2,
    PARTS_ATTACK_KING_TEAM_MARK3,
    PARTS_DEFENSE_TEAM_MARK,
    PARTS_DEFENSE_KING_TEAM_MARK,
    PARTS_END
};
//csparts end

//csmapinterface start
enum
{
    TYPE_OBSERVER = 0,
    TYPE_GUILD_SOLDIER,
    TYPE_GUILD_COMMANDER
};
//csmapinterface end

//csitemsetoption start
enum
{
    SET_OPTION_NONE = 0,
    SET_OPTION_STRENGTH,
    SET_OPTION_DEXTERITY,
    SET_OPTION_ENERGY,
    SET_OPTION_VITALITY,
    SET_OPTION_END
};
//csitemsetoption start

//cseventmatch start
enum  MATCH_TYPE
{
    TYPE_MATCH_NONE = 0,
    TYPE_MATCH_DEVIL_ENTER_START,
    TYPE_MATCH_DEVIL_ENTER_CLOSE,
    TYPE_MATCH_DEVIL_CLOSE,
    TYPE_MATCH_CASTLE_ENTER_CLOSE,
    TYPE_MATCH_CASTLE_INFILTRATION,
    TYPE_MATCH_CASTLE_CLOSE,
    TYPE_MATCH_CASTLE_END,
    TYPE_MATCH_CHAOS_ENTER_START = 11,
    TYPE_MATCH_CHAOS_EINFILTRATION,
    TYPE_MATCH_CHAOS_CLOSE,
    TYPE_MATCH_CHAOS_END,
    TYPE_MATCH_CURSEDTEMPLE_ENTER_CLOSE,
    TYPE_MATCH_CURSEDTEMPLE_GAME_START,
    TYPE_MATCH_DOPPELGANGER_ENTER_CLOSE,
    TYPE_MATCH_DOPPELGANGER_GAME_START,
    TYPE_MATCH_DOPPELGANGER_ICEWALKER,
    TYPE_MATCH_DOPPELGANGER_CLOSE,
    TYPE_MATCH_END
};

enum
{
    MATCH_TYPE_NONE_EVENT = 0,
    MATCH_TYPE_DEVIL_SQUARE,
    MATCH_TYPE_BLOOD_CASTLE,
    MATCH_TYPE_END
};
//cseventmatch end

enum COMMAND_TYPE
{
    COMMAND_NONE = -1,
    COMMAND_TRADE = 0,
    COMMAND_PURCHASE,
    COMMAND_PARTY,
    COMMAND_WHISPER,
    COMMAND_GUILD,
    COMMAND_GUILDUNION,
    COMMAND_RIVAL,
    COMMAND_RIVALOFF,
    COMMAND_ADD_FRIEND,
    COMMAND_FOLLOW,
    COMMAND_BATTLE,
    // Leads to the chat commands the server offers to this player.
    COMMAND_SPECIAL,
    COMMAND_END
};

//cmvp1stdirection start

enum CRYWOLF_OCCUPATION_STATE_TYPE
{
    CRYWOLF_OCCUPATION_STATE_PEACE = 0,
    CRYWOLF_OCCUPATION_STATE_OCCUPIED = 1,
    CRYWOLF_OCCUPATION_STATE_WAR = 2,
};

enum CRYWOLF_STATE_TYPE
{
    CRYWOLF_STATE_NONE = 0,
    CRYWOLF_STATE_NOTIFY_1 = 1,
    CRYWOLF_STATE_NOTIFY_2 = 2,
    CRYWOLF_STATE_READY = 3,
    CRYWOLF_STATE_START = 4,
    CRYWOLF_STATE_END = 5,
    CRYWOLF_STATE_ENDCYCLE = 6,
};

enum CRYWOLF_ALTAR_STATE
{
    CRYWOLF_ALTAR_STATE_NONE = 0,
    CRYWOLF_ALTAR_STATE_CONTRACTED = 1,
    CRYWOLF_ALTAR_STATE_APPLYING_CONTRACT = 2,
    CRYWOLF_ALTAR_STATE_EXCEEDING_CONTRACT_COUNT = 3,
    CRYWOLF_ALTAR_STATE_OCCUPYING = 4,
    CRYWOLF_ALTAR_STATE_OCCUPIED = 5,
};

//cmvp1stdirection end

//ckanturudirection start
enum KANTURU_STATE_TYPE
{
    KANTURU_STATE_NONE = 0,
    KANTURU_STATE_STANDBY = 1,
    KANTURU_STATE_MAYA_BATTLE = 2,
    KANTURU_STATE_NIGHTMARE_BATTLE = 3,
    KANTURU_STATE_TOWER = 4,
    KANTURU_STATE_END = 5,
};

enum KANTURU_MAYA_DIRECTION_TYPE
{
    KANTURU_MAYA_DIRECTION_NONE = 0,
    KANTURU_MAYA_DIRECTION_STANBY1 = 1,
    KANTURU_MAYA_DIRECTION_NOTIFY = 2,
    KANTURU_MAYA_DIRECTION_MONSTER1 = 3,
    KANTURU_MAYA_DIRECTION_MAYA1 = 4,
    KANTURU_MAYA_DIRECTION_END_MAYA1 = 5,
    KANTURU_MAYA_DIRECTION_ENDCYCLE_MAYA1 = 6,
    KANTURU_MAYA_DIRECTION_STANBY2 = 7,
    KANTURU_MAYA_DIRECTION_MONSTER2 = 8,
    KANTURU_MAYA_DIRECTION_MAYA2 = 9,
    KANTURU_MAYA_DIRECTION_END_MAYA2 = 10,
    KANTURU_MAYA_DIRECTION_ENDCYCLE_MAYA2 = 11,
    KANTURU_MAYA_DIRECTION_STANBY3 = 12,
    KANTURU_MAYA_DIRECTION_MONSTER3 = 13,
    KANTURU_MAYA_DIRECTION_MAYA3 = 14,
    KANTURU_MAYA_DIRECTION_END_MAYA3 = 15,
    KANTURU_MAYA_DIRECTION_ENDCYCLE_MAYA3 = 16,
    KANTURU_MAYA_DIRECTION_END = 17,
    KANTURU_MAYA_DIRECTION_ENDCYCLE = 18,
};

enum KANTURU_NIGHTMARE_DIRECTION_TYPE
{
    KANTURU_NIGHTMARE_DIRECTION_NONE = 0,
    KANTURU_NIGHTMARE_DIRECTION_IDLE = 1,
    KANTURU_NIGHTMARE_DIRECTION_NIGHTMARE = 2,
    KANTURU_NIGHTMARE_DIRECTION_BATTLE = 3,
    KANTURU_NIGHTMARE_DIRECTION_END = 4,
    KANTURU_NIGHTMARE_DIRECTION_ENDCYCLE = 5,
};

enum KANTURU_TOWER_STATE_TYPE
{
    KANTURU_TOWER_NONE = 0,
    KANTURU_TOWER_REVITALIXATION = 1,
    KANTURU_TOWER_NOTIFY = 2,
    KANTURU_TOWER_CLOSE = 3,
    KANTURU_TOWER_NOTIFY2 = 4,
    KANTURU_TOWER_END = 5,
    KANTURU_TOWER_ENDCYCLE = 6,
};
//ckanturudirection end

//ccomgem start
