#pragma once

// Inventory/grid layout and derived capacity constants, extracted from the legacy aggregate
// Core/Globals/_define.h (P2 disassembly).

#define INVENTORY_SCALE        20
#define COLUMN_INVENTORY       8
#define ROW_INVENTORY          8
#define COLUMN_SHOP_INVENTORY  8
#define ROW_SHOP_INVENTORY     15
#define COLUMN_TRADE_INVENTORY 8
#define ROW_TRADE_INVENTORY    4
#define COLUMN_MIX_INVENTORY   8
#define ROW_MIX_INVENTORY      4
#define ROW_INVENTORY_EXT      4
#define MAX_INVENTORY_EXT_COUNT 4
#define MAX_INVENTORY          (COLUMN_INVENTORY*ROW_INVENTORY)
#define MAX_INVENTORY_EXT_ONE  (COLUMN_INVENTORY*ROW_INVENTORY_EXT)
#define MAX_INVENTORY_EXT      (MAX_INVENTORY_EXT_ONE*MAX_INVENTORY_EXT_COUNT)
#define MAX_SHOP_INVENTORY     (COLUMN_SHOP_INVENTORY*ROW_SHOP_INVENTORY)
#define MAX_TRADE_INVENTORY    (COLUMN_TRADE_INVENTORY*ROW_TRADE_INVENTORY)
#define MAX_MIX_INVENTORY      (COLUMN_MIX_INVENTORY*ROW_MIX_INVENTORY)
