name: publish to nuget
on:
  push:
    branches:
      - master

permissions:
  contents: read

jobs:
  publish:
    name: Publish packages to nuget
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@ee0669bd1cc54295c223e0bb666b733df41de1c5
      - name: Setup .NET Core
        uses: actions/setup-dotnet@499789684c9a0d41c9b3f0d66a785ba17b1d51ab
        with:
          dotnet-version: 10.0.x

      - name: publish MUnique.OpenMU.PlugIns on version change
        uses: rohith/publish-nuget@5fdc86fb81a38b37521c9f153bfb60ac44e7ba93
        with:
          PROJECT_FILE_PATH: src/PlugIns/MUnique.OpenMU.PlugIns.csproj
          TAG_COMMIT: false
          NUGET_KEY: ${{secrets.NUGET_KEY}}
          PACKAGE_NAME: munique.openmu.plugins

      - name: publish MUnique.OpenMU.Network on version change
        uses: rohith/publish-nuget@5fdc86fb81a38b37521c9f153bfb60ac44e7ba93
        with:
          PROJECT_FILE_PATH: src/Network/MUnique.OpenMU.Network.csproj
          TAG_COMMIT: false
          NUGET_KEY: ${{secrets.NUGET_KEY}}
          PACKAGE_NAME: munique.openmu.network

      - name: publish MUnique.OpenMU.Network.Packets on version change
        uses: rohith/publish-nuget@5fdc86fb81a38b37521c9f153bfb60ac44e7ba93
        with:
          PROJECT_FILE_PATH: src/Network/Packets/MUnique.OpenMU.Network.Packets.csproj
          TAG_COMMIT: true
          TAG_FORMAT: v*
          NUGET_KEY: ${{secrets.NUGET_KEY}}
          PACKAGE_NAME: munique.openmu.network.packets
