# -*- coding: utf-8 -*-
import os as _os, sys as _sys
_sys.path.insert(0, _os.path.dirname(_os.path.dirname(_os.path.abspath(__file__))))
import config
W = _os.path.dirname(_os.path.abspath(__file__))
"""Rule-based translator for the residual gap (id/tl/pl/ja). Compositional item/skill/buff
names are assembled from per-language glossaries; proper nouns stay. Emits out_data_gap files
consumed by merge_gap.py, then validate like every batch."""
import json, os, re
STR={int(s['id']):s for s in json.load(open(config.STRINGS_JSON,encoding='utf-8'))['strings']}
WL={x['id']:x for x in json.load(open(os.path.join(W,'gap_worklist.json'),encoding='utf-8'))}

# ---------- ID (Indonesian) ----------
ID_SLOT={ # head nouns -> Indonesian (these move to front for armor/weapon sets)
 'armor':'Zirah','boots':'Sepatu','gloves':'SarungTangan','helm':'Helm','helmet':'Helm',
 'pants':'Celana','mask':'Topeng','shield':'Perisai','stick':'Tongkat','staff':'Tongkat',
 'sword':'Pedang','bow':'Busur','crossbow':'BusurSilang','axe':'Kapak','blade':'Bilah',
 'scepter':'Tongkat','spear':'Tombak','mace':'Gada','scythe':'Sabit','hammer':'Palu',
 'trident':'Trisula','lance':'Lembing','dagger':'Belati',
 'parchment':'Gulungan','scroll':'Gulungan','ticket':'Tiket','potion':'Ramuan','ring':'Cincin',
 'pendant':'Liontin','necklace':'Kalung','box':'Kotak','orb':'Bola','feather':'Bulu',
 'flame':'Api','cape':'Jubah','wing':'Sayap','wings':'Sayap','horn':'Tanduk','key':'Kunci',
 'eye':'Mata','talisman':'Jimat','seal':'Segel','elixir':'Eliksir','charm':'Jimat',
 'coin':'Koin','cloak':'Jubah','fragment':'Fragmen','stone':'Batu','branch':'Ranting',
 'figurine':'Patung','card':'Kartu','pass':'Tiket','bundle':'Bundel','package':'Paket',
 'book':'Buku','map':'Peta','gift':'Hadiah','fruit':'Buah','tome':'Kitab','glove':'SarungTangan',
 'backpack':'Tas','certificate':'Sertifikat','service':'Layanan','access':'Akses',
 'flower':'Bunga','petal':'Kelopak','cake':'Kue','wine':'Minuman','water':'Air',
}
ID_PHRASE={ # longest-match phrases
 'dark phoenix':'FeniksGelap','grand soul':'JiwaAgung','light plate':'LempengCahaya',
 'great dragon':'NagaPerkasa','red spirit':'RohMerah','red wing':'SayapMerah',
 'red sprit':'RohMerah','dark master':'MasterGelap','dark soul':'JiwaGelap','dark steel':'BajaGelap',
 'dragon knight':'KsatriaNaga','phoenix soul':'JiwaFeniks','eternal wing':'SayapAbadi',
 'piercing groove':'AlurTembus','cherry blossom':'Sakura','jack olantern':'JackOLantern',
 "jack o'lantern":'JackOLantern','morning star':'BintangTimur','crystal morning':'KristalTimur',
 'weapon of archangel':'SenjataMalaikatAgung','divine crossbow of archangel':'BusurIlahiMalaikatAgung',
 'divine scepter of archangel':'TongkatIlahiMalaikatAgung','divine staff of archangel':'TongkatIlahiMalaikatAgung',
 'divine sword of archangel':'PedangIlahiMalaikatAgung','divine stick of the archangel':'TongkatIlahiMalaikatAgung',
 'absolute weapon of archangel':'SenjataAbsolutMalaikatAgung',
 'character relocation':'RelokasiKarakter','character rename':'GantiNamaKarakter',
 'rare item':'ItemLangka','lucky armor':'ZirahKeberuntungan','lucky boots':'SepatuKeberuntungan',
 'lucky gloves':'SarungTanganHoki','lucky helm':'HelmHoki','lucky pants':'CelanaHoki',
 'party exp':'EXPParty','exp gain':'PerolehanEXP','item drop':'JatuhanItem','item gain':'PerolehanItem',
 'attack power':'KekuatanSerang','attack speed':'KecepatanSerang','attack rate':'TingkatSerangan',
 'attack success rate':'TingkatKeberhasilanSerang','defense rate':'TingkatPertahanan','defense success rate':'TingkatKeberhasilanBertahan',
 'success rate':'TingkatKeberhasilan','magic attack':'SeranganSihir','physical attack':'SeranganFisik',
 'maximum attack power':'KekuatanSerangMaks','minimum attack power':'KekuatanSerangMin',
 'max ag boost aura':'AuraAGMaks','max sd boost aura':'AuraSDMaks',
 'hp regen':'RegenHP','hp recovery':'PemulihanHP','mana recovery':'PemulihanMana','sd recovery':'PemulihanSD',
 'ag recovery':'PemulihanAG','recovery speed':'KecepatanPulih','recovery rate':'TingkatPemulihan',
 'automatic hp recovery':'PemulihanHPOtomatis','automatic mana recovery':'PemulihanManaOtomatis',
 'automatic ag recovery':'PemulihanAGOtomatis','automatic life recovery':'PemulihanHPOtomatis',
 'critical damage':'KerusakanKritis','critical dmg':'KerusakanKritis','double damage':'KerusakanGanda',
 'triple damage':'KerusakanTripel','excellent damage':'KerusakanUnggul','ignore defense':'TembusPertahanan',
 'ignore enemy':'TembusLawan','ignore def':'TembusDef','damage reflection':'PantulanKerusakan',
 'damage reduction':'PenguranganKerusakan','durability reduction':'PenguranganDayaTahan',
 'wizardry/curse':'Sihir/Kutukan','maximum wizardry':'SihirMaks','minimum wizardry':'SihirMin',
 'monster attack':'SeranganMonster','monster kills':'BunuhMonster','from monster kills':'dariBunuhMonster',
 'one-handed sword':'PedangSatuTangan','two-handed sword':'PedangDuaTangan',
 'one-handed staff':'TongkatSatuTangan','two-handed staff':'TongkatDuaTangan',
 'equipped weapon':'SenjataDipakai','pet durability':'DayaTahanPeliharaan',
 'spell of protection':'MantraPerlindungan','spell of restriction':'MantraPembatasan','spell of pursuit':'MantraPengejaran',
 'spell of quickness':'MantraKelincahan','spell of sublimation':'MantraSublimasi',
 'soul barrier':'PerisaiJiwa','iron defense':'PertahananBesi','invisibility cloak':'JubahTakTerlihat',
 'shadow phantom':'BayanganPhantom','besiegement guild':'GuildPengepungan','altar of wolf':'AltarSerigala',
 'crown registration':'RegistrasiMahkota','crown switch':'PindahMahkota','cry wolf':'CryWolf',
 'divine protection':'PerlindunganIlahi','gate open/close':'Buka/TutupGerbang','pk penalty':'HukumanPK',
 'illicit software':'PerangkatLiar','punishment for illicit software use':'HukumanPenggunaanPerangkatLiar',
 'general goods merchant':'PedagangBarangUmum','magic shop owner':'PemilikTokoSihir',
 'potion merchant':'PedagangRamuan','wandering merchant':'PedagangKelana','weapons merchant':'PedagangSenjata',
 'magic stone':'BatuSihir','magic backpack':'TasSihir','higher refining stone':'BatuPemurnianTinggi',
 'lower refining stone':'BatuPemurnianRendah','refining stone':'BatuPemurnian',
 'watchers of kundun':'PengawalKundun','gens ranking reward':'HadiahPeringkatGens',
 'mercenary guild office':'KantorGildTentaraBayaran','free mercenary':'TentaraBayaranBebas',
 'letter of request':'SuratPermintaan','npc dialog script error':'KesalahanSkripDialogNPC',
 'party request':'PermintaanParty','inland supply route':'RutePasokPedalaman','dungeon sweep':'SapuDungeon',
 'blood castle adaptation':'AdaptasiBloodCastle','blood castle challenge':'TantanganBloodCastle',
 'chaos castle adaptation':'AdaptasiChaosCastle','chaos castle challenge':'TantanganChaosCastle',
 'devil square adaptation':'AdaptasiDevilSquare','devil square challenge':'TantanganDevilSquare',
 'illusion temple adaptation':'AdaptasiIllusionTemple','illusion temple challenge':'TantanganIllusionTemple',
 'heroic courage':'KeberanianHeroik','heroic fighting spirit':'SemangatTempurHeroik',
 'heroic mentality':'MentalitasHeroik','heroic qualities':'KualitasHeroik','heroic tenacity':'KegigihanHeroik',
 'skill level':'TingkatKeahlian','rank':'Peringkat','adds command stat':'TambahStatCommand',
 'agility status':'StatusKelincahan','energy status':'StatusEnergi','health status':'StatusKesehatan',
 'strength status':'StatusKekuatan','control status':'StatusKontrol','transparency status':'StatusTransparan',
 'ascension':'Kenaikan','weaken':'Melemah','bleeding':'Berdarah','cold':'Dingin','freeze':'Beku',
 'monster chemistry attack resistance':'KetahananSeranganKimiaMonster','monster magic attack resistance':'KetahananSeranganSihirMonster',
 'boss':'Boss',
}
ID_WORD={
 'dragon':'Naga','dark':'Gelap','soul':'Jiwa','bone':'Tulang','brass':'Kuningan','bronze':'Perunggu',
 'adamantine':'Adamantin','ancient':'Kuno','ashcrow':'GagakAbu','atlans':'Atlans','brave':'Berani',
 'black':'Hitam','phoenix':'Feniks','steel':'Baja','master':'Master','demonic':'Iblis','destroy':'Hancur',
 'divine':'Ilahi','legendary':'Legendaris','leather':'Kulit','plate':'Lempeng','pad':'Bantalan',
 'scale':'Sisik','silk':'Sutra','eclipse':'Gerhana','glorious':'Mulia','guardian':'Penjaga',
 'hades':'Hades','hurricane':'Badai','iris':'Iris','eternal':'Abadi','great':'Perkasa','grand':'Agung',
 'light':'Cahaya','lightning':'Petir','lighting':'Petir','fire':'Api','ice':'Es','wind':'Angin',
 'storm':'Badai','spirit':'Roh','sacred':'Suci','seraphim':'Serafim','silver':'Perak','golden':'Emas',
 'gold':'Emas','red':'Merah','blue':'Biru','green':'Hijau','purple':'Ungu','pink':'MerahMuda',
 'white':'Putih','chaos':'Chaos','life':'Hidup','death':'Kematian','blood':'Darah','frost':'Beku',
 'phantom':'Hantu','knight':'Ksatria','lord':'Tuan','emperor':'Kaisar','fighter':'Petarung',
 'angel':'Malaikat','archangel':'MalaikatAgung','battle':'Tempur','royal':'Kerajaan','titan':'Titan',
 'viper':'Viper','serpent':'Ular','hawk':'Elang','raven':'Gagak','crow':'Gagak','wolf':'Serigala',
 'elemental':'Elemen','elite':'Elit','healing':'Penyembuhan','heal':'Pulih','mana':'Mana',
 'vitality':'Vitalitas','complex':'Kompleks','absolute':'Absolut','abyssal':'Abisal','celestial':'Langit',
 'crimson':'Kirmizi','morning':'Timur','star':'Bintang','sunlight':'CahayaMatahari','sun':'Matahari',
 'volcano':'GunungApi','thunder':'Guntur','blitz':'Kilat','valiant':'Gagah','violent':'Ganas',
 'sphinx':'Sfinks','sylphid':'Sylphid','vine':'Merambat','mist':'Kabut','venom':'Racun',
 'piercing':'Tembus','groove':'Alur','illusion':'Ilusi','sorcerer':'Penyihir','covenant':'Perjanjian',
 'condor':'Condor','fenrir':'Fenrir','uniria':'Uniria','dinorant':'Dinorant','satan':'Iblis',
 'heaven':'Surga','curse':'Kutukan','transformation':'Transformasi','skeleton':'Kerangka','elf':'Peri',
 'jewelry':'Perhiasan','case':'Wadah','elegant':'Anggun','old':'Lama','christmas':'Natal','santa':'Santa',
 'pumpkin':'Labu','chocolate':'Cokelat','rice':'Beras','blossom':'Sakura','firecracker':'KembangApi',
 'maple':'Maple','oak':'Ek','panda':'Panda','rudolf':'Rudolf','pet':'Peliharaan','unicorn':'Unicorn',
 'goblin':'Goblin','yeti':'Yeti','gorgon':'Gorgon','lethal':'Mematikan','wizard':'Penyihir',
 'magic':'Sihir','mystery':'Misteri','mirror':'Cermin','dimensions':'Dimensi','dimension':'Dimensi',
 'imperial':'Kekaisaran','inberial':'Kekaisaran','platina':'Platina','chromatic':'Pelangi',
 'nature':'Alami','reign':'Berkuasa','breaker':'Penghancur','explosion':'Ledakan','barrier':'Perisai',
 'holy':'Suci','claw':'Cakar','beast':'Binatang','club':'Pentung','burnt':'Terbakar','broken':'Patah',
 'complete':'Lengkap','secromicon':'Secromicon','first':'Pertama','second':'Kedua','third':'Ketiga',
 'fourth':'Keempat','fifth':'Kelima','1st':'Ke-1','2nd':'Ke-2','3rd':'Ke-3','higher':'Tinggi',
 'lower':'Rendah','refining':'Pemurnian','reset':'Reset','skill':'Keahlian','completion':'Penyelesaian',
 'request':'Permintaan','letter':'Surat','paid':'Berbayar','channel':'Saluran','open':'Terbuka',
 'varka':'Varka','premium':'Premium','character':'Karakter','party':'Party','ability':'Kemampuan',
 'of':'','the':'','s':'','a':'','to':'ke','and':'dan','or':'atau',
 'increase':'Naik','increases':'Naik','increaese':'Naik','boost':'Boost','powup':'Tingkat',
 'mastery':'Penguasaan','strengthener':'Penguat','strengthen':'Penguat','proficiency':'Keahlian',
 'maximum':'Maks','minimum':'Min','max':'Maks','strength':'Kekuatan','agility':'Kelincahan',
 'energy':'Energi','defense':'Pertahanan','defence':'Pertahanan','defensibility':'Ketahanan',
 'attack':'Serangan','damage':'Kerusakan','dmg':'Kerusakan','speed':'Kecepatan','rate':'Tingkat',
 'stamina':'Stamina','command':'Command','health':'Kesehatan','life':'Nyawa','sd':'SD','ag':'AG',
 'hp':'HP','mp':'MP','xp':'XP','pvp':'PvP','pve':'PvE','exp':'EXP','zen':'Zen',
 'resistance':'Ketahanan','immunity':'Kekebalan','reduction':'Pengurangan','decrease':'Turun',
 'recover':'Pulih','recovers':'Pulih','recoverys':'Pemulihan','restores':'Pulih','fully':'Penuh',
 'all':'Semua','full':'Penuh','automatic':'Otomatis','status':'Status','attempt':'Percobaan',
 'enabled':'Aktif','disabled':'Nonaktif','contract':'Kontrak','besiegement':'Pengepungan',
 'hero':'Pahlawan','watch':'Pengawasan','watchtower':'MenaraPengawas','vampiric':'Vampirik',
 'invincible':'TakTerkalahkan','invincibility':'Kekebalan','innovate':'Inovasi','innovation':'Inovasi',
 'penetrate':'Tembus','penetration':'Penetrasi','absorption':'Serapan','absorb':'Serap',
 'swell':'Naik','berserker':'Berserker','berserk':'Beringas','bless':'Berkah','blessing':'Berkah',
 'blind':'Buta','poison':'Racun','sleep':'Tidur','stun':'Stun','decay':'Busuk','ice':'Es',
 'flame':'Api','flamestrike':'SeranganApi','nova':'Nova','inferno':'Neraka','hellfire':'ApiNeraka',
 'cyclone':'Siklon','twister':'PutingBeliung','twisting':'Putar','spiral':'Spiral','slash':'Tebasan',
 'falling':'Jatuh','lunge':'Terjang','uppercut':'Uppercut','beast':'Binatang','charge':'Serbu',
 'cometfall':'JatuhKomet','meteor':'Meteor','starfall':'HujanBintang','teleport':'Teleportasi',
 'ally':'Sekutu','summon':'Panggil','assassin':'Pembunuh','bali':'Bali','golem':'Golem',
 'satyros':'Satyros','soldier':'Prajurit','elite':'Elit','monster':'Monster','vengeance':'BalasDendam',
 'cure':'Sembuh','heal':'Sembuh','party':'Party','healing':'Penyembuhan','multi-shot':'TembakGanda',
 'triple':'Tripel','shot':'Tembakan','phoenix':'Feniks','plasma':'Plasma','force':'Kekuatan',
 'wave':'Gelombang','power':'Kekuatan','rageful':'Murka','blow':'Pukulan','killing':'Mematikan',
 'impale':'Tusuk','death':'Kematian','stab':'Tusukan','earthshake':'GempaBumi','earth':'Tanah',
 'prison':'Penjara','electric':'Listrik','spark':'Percik','spike':'Duri','ball':'Bola',
 'evil':'Jahat','spirit':'Roh','dark':'Gelap','side':'Sisi','horse':'Kuda','raven':'Gagak',
 'howling':'Lolongan','howl':'Lolongan','storm':'Badai','scream':'Jeritan','breath':'Napas',
 'burst':'Ledakan','blast':'Ledakan','tome':'Kitab','cast':'Rapal','other':'Lain','world':'Dunia',
 'mace':'Gada','spear':'Tombak','scepter':'Tongkat','shield':'Perisai','sword':'Pedang',
 'staff':'Tongkat','stick':'Tongkat','bow':'Busur','crossbow':'BusurSilang','axe':'Kapak',
 'use':'Pakai','pet':'Peliharaan','slasher':'Pengiris','roar':'Raungan','chain':'Rantai',
 'drive':'Dorong','diseier':'Diseier','chaotic':'Kacau','combo':'Combo','cancel':'Batal',
 'cast':'Rapal','invincibility':'Kekebalan','stun':'Stun','invisibility':'TakTerlihat',
 'swell':'Naik','mana':'Mana','requiem':'Requiem','frost':'Beku','shied-burn':'BakarPerisai',
 'burn':'Bakar','shock':'Kejut','lightning':'Petir','arrow':'Panah','ice':'Es','flame':'Api',
 'strike':'Pukulan','gigantic':'Raksasa','expansion':'Perluasan','wizardry':'Sihir','infinity':'TanpaBatas',
 'abolish':'Hapus','magic':'Sihir','control':'Kontrol','block':'Tangkis','switch':'Ganti',
 'set':'Set','equipped':'Dipakai','one-handed':'SatuTangan','two-handed':'DuaTangan',
 'durability':'DayaTahan','increment':'Tambahan','chemistry':'Kimia','penalty':'Hukuman',
 'bonus':'Bonus','gladiator':'Gladiator','honor':'Kehormatan','divinity':'Keilahian',
 'mobility':'Mobilitas','sustenance':'DayaTahan','wealth':'Kekayaan','ascension':'Kenaikan',
 'battle':'Tempur','defense':'Pertahanan','quickness':'Kelincahan','wrath':'Murka','strength':'Kekuatan',
 'neil':'Neil','shamut':'Shamut','summoner':'Summoner','attack':'Serangan','rod':'Tongkat',
 'skill':'Keahlian','temple':'Kuil','sublimation':'Sublimasi','wolf':'Serigala','altar':'Altar',
 'guild1':'Guild1','guild2':'Guild2','guild3':'Guild3','npc':'NPC','transparency':'Transparan',
 'general':'Umum','goods':'Barang','merchant':'Pedagang','shop':'Toko','owner':'Pemilik',
 'marce':'Marce','silvia':'Silvia','herald':'Herald','rhea':'Rhea','leina':'Leina',
 'relics':'Peninggalan','relic':'Peninggalan','ruins':'Reruntuhan','ruin':'Reruntuhan','island':'Pulau',
 'swamp':'Rawa','calmness':'Ketenangan','peace':'Damai','tower':'Menara','lost':'Hilang',
 'dungeon':'Dungeon','kanturu':'Kanturu','relics':'Peninggalan',
 'adaptation':'Adaptasi','challenge':'Tantangan','whispers':'Bisikan','trade':'Dagang',
 'hmm':'Hmm','free':'Bebas','mercenary':'TentaraBayatan','office':'Kantor','dialog':'Dialog',
 'script':'Skrip','error':'Kesalahan','request':'Permintaan','inland':'Pedalaman','supply':'Pasok',
 'route':'Rute','sweep':'Sapu','ranking':'Peringkat','reward':'Hadiah','qualities':'Kualitas',
 'courage':'Keberanian','fighting':'Tempur','mentality':'Mentalitas','tenacity':'Kegigihan',
 'hound':'Anjing','hunt':'Berburu','walls':'Tembok','beyond':'Luar','abilities':'Kemampuan',
 'sure':'Pasti','within':'Dalam','well':'','well':'','im':'Aku','scorpions':'Kalajengking',
 'chain':'Rantai','noria':'Noria','lorencia':'Lorencia','down':'','30':'30','3':'3',
}
