# -*- coding: utf-8 -*-
ID_ADD={
 'rare':'Langka','item':'Item','lucky':'Hoki','seed':'Benih','small':'Kecil','recovery':'Pemulihan',
 'sphere':'Bola','handed':'Tangan','cherry':'Ceri','jewel':'Permata','critical':'Kritis','crystal':'Kristal',
 'success':'Berhasil','destruction':'Kehancuran','double':'Ganda','ignore':'Tembus','large':'Besar',
 'spell':'Mantra','ray':'Sinar','day':'Hari','weapon':'Senjata','castle':'Istana','multi':'Multi',
 'def':'Def','devil':'Iblis','drain':'Sedot','greater':'Besar','chance':'Peluang','one':'Satu','two':'Dua',
 'hour':'Jam','beam':'Pancaran','luck':'Hoki','elven':'Peri','from':'dari','kills':'Bunuh','reigning':'Berkuasa',
 'protection':'Perlindungan','watchers':'Pengawal','weakness':'Kelemahan','ribbon':'Pita','points':'Poin',
 'stat':'Stat','aqua':'Air','relocation':'Relokasi','crescent':'Sabit','crown':'Mahkota','reflection':'Pantulan',
 'invitation':'Undangan','transfer':'Transfer','gm':'GM','order':'Ordo','gemstone':'BatuMulia','giant':'Raksasa',
 'iron':'Besi','warrior':'Prajurit','lv':'Lv','aura':'Aura','medium':'Sedang','ruby':'Rubi','rune':'Rune',
 'sealed':'Tersegel','shining':'Bersinar','short':'Pendek','skull':'Tengkorak','resurrection':'Kebangkitan',
 'despair':'Keputusasaan','darkness':'Kegelapan','spirits':'Roh','adds':'Tambah','angelic':'Malaikat',
 'antidote':'Penawar','apple':'Apel','guardsman':'Penjaga','bolt':'Peluru','murderer':'Pembunuh','overrule':'Penguasa',
 'mini':'Mini','rename':'GantiNama','play':'Main','cloud':'Awan','moon':'Bulan','glory':'Kemuliaan',
 'cross':'Salib','cursed':'Terkutuk','stinger':'Penyengat','daybreak':'Fajar','deadly':'Mematikan',
 'demon':'Iblis','square':'Alun','poleaxe':'KapakGalah','slayer':'Pembunuh','binds':'Ikatan','eilte':'Elit',
 'elvian':'Peri','emerald':'Zamrud','fortitude':'Ketabahan','summoning':'Pemanggilan','pk':'PK','physical':'Fisik',
 'pollution':'Polusi','ragefighter':'PetarungAmuk','sprit':'Roh','remedy':'Obat','love':'Cinta','saint':'Suci',
 'fortune':'Hoki','fireburst':'LedakanApi','meteorite':'Meteorit','enhance':'Tingkatkan','server':'Server',
 'shied':'Perisai','siege':'Pengepungan','sign':'Tanda','sixth':'Keenam','snowman':'ManusiaSalju',
 'shard':'Pecahan','pursuit':'Pengejaran','restriction':'Pembatasan','spiked':'Berduri','splinter':'Serpihan',
 'stardust':'DebuBintang','adjustment':'Penyesuaian','striker':'Penyerang','suspicious':'Mencurigakan',
 'scrap':'Potongan','paper':'Kertas','dancer':'Penari','sylph':'Sylph','symbol':'Simbol','assembly':'Majelis',
 'tear':'AirMata','tiger':'Harimau','topaz':'Topas','town':'Kota','portal':'Portal','vault':'Brankas',
 'wandering':'Kelana','weapons':'Senjata','worn':'Usang','horseshoe':'TapalKuda','budle':'Bundel','gem':'Permata',
 'secret':'Rahasia','high':'Tinggi','low':'Rendah','rays':'Sinar','moonstone':'BatuBulan','hand':'Tangan',
 'heart':'Hati','miner':'Penambang','enemy':'Lawan','excellent':'Unggul','indulgence':'Pengampunan',
 'village':'Desa','blessings':'Berkah','cry':'Tangis','drink':'Minuman','food':'Makanan','creation':'Penciptaan',
 'harmony':'Harmoni','round':'Bulat','saber':'Pedang','little':'Kecil','sceptor':'Tongkat','di':'Di','mono':'Mono',
 'tri':'Tri','successrate':'TingkatBerhasil','defsuccessrate':'TingkatBertahan',
 'dimensionwings':'SayapDimensi','losttower':'MenaraHilang','kantururelics':'PeninggalanKanturu',
 'kantururuins':'ReruntuhanKanturu','peaceswamp':'RawaDamai','swamp':'Rawa','relics':'Peninggalan',
 'ruins':'Reruntuhan','b':'B','c':'C','d':'D','e':'E','f':'F','o':'O','st':'Ke','nd':'Ke','j':'J',
 'el':'El','salamander':'Salamander','sapphire':'Safir','flameberge':'Flameberge','falchion':'Falchion',
 'berdysh':'Berdysh','arquebus':'Arquebus','halberd':'Halberd','flail':'Flail','bill':'Bill','balrog':'Balrog',
 'bluewing':'SayapBiru','lagle':'Lagle','samut':'Samut','neil':'Neil','book':'Buku','chistmas':'Natal',
 'ruin':'Kehancuran','absorb':'Serap','absorption':'Serapan','powup':'+','pow':'+',
 'elixir':'Eliksir','doom':'Kiamat','note':'Catatan','increment':'Tambahan','orb':'Bola',
 'fruits':'Buah','fruits':'Buah','el':'Lv','stun':'Stun','dungeon':'Dungeon','monster':'Monster',
 'helm':'Helm','successrate':'TingkatBerhasil',
}
ID_PHRASE_ADD={
 'critical dmg increase powup':'NaikDMGKritis','defense success rate increase':'NaikTingkatBertahan',
 'increase defense success rate':'NaikTingkatBertahan','dimensionwings defense':'SayapDimensi Pertahanan',
 'dimensionwings attack':'SayapDimensi Serangan','dimensionwings absorb':'SayapDimensi Serap',
 'wing of ruin':'SayapKehancuran','reigning cloak':'JubahBerkuasa','use scepter : pet':'Tongkat:Hewan',
 'medium elite healing potion':'RamuanHealingElit','open access ticket':'TiketAkses','paid channel access ticket':'TiketSaluran',
 'completion certificate':'Sertifikat','lucky boots ticket':'TiketSepatuHoki','lucky armor ticket':'TiketZirahHoki',
 'lucky gloves ticket':'TiketSarungTanganHoki','lucky helm ticket':'TiketHelmHoki','lucky pants ticket':'TiketCelanaHoki',
 'lost tower':'MenaraHilang','peace swamp':'RawaDamai','swamp of calmness':'RawaKetenangan',
 'eternal wings defense':'SayapAbadi Pertahanan','eternal wings attack':'SayapAbadi Serangan','eternal wings absorption':'SayapAbadi Serap',
 'illusion wings defense':'SayapIlusi Pertahanan','illusion wings attack':'SayapIlusi Serangan','illusion wings absorption':'SayapIlusi Serap',
 'emperor cape defense':'JubahKaisar Pertahanan','emperor cape attack':'JubahKaisar Serangan','emperor cape absorption':'JubahKaisar Serap',
 'wing of storm defense':'SayapBadai Pertahanan','wing of storm attack':'SayapBadai Serangan','wing of storm absorption':'SayapBadai Serap',
 'eilte transfer skeleton ring':'CincinKerangkaTransferElit','elite transfer skeleton ring':'CincinKerangkaTransferElit',
 'def successrate increase':'NaikTingkatDef','reigning cloak defense':'JubahBerkuasa Def','reigning cloak attack':'JubahBerkuasa Atk','reigning cloak absorption':'JubahBerkuasa Serap',
 'snowman transformation ring':'CincinManusiaSalju','use scepter pet strengthener':'Tongkat:Hewan+',
 'wing of ruin attack':'SayapKehancuran Atk','wing of ruin defense':'SayapKehancuran Def','wing of ruin absorption':'SayapKehancuran Serap',
}
