# -*- coding: utf-8 -*-
import os as _os
W = _os.path.dirname(_os.path.abspath(__file__))
# 34 questword records (IDs) that the English client left in Korean; translated from the
# shipped Chinese (Chs) source into the 7 MT locales. Variable-length records, no slot cap.
import json
T = {
"de": {
7001:"Lagerverwaltung ist immer wichtig. Die Löhne der Sicherheitswachen, der Teleport zwischen den Dörfern und die Unmenge ungenutzter Lager … wir brauchen dringend ein neues Lager! Darum habe ich einen klugen Plan.",
7002:"Welche Methode?",
7003:"Ich verkufe Antiquitten an Reiche. Für Abenteurer sind es unscheinbare Steine, für Reiche aber von künstlerischem Wert. So verdiene ich mein Geld. Wenn Ihr mir helft, erlaube ich Euch die Nutzung des Lagers.",
7004:"Wie kann ich Euch helfen?",
7005:"Ich überlasse Euch ein Fach im neuen Lager. Bringt mir die antike Statue, einverstanden? (Charakter ab Level 50)",
7007:"Verstanden. (Annehmen)",
7008:"Ich bin gerade zu beschftigt, um Euch zu helfen. (Ablehnen)",
7009:"Schade. Wenn Ihr Euer Lager erweitern wollt, sucht mich jederzeit wieder auf. (Quest abgebrochen)",
7010:"Besiegt den Todesritter in Ebene 7 des Turms der verlorenen Seelen, um eine antike Statue zu erhalten. Bringt sie mir, und ich überlasse Euch ein neues Lagerfach. Die Zugangsberechtigung wird nach der Neuverbindung wirksam.",
7011:"Wisst Ihr, woraus Euer alltäglicher Rucksack besteht? Aus magischem Stoff. Deshalb knnen Abenteurer beliebig viel schwere Ausrüstung tragen. Da ihn jeder als Vorrat besitzt, ist er sehr wertvoll. Ich hätte Euch einen Handel vorzuschlagen …",
7012:"Welchen Handel meint Ihr?",
7013:"Mit magischem Stoff lässt sich mehr im magischen Rucksack verstauen. Bringt mir magischen Stoff, dann vergrößere ich Euren Rucksack mit dem Rest, damit Ihr mehr tragen knnt.",
7015:"Bringt mir also magischen Stoff, einverstanden? (Charakter ab Level 150)",
7017:"Verstanden. (Annehmen)",
7018:"Ich bin gerade zu beschftigt, um Euch zu helfen. (Ablehnen)",
7019:"Schade. Wenn Ihr Interesse habt, sucht mich jederzeit wieder auf. (Quest abgebrochen)",
7020:"Besiegt die Silberne Walküre in Ebene 3 von Atlans, um magischen Stoff zu erhalten. Er ist nicht leicht zu bekommen, doch wenn sich der magische Rucksack vergrößert, lohnt die Mühe. Bringt mir den magischen Stoff. Der Rucksack wird nach Neuverbindung wirksam.",
7021:"Was führt Euch zu mir?",
7022:"Gibt es einen Weg, den magischen Rucksack zu vergrößern?",
7023:"Ihr wollt den magischen Rucksack vergrößern? Es ist nicht leicht, aber es gibt einen Weg. Ein Magier kann mit Raumstoff den ungenutzten Platz erweitern.",
7025:"Seid Ihr bereit, den Raumstoff zu suchen? (Charakter ab Level 300)",
7027:"Verstanden. (Annehmen)",
7028:"Ich bin gerade zu beschftigt, um Euch zu helfen. (Ablehnen)",
7029:"Schade. Wenn Ihr Euer Lager erweitern wollt, sucht mich jederzeit wieder auf. (Quest abgebrochen)",
7030:"Besiegt Alquamos in Ebene 1 der Himmelsstadt, um Raumstoff zu erhalten. Bringt ihn mir, dann vergrößere ich Euren magischen Rucksack erneut. Die Erweiterung wird nach Neuverbindung wirksam.",
7801:"Wenn Ihr Euer Lager erweitern wollt, sucht den wandernden Händler Zero.",
7802:"Übergebt die antike Statue des Todesritters aus Ebene 7 des Turms der verlorenen Seelen an den wandernden Händler Zero, um das erweiterte Lager zu erhalten.",
7803:"Für die erste Rucksackerweiterung sucht den wandernden Händler Zero.",
7804:"Übergebt den magischen Stoff der Silbernen Walküre aus Atlans an den wandernden Händler Zero, um die erste Rucksackerweiterung zu erhalten. Startet zur Bestätigung neu.",
7805:"Für die zweite Rucksackerweiterung sucht den wandernden Händler Zero.",
7806:"Übergebt den Raumstoff des Alquamos aus der Himmelsstadt an den wandernden Händler Zero, um die zweite Rucksackerweiterung zu erhalten. Startet zur Bestätigung neu.",
7901:"Handelserweiterung der Händlergilde",
7902:"Magischer Stoff",
7903:"Raumstoff",
},
"id": {
7001:"Mengelola gudang selalu penting. Gaji Penjaga Keamanan, teleport antar desa, dan banyaknya gudang menganggur … kita sangat butuh gudang baru! Jadi aku punya rencana cerdik.",
7002:"Cara apa?",
7003:"Menjual barang antik kepada orang kaya. Di mata petualang hanya batu tak berarti, tapi bagi orang kaya bernilai seni. Begitulah mereka … begitulah aku mencari uang. Jika kau mau membantu, aku izinkan kau memakai gudang itu.",
7004:"Bagaimana aku bisa membantumu?",
7005:"Aku akan memberimu satu ruang di gudang baru. Tolong bawakan Patung Kuno untukku, mau? (Karakter level 50 ke atas)",
7007:"Baiklah. (Terima)",
7008:"Aku sedang terlalu sibuk untuk membantumu. (Tolak)",
7009:"Sayang sekali. Jika ingin memperluas gudang, temui aku kapan saja. (Misi dibatalkan)",
7010:"Kalahkan Death Knight di lantai 7 Lost Tower untuk mendapat Patung Kuno. Bawakan patung itu, dan aku akan memberimu gudang baru. Hak akses gudang berlaku setelah reconnect.",
7011:"Tahukah kau terbuat dari apa tas yang biasa kau pakai? Kain sihir. Itulah sebabnya petualang bisa membawa banyak perlengkapan berat. Karena semua orang memilikinya sebagai bekal, sebenarnya ia sangat berharga. Sebenarnya, ada kesepakatan yang ingin kutawarkan …",
7012:"Kesepakatan apa maksudmu?",
7013:"Dengan kain sihir, lebih banyak barang bisa masuk ke tas sihir. Bawakan kain sihir, maka aku akan memperbesar tasmu dengan sisa kain agar bisa memuat lebih banyak barang.",
7015:"Jadi, tolong bawakan kain sihir untukku, mau? (Karakter level 150 ke atas)",
7017:"Baiklah. (Terima)",
7018:"Aku sedang terlalu sibuk untuk membantumu. (Tolak)",
7019:"Sayang sekali. Jika tertarik, temui aku kapan saja. (Misi dibatalkan)",
7020:"Kalahkan Silver Valkyrie di lantai 3 Atlans untuk mendapat kain sihir. Tidak mudah didapat, tapi jika tas sihir bisa diperbesar, lelah ini sepadan. Tolong bawakan kain sihir. Tas sihir berlaku setelah reconnect.",
7021:"Ada apa kau datang?",
7022:"Adakah cara memperbesar tas sihir?",
7023:"Ingin memperbesar tas sihir? Tidak mudah, tapi ada caranya. Konon seorang penyihir bisa memperluas ruang yang terbuang memakai kain ruang.",
7025:"Maukah kau mencari kain ruang? (Karakter level 300 ke atas)",
7027:"Baiklah. (Terima)",
7028:"Aku sedang terlalu sibuk untuk membantumu. (Tolak)",
7029:"Sayang sekali. Jika ingin memperluas gudang, temui aku kapan saja. (Misi dibatalkan)",
7030:"Kalahkan Alquamos di lantai 1 Sky City untuk mendapat kain ruang. Bawakan kain ruang, dan aku akan memperbesar tas sihirmu lagi. Perluasan tas berlaku setelah reconnect.",
7801:"Jika ingin memperluas gudang, temui pedagang keliling Zero.",
7802:"Serahkan Patung Kuno yang dijatuhkan Death Knight di lantai 7 Lost Tower kepada pedagang keliling Zero untuk mendapat gudang yang diperluas.",
7803:"Untuk perluasan tas pertama, temui pedagang keliling Zero.",
7804:"Serahkan kain sihir yang dijatuhkan Silver Valkyrie di Atlans kepada pedagang keliling Zero untuk mendapat perluasan tas pertama. Reconnect untuk memastikannya.",
7805:"Untuk perluasan tas kedua, temui pedagang keliling Zero.",
7806:"Serahkan kain ruang yang dijatuhkan Alquamos di Sky City kepada pedagang keliling Zero untuk mendapat perluasan tas kedua. Reconnect untuk memastikannya.",
7901:"Perluasan Transaksi Serikat Pedagang",
7902:"Kain Sihir",
7903:"Kain Ruang",
},
"ja": {
7001:"倉庫の管理はいつだって重要だ。警備員の給料、村と村の間のワープ、それに天文学的な数の遊休倉庫……新しい倉庫が急務なんだ！そこで名案を思いついた。",
7002:"どんな方法ですか？",
7003:"金持ちに骨董品を売って一儲けするのさ。冒険者には取るに足らない石ころでも、金持ちには芸術的価値がある。金持ちはそういうものさ……とにかく私はこれで稼いでいる。手伝ってくれるなら、あの倉庫を使わせてやろう。",
7004:"どうお手伝いすればよろしいですか？",
7005:"新しい倉庫から一区画を分けてあげよう。古代の彫像を私に持ってきてくれないか？（レベル50以上のキャラクター）",
7007:"わかりました。（承諾）",
7008:"今は忙しくて手伝えません。（拒否）",
7009:"残念だ。倉庫を拡張したくなったら、いつでもまた来てくれ。（クエストがキャンセルされました）",
7010:"ロストタワー7階でデスナイトを倒すと、古代の彫像を手に入れるチャンスがある。彫像を持ってくれば新しい倉庫を分けてやろう。倉庫の使用権限は再接続後に有効になる。",
7011:"普段使っているバッグが何でできているか知っているか？魔法の布だ。だから冒険者はどれほど重い装備を持っても平気なんだ。誰もが補給品として持っているが、実はとても貴重なものでね。実は、君と取り引きしたい話がある……",
7012:"どんな取り引きですか？",
7013:"魔法の布があれば、魔法のバッグにもっと多くの物を入れられる。魔法の布を持ってきてくれれば、残った布で君のバッグを大きく作り直し、より多く入るようにしてやろう。",
7015:"だから魔法の布を持ってきてくれないか？（レベル150以上のキャラクター）",
7017:"わかりました。（承諾）",
7018:"今は忙しくて手伝えません。（拒否）",
7019:"残念だ。興味があれば、いつでもまた来てくれ。（クエストがキャンセルされました）",
7020:"アトランス3階でシルバーヴァルキリーを倒すと魔法の布を手に入れるチャンスがある。簡単ではないが、魔法のバッグが大きくなるなら苦労する価値はある。魔法の布を持ってきてくれ。魔法のバッグは再接続後に有効になる。",
7021:"何の用で来ましたか？",
7022:"魔法のバッグをもっと大きくする方法はありますか？",
7023:"魔法のバッグを大きくしたいのか？簡単ではないが方法はある。空間の布で無駄になっている空間を広げられる魔法使いがいるそうだ。",
7025:"空間の布を探しに行ってくれるか？（レベル300以上のキャラクター）",
7027:"わかりました。（承諾）",
7028:"今は忙しくて手伝えません。（拒否）",
7029:"残念だ。倉庫を拡張したくなったら、いつでもまた来てくれ。（クエストがキャンセルされました）",
7030:"スカイシティ1階でアルクアモスを倒すと空間の布を手に入れるチャンスがある。空間の布を持ってくれば、魔法のバッグをもう一度大きくしてやろう。バッグの拡張は再接続後に有効になる。",
7801:"倉庫を拡張したいなら、旅の商人ゼロを探してください。",
7802:"ロストタワー7階に出現するデスナイトが落とす古代の彫像を旅の商人ゼロに渡すと、拡張された倉庫を入手できます。",
7803:"バッグの1回目の拡張をご希望なら、旅の商人ゼロを探してください。",
7804:"アトランスに出現するシルバーヴァルキリーが落とす魔法の布を旅の商人ゼロに渡すと、1回目のバッグ拡張を入手できます。拡張を確認するには再接続してください。",
7805:"バッグの2回目の拡張をご希望なら、旅の商人ゼロを探してください。",
7806:"スカイシティに出現するアルクアモスが落とす空間の布を旅の商人ゼロに渡すと、2回目のバッグ拡張を入手できます。拡張を確認するには再接続してください。",
7901:"商人ギルド取引拡張",
7902:"魔法の布",
7903:"空間の布",
},
"pl": {
7001:"Zarządzanie magazynem jest zawsze ważne. Żołd Strażników Bezpieczeństwa, teleporty między wioskami i ogromna liczba pustych magazynów … pilnie potrzebujemy nowego! Dlatego wpadłem na sprytny plan.",
7002:"Jaką metodę?",
7003:"Sprzedaję antyki bogaczom. Dla poszukiwaczy to zwykłe kamyki, lecz dla bogaczy mają wartość artystyczną. Tacy już są … tak właśnie zarabiam. Jeśli zechcesz pomóc, pozwolę ci korzystać z tego magazynu.",
7004:"Jak mogę ci pomóc?",
7005:"Przydzielę ci jedną komorę w nowym magazynie. Przynieś mi Starożytną Statuę, dobrze? (Postać od poziomu 50)",
7007:"Rozumiem. (Akceptuj)",
7008:"Jestem zbyt zajęty, by ci pomóc. (Odrzuć)",
7009:"Jaka szkoda. Jeśli zechcesz powiększyć magazyn, wróć do mnie w każdej chwili. (Misja anulowana)",
7010:"Pokonaj Rycerza Śmierci na piętrze 7 Wieży Zagubionych, aby zdobyć Starożytną Statuęprzynieś ją, a przydzielę ci nowy magazyn. Dostęp do magazynu zacznie działać po ponownym połączeniu.",
7011:"Wiesz, z czego zrobiony jest twój zwykły plecak? Z magicznej tkaniny. Dlatego poszukiwacze bez trudu dźwigają tyle ciężkiego ekwipunku. Skoro każdy ma ją jako zapas, jest wprost bezcenna. Mam z tobą pewien układ do zawarcia …",
7012:"Jaki układ masz na myśli?",
7013:"Z magiczną tkaniną zmieści się więcej w magicznym plecaku. Przy nieś magiczną tkaninę, a z resztek powiększę twój plecak, by pomieścił więcej przedmiotów.",
7015:"Proszę,przynieś mi więc magiczną tkaninę, dobrze? (Postać od poziomu 150)",
7017:"Rozumiem. (Akceptuj)",
7018:"Jestem zbyt zajęty, by ci pomóc. (Odrzuć)",
7019:"Jaka szkoda. Jeśli jesteś zainteresowany, wróć do mnie w każdej chwili. (Misja anulowana)",
7020:"Pokonaj Srebrną Walkirię na piętrze 3 Atlans, aby zdobyć magiczną tkaninę. Niełatwo ją zdobyć, lecz skoro magiczny plecak ma się powiększyć, trud się opłaci. Przynieś magiczną tkaninę. Magiczny plecak zacznie działać po ponownym połączeniu.",
7021:"Co cię tu sprowadza?",
7022:"Czy da się powiększyć magiczny plecak?",
7023:"Chcesz powiększyć magiczny plecak? To niełatwe, ale jest sposób. Podobno pewien mag potrafi za pomocą tkaniny przestrzeni rozszerzyć marnowane miejsce.",
7025:"Czy zechcesz odnaleźć tkaninę przestrzeni? (Postać od poziomu 300)",
7027:"Rozumiem. (Akceptuj)",
7028:"Jestem zbyt zajęty, by ci pomóc. (Odrzuć)",
7029:"Jaka szkoda. Jeśli zechcesz powiększyć magazyn, wróć do mnie w każdej chwili. (Misja anulowana)",
7030:"Pokonaj Alquamosa na piętrze 1 Niebiańskiego Miasta, aby zdobyć tkaninę przestrzeni. Przynieś ją, a jeszcze bardziej powiększę twój magiczny plecak. Rozszerzenie zacznie działać po ponownym połączeniu.",
7801:"Jeśli chcesz powiększyć magazyn, odszukaj wędrownego kupca Zero.",
7802:"Oddaj Starożytną Statuę, którą wypada Rycerz Śmierci z piętra 7 Wieży Zagubionych, wędrownemu kupcowi Zero, aby otrzymać powiększony magazyn.",
7803:"Aby dokonać pierwszego powiększenia plecaka, odszukaj wędrownego kupca Zero.",
7804:"Oddaj magiczną tkaninę, którą wypada Srebrna Walkiria z Atlans, wędrownemu kupcowi Zero, aby dokonać pierwszego powiększenia plecaka. Połącz się ponownie, aby je potwierdzić.",
7805:"Aby dokonać drugiego powiększenia plecaka, odszukaj wędrownego kupca Zero.",
7806:"Oddaj tkaninę przestrzeni, którą wypada Alquamos z Niebiańskiego Miasta, wędrownemu kupcowi Zero, aby dokonać drugiego powiększenia plecaka. Połącz się ponownie, aby je potwierdzić.",
7901:"Rozszerzenie handlu gildii kupieckiej",
7902:"Magiczna tkanina",
7903:"Tkanina przestrzeni",
},
"ru": {
7001:"Управление складом всегда важно. Жалованье Стражей Безопасности, телепорты между деревнями и огромное число пустых складов … срочно нужен новый склад! Поэтому я придумал хитрый план.",
7002:"Какой способ?",
7003:"Продавать антиквариат богачам. Для искателей приключений это невзрачные камни, а для богачей — художественная ценность. Богачи такие … вот так я и зарабатываю. Если поможешь, я разрешу тебе пользоваться тем складом.",
7004:"Чем я могу вам помочь?",
7005:"Я выделю тебе место в новом складе. Принеси мне Древнюю статую, хорошо? (Персонаж от уровня 50)",
7007:"Понятно. (Принять)",
7008:"Я сейчас слишком занят, чтобы помочь. (Отклонить)",
7009:"Жаль. Если захочешь расширить склад, приходи в любое время. (Задание отменено)",
7010:"Победи Рыцаря Смерти на 7-м этаже Башни Потерянных, чтобы получить Древнюю статую. Принеси её — и я выделю тебе новый склад. Доступ к складу вступит в силу после переподключения.",
7011:"Знаешь, из чего сделан т обычный рюкзак? Из магической ткани. Поэтому искатели приключений без труда носят много тяжёлого снаряжения. Раз она есть у каждого как припас, она очень ценна. На самом деле, я хочу заключить с тобой сделку …",
7012:"О какой сделке речь?",
7013:"С магической тканью в магический рюкзак влезет больше вещей. Принеси магическую ткань — и я из остатков увеличу твой рюкзак, чтобы в него помещалось больше.",
7015:"Так что принеси мне магическую ткань, хорошо? (Персонаж от уровня 150)",
7017:"Понятно. (Принять)",
7018:"Я сейчас слишком занят, чтобы помочь. (Отклонить)",
7019:"Жаль. Если заинтересован, приходи в любое время. (Задание отменено)",
7020:"Победи Серебряную валькирию на 3-м этаже Атланса, чтобы получить магическую ткань. Достать её непросто, но если магический рюкзак увеличится, труды окупятся. Принеси магическую ткань. Магический рюкзак вступит в силу после переподключения.",
7021:"Что тебя привело?",
7022:"Есть ли способ увеличить магический рюкзак?",
7023:"Хочешь увеличить магический рюкзак? Это непросто, но способ есть. Говорят, один маг может с помощью ткани пространства расширить впустую пот раченное место.",
7025:"Согласен отправиться на поиски ткани пространства? (Персонаж от уровня 300)",
7027:"Понятно. (Принять)",
7028:"Я сейчас слишком занят, чтобы помочь. (Отклонить)",
7029:"Жаль. Если захочешь расширить склад, приходи в любое время. (Задание отменено)",
7030:"Победи Алькуамоса на 1-м этаже Небесного города, чтобы получить ткань пространства. Принеси её — и я ещё раз увеличу твой магический рюкзак. Расширение вступит в силу после переподключения.",
7801:"Если хочешь расширить склад, найди странствующего торговца Зеро.",
7802:"Отдай Древнюю статую, выпадающую с Рыцаря Смерти на 7-м этаже Башни Потерянных, странствующему торговцу Зеро, чтобы получить расширенный склад.",
7803:"Для первого расширения рюкзака найди странствующего торговца Зеро.",
7804:"Отдай магическую ткань, выпадающую с Серебряной валькирии в Атлансе, странствующему торговцу Зеро, чтобы получить первое расширение рюкзака. Для подтверждения переподключись.",
7805:"Для второго расширения рюкзака найди странствующего торговца Зеро.",
7806:"Отдай ткань пространства, выпадающую с Алькуамоса в Небесном городе, странствующему торговцу Зеро, чтобы получить второе расширение рюкзака. Для подтверждения переподключись.",
7901:"Расширение торговли гильдии торговцев",
7902:"Магическая ткань",
7903:"Ткань пространства",
},
"tl": {
7001:"Laging mahalaga ang pamamahala ng bodega. Sahod ng mga Safety Guard, teleport sa pagitan ng mga bayan, at ang napakaraming bakanteng bodega … kailangan na natin ng bagong bodega! Kaya nakaisip ako ng matalinong plano.",
7002:"Anong paraan?",
7003:"Magbenta ng antigong gamit sa mayayaman. Sa mga adventurer ay bato lang ito, pero sa mayayaman ay may artistikong halaga. Ganyan sila … ganyan ako kumita. Kung tutulong ka, papayagan kitang gamitin ang bodegang iyon.",
7004:"Paano kita matutulungan?",
7005:"Bibigyan kita ng espasyo sa bagong bodega. Dalhan mo ako ng Sinaunang Estatwa, okay? (Karakter level 50 pataas)",
7007:"Naiintindihan ko. (Tanggapin)",
7008:"Masyado akong abala para tumulong ngayon. (Tanggihan)",
7009:"Sayang naman. Kung gusto mong palawakin ang bodega, bumalik ka sa akin anumang oras. (Nakansela ang misyon)",
7010:"Talunin ang Death Knight sa ika-7 palapag ng Lost Tower para makakuha ng Sinaunang Estatwa. Dalhan mo ako nito at bibigyan kita ng bagong bodega. Magkakabisa ang access pagkatapos mag-reconnect.",
7011:"Alam mo ba kung saan gawa ang karaniwang bag mo? Sa mahiwagang tela. Kaya nakakadala ang mga adventurer ng maraming mabibigat na gamit. Dahil mayroon nito ang lahat bilang suplay, ito ay mahalaga. Sa totoo lang, may gusto akong makipagkasundo sa iyo …",
7012:"Anong kasunduan ang ibig mong sabihin?",
7013:"Sa mahiwagang tela, mas maraming mailalagay sa mahiwagang bag. Dalhan mo ako ng mahiwagang tela at palalakihin ko ang bag mo gamit ang natirang tela para mas marami ang mailagay.",
7015:"Kaya dalhan mo ako ng mahiwagang tela, okay? (Karakter level 150 pataas)",
7017:"Naiintindihan ko. (Tanggapin)",
7018:"Masyado akong abala para tumulong ngayon. (Tanggihan)",
7019:"Sayang naman. Kung interesado ka, bumalik ka sa akin anumang oras. (Nakansela ang misyon)",
7020:"Talunin ang Silver Valkyrie sa ika-3 palapag ng Atlans para makakuha ng mahiwagang tela. Hindi madaling makuha, pero kung lalaki ang mahiwagang bag, sulit ang pagod. Dalhan mo ako ng mahiwagang tela. Magkakabisa ang mahiwagang bag pagkatapos mag-reconnect.",
7021:"Bakit ka naparito?",
7022:"May paraan ba para palakihin ang mahiwagang bag?",
7023:"Gusto mong palakihin ang mahiwagang bag? Hindi madali, pero may paraan. May isang mangkukulam na kayang palawakin ang nasasayang na espasyo gamit ang telang espasyo.",
7025:"Handa ka bang hanapin ang telang espasyo? (Karakter level 300 pataas)",
7027:"Naiintindihan ko. (Tanggapin)",
7028:"Masyado akong abala para tumulong ngayon. (Tanggihan)",
7029:"Sayang naman. Kung gusto mong palawakin ang bodega, bumalik ka sa akin anumang oras. (Nakansela ang misyon)",
7030:"Talunin ang Alquamos sa ika-1 palapag ng Sky City para makakuha ng telang espasyo. Dalhan mo ako nito at lalo kong palalakihin ang mahiwagang bag mo. Magkakabisa ang pagpapalaki pagkatapos mag-reconnect.",
7801:"Kung gusto mong palawakin ang bodega, hanapin ang lagalag na mangangalakal na si Zero.",
7802:"Ibigay ang Sinaunang Estatwa na ibinabagsak ng Death Knight sa ika-7 palapag ng Lost Tower sa lagalag na mangangalakal na si Zero para makuha ang pinalawak na bodega.",
7803:"Para sa unang pagpapalaki ng bag, hanapin ang lagalag na mangangalakal na si Zero.",
7804:"Ibigay ang mahiwagang tela na ibinabagsak ng Silver Valkyrie sa Atlans sa lagalag na mangangalakal na si Zero para makuha ang unang pagpapalaki ng bag. Mag-reconnect para makumpirma.",
7805:"Para sa ikalawang pagpapalaki ng bag, hanapin ang lagalag na mangangalakal na si Zero.",
7806:"Ibigay ang telang espasyo na ibinabagsak ng Alquamos sa Sky City sa lagalag na mangangalakal na si Zero para makuha ang ikalawang pagpapalaki ng bag. Mag-reconnect para makumpirma.",
7901:"Pagpapalawak ng Kalakalan ng Merchant Guild",
7902:"Mahiwagang Tela",
7903:"Telang Espasyo",
},
"uk": {
7001:"Керування складом завжди важливе. Платня Стражів Безпеки, телепорти між селами та величезна кількість порожніх складів … терміново потрібен новий склад! Тому я вигадав хитрий план.",
7002:"Який спосіб?",
7003:"Продавати антикваріат багатіям. Для шукачів пригод це непоказні камінці, а для багатіїв — мистецька цінність. Багатії такі … отак я й заробляю. Якщо допоможеш, я дозволю тобі користуватися тим складом.",
7004:"Чим я можу вам допомогти?",
7005:"Я виділю тобі місце в новому складі. Принеси мені Стару статую, добре? (Персонаж від рівня 50)",
7007:"Зрозуміло. (Прийняти)",
7008:"Я зараз надто зайнятий, щоб допомогти. (Відхилити)",
7009:"Шкода. Якщо захочеш розширити склад, приходь будь-коли. (Завдання скасовано)",
7010:"Перемож Лицаря Смерті на 7-му поверсі Вежі Загублених, щоб отримати Стару статую. Принеси її — і я виділю тобі новий склад. Доступ до складу почне діяти після перепідключення.",
7011:"Знаєш, із чого зроблений твій звичайний наплічник? З магічної тканини. Тому шукачі пригод без труднощів носять багато важкого спорядження. Оскільки вона є в кожного як припас, вона дуже цінна. Насправді, я хочу укласти з тобою угоду …",
7012:"Про яку угоду йдеться?",
7013:"З магічною тканиною в магічний наплічник увійде більше речей. Принеси магічну тканину — і я з решток збільшу твій наплічник, щоб у нього поміщалося більше.",
7015:"Тож принеси мені магічну тканину, добре? (Персонаж від рівня 150)",
7017:"Зрозуміло. (Прийняти)",
7018:"Я зараз надто зайнятий, щоб допомогти. (Відхилити)",
7019:"Шкода. Якщо зацікавлений, приходь будь-коли. (Завдання скасовано)",
7020:"Перемож Срібну валькірію на 3-му поверсі Атланса, щоб отримати магічну тканину. Дістати її непросто, але якщо магічний наплічник збільшиться, праця окупиться. Принеси магічну тканину. Магічний наплічник почне діяти після перепідключення.",
7021:"Що тебе привело?",
7022:"Чи є спосіб збільшити магічний наплічник?",
7023:"Хочеш збільшити магічний наплічник? Це непросто, але спосіб є. Кажуть, один маг може за допомогою тканини простору розширити змарноване місце.",
7025:"Чи згоден ти вирушити на пошуки тканини простору? (Персонаж від рівня 300)",
7027:"Зрозуміло. (Прийняти)",
7028:"Я зараз надто зайнятий, щоб допомогти. (Відхилити)",
7029:"Шкода. Якщо захочеш розширити склад, приходь будь-коли. (Завдання скасовано)",
7030:"Перемож Алькуамоса на 1-му поверсі Небесного міста, щоб отримати тканину простору. Принеси її — і я ще раз збільшу твій магічний наплічник. Розширення почне діяти після перепідключення.",
7801:"Якщо хочеш розширити склад, знайди мандрівного торговця Зеро.",
7802:"Віддай Стару статую, що випадає з Лицаря Смерті на 7-му поверсі Вежі Загублених, мандрівному торговцю Зеро, щоб отримати розширений склад.",
7803:"Для першого розширення наплічника знайди мандрівного торговця Зеро.",
7804:"Віддай магічну тканину, що випадає зі Срібної валькірії в Атлансі, мандрівному торговцю Зеро, щоб отримати перше розширення наплічника. Для підтвердження перепідключися.",
7805:"Для другого розширення наплічника знайди мандрівного торговця Зеро.",
7806:"Віддай тканину простору, що випадає з Алькуамоса в Небесному місті, мандрівному торговцю Зеро, щоб отримати друге розширення наплічника. Для підтвердження перепідключися.",
7901:"Розширення торгівлі гільдії торговців",
7902:"Магічна тканина",
7903:"Тканина простору",
},
}
# sanity: all locales have all 34 ids
ids=[7001,7002,7003,7004,7005,7007,7008,7009,7010,7011,7012,7013,7015,7017,7018,7019,7020,7021,7022,7023,7025,7027,7028,7029,7030,7801,7802,7803,7804,7805,7806,7901,7902,7903]
for L,d in T.items():
    miss=[i for i in ids if i not in d]
    assert not miss,(L,miss)
    # no replacement char
    for i,v in d.items(): assert '�' not in v,(L,i)
json.dump({L:{str(k):v for k,v in d.items()} for L,d in T.items()},
          open(os.path.join(W, 'kr_gap_translations.json'),'w',encoding='utf-8'),
          ensure_ascii=False,indent=1)
print('wrote kr_gap_translations.json for',len(T),'locales,',len(ids),'records each')
