#!/usr/bin/env python3
# -*- coding: utf-8 -*-
import os as _os
W = _os.path.dirname(_os.path.abspath(__file__))
"""Translate MU Online questwords from English to Polish.
Uses a comprehensive manual translation dictionary for all 692 strings.
"""
import json
import re
import os

INPUT = os.path.join(W, 'in_data', 'pl', 'g1.json')
OUTPUT = os.path.join(W, 'out_data', 'pl', 'g1.json')

with open(INPUT, "r", encoding="utf-8") as f:
    data = json.load(f)

strings = data["strings"]
print(f"Loaded {len(strings)} strings")

# ============================================================
# Translation dictionary: id -> Polish text
# Conventions:
# - "ty" form (panujący w polskich serwerach MU)
# - Proper names kept as-is per MU tradition (Dark Knight, Fairy Elf, Lorencia, Noria, Devias, etc.)
# - Monster/item names kept English (standard on Polish MU servers)
# - Semicolons preserved exactly
# - Printf tokens preserved
# ============================================================

TR = {
    23: "'Shadow Phantom Soldier' szuka poszukiwacza przygód, który wykona zadania dla oddziału Shadow Phantom. Idź do niego i się dowiedz.",
    24: "'Shadow Phantom Soldier' szuka poszukiwacza przygód, który wykona misje oddziału Shadow Phantom. Idź do niego i się dowiedz.",
    27: "...Dodatkowy prezent, jeśli odpowiem poprawnie na wszystkie pytania?",
    28: "...W końcu samouczek się skończył!",
    29: "...Znalezienie kupca jest trudniejsze, niż myślałem.",
    30: "...Hmm. Nie wiedziałem, że coś takiego istnieje.",
    31: "...Jak to zrobić?",
    32: "...Widać, że warto znać wielu NPC.",
    33: "...Chcę się dowiedzieć o...",
    34: "...Jestem wzruszony, że królowa wydała takie rozkazy.",
    35: "...Czy to prawda? A potem chciałbym się dowiedzieć o...",
    36: "...Shadow Phantom?;Strażnicy królowej?",
    37: "...Ataki umiejętnościami?",
    38: "...To fantastyczne!",
    39: "...Ikona obok slotów numer 1, 2, 3, 4 i 5....",
    40: "...Królowa jest bardzo troskliwa!",
    41: "...To nic trudnego. Ale chciałbym się dowiedzieć więcej....",
    42: "...To jest Elveland, królestwo Summonerów! Więc tutaj zaczyna się moja przygoda.;Jakże ekscytujące!",
    43: "...To jest Lorencia, królestwo Dark Wizardów i Dark Knightów! Więc tutaj zaczyna się moja przygoda.;Doskonale! Moja przygoda się zaczyna!",
    44: "...To jest Noria, królestwo Elfów! Więc tutaj zaczyna się moja przygoda.;Jakże ekscytujące!",
    45: "...Town Portal Scroll?",
    46: "...Uniria?",
    47: "...Szepty...",
    48: "...handel...",
    50: "1 milion Zen za darmową rejestrację najemnika i 500 000 Zen jako kaucja. Czy zarejestrujesz się jako wolny najemnik już teraz? (Lv. 350 - Master Level)",
    51: "Wystarczy 10 maczug od Burnt Murdererów w Vulcanus. Pamiętaj, że 'Heroes' wśród Burnt Murdererów nie upuszczają tego przedmiotu. Wróć do mnie z 10 maczugami Burnt Murderer, by otrzymać nagrodę.",
    74: "Grupa ścigająca zapieczętowany kamień używa mechanicznych wojowników do atakowania naszych sił w Kanturu Ruins. Proszę pokonać Splinter Wolves, które sprawiają najwięcej kłopotów.",
    75: "Wzmocnienie na obrażenia i obronę? Brzmi świetnie!",
    76: "Duch walki nie przynosi korzyści bohaterowi. (Odrzuć)",
    77: "Grupa potworów pojawiła się na Poziomach 2 i 3 Lochu i atakuje nasz zwiadowczy oddział. Chciałbym poprosić cię, wędrowcze, o wytępienie tych potworów. Czy przyjmiesz to zadanie? (Poziom 131-140)",
    78: "Bohater to w końcu tylko człowiek, energia szaleństwa…",
    79: "Bohater nie zna słowa 'poddaję się'. Przyjmuję. (Przyjmij)",
    80: "Bohater bez silnego umysłu to niewiele więcej niż trup. Kontynuuj wyzwania aż do samego końca.",
    81: "Chwila nieuwagi może oznaczać katastrofę nawet dla najbardziej doświadczonych wojowników. Mam nadzieję, że pozostaniesz oddany treningowi przez cały czas. Jestem odpowiedzialny za wydawanie zaproszeń do Devil Square – areny, gdzie możesz przejść najwięcej treningu w najkrótszym czasie. Czy chcesz usłyszeć więcej? (Wszystkie postacie: Master Level)",
    83: "Według plotek grupa potworów ściga zapieczętowany kamień. Plotki mówią też, że te potwory to prawdopodobnie Ghost Napinowie, ale nikt ich nie widział na własne oczy. Może to tylko plotka, ale czy wyeliminujesz tych Ghost Napinów i ochronisz zapieczętowany kamień?",
    84: "Oddział poszukiwawczy wysłany do Aidy donosi, że liczba Death Trees gwałtownie rośnie. Idź do Aidy i wyeliminuj 50 Death Trees.",
    85: "Oddział poszukiwawczy wysłany do Aidy donosi, że liczba Death Trees gwałtownie rośnie. Idź do Aidy i wyeliminuj 50 Death Trees.",
    86: "Szlak szaleństwa",
    87: "Samouczek?;Nie mogę się doczekać!",
    88: "Mądra decyzja. Chaos Castle to pole bitwy stworzone przez Lugarda, boga świata niebios, i Secrarium, boga świata podziemnego, dla zachowania równości dobra i zła na tym świecie. Jednakże podróżnicy zaczęli przybywać do Chaos Castle i walczyć po stronie Lugarda, przechylając szalę na niekorzyść Secrarium.",
    89: "Mądra decyzja. Pokonaj 50 Cursed Liches w Elveland (Obszar 2) i 50 Yetis w Devias (Obszar 2). Zrób to, a otrzymasz 60 000 pkt EXP, 1 500 000 Zenów i 1 Jewel of Chaos jako nagrodę od Shadow Phantom Soldier.",
    90: "Mądra decyzja. Pokonaj 50 Totem Golemów w Elveland (Obszar 3) i 50 Elite Yetis w Devias (Obszar 3). Zrób to, a otrzymasz 60 000 pkt EXP, 1 500 000 Zenów i 1 Jewel of Chaos jako nagrodę od Shadow Phantom Soldier.",
    91: "Mądra decyzja. Daj mi 1 milion Zenów, a od razu cię zapiszę.",
    92: "Mądra decyzja. Test, o którym myślę, polega na wejściu do Devil Square Level 2 i zdobyciu 100 punktów. Zrób to, a dam ci 200 000 Zenów jako nagrodę. Jednak dotyczy to tylko Devil Square Level 2.",
    93: "Mądra decyzja. Test, o którym myślę, polega na wejściu do Devil Square Level 3 i zdobyciu 130 punktów. Zrób to pomyślnie, a dam ci 800 000 pkt EXP i 500 000 Zenów jako nagrodę. Jednak dotyczy to tylko Devil Square Level 3.",
    94: "Mądra decyzja. Test, o którym myślę, polega na wejściu do Devil Square Level 4 i zdobyciu 160 punktów. Zrób to pomyślnie, a dam ci 1 Jewel of Chaos i 500 000 Zenów jako nagrodę. Jednak dotyczy to tylko Devil Square Level 4.",
    95: "Mądra decyzja. Test, o którym myślę, polega na wejściu do Devil Square Level 5 i zdobyciu 190 punktów. Zrób to pomyślnie, a dam ci 1 Jewel of Soul jako nagrodę. Jednak dotyczy to tylko Devil Square Level 5.",
    96: "Mądra decyzja. Test, o którym myślę, polega na wejściu do Devil Square Level 6 i zdobyciu 210 punktów. Zrób to pomyślnie, a dam ci 1 Jewel of Harmony jako nagrodę. Jednak dotyczy to tylko Devil Square Level 6.",
    97: "Mądra decyzja. Test, o którym myślę, polega na wejściu do Devil Square Level 7 i zdobyciu 240 punktów. Zrób to pomyślnie, a dam ci 2 Jewele of Soul jako nagrodę. Jednak dotyczy to tylko Devil Square Level 7.",
    98: "Mądra decyzja. Spróbuj szczęścia w Blood Castle Level 1. Zniszcz przynajmniej bramę zamku, a dam ci 100 000 Zenów jako nagrodę. Jednak dotyczy to tylko Blood Castle Level 1.",
    99: "Mądra decyzja. Spróbuj szczęścia w Blood Castle Level 2. Zniszcz przynajmniej bramę zamku, a dam ci 200 000 Zenów jako nagrodę. Jednak dotyczy to tylko Blood Castle Level 2.",
    100: "Mądra decyzja. Spróbuj szczęścia w Blood Castle Level 3. Zniszcz przynajmniej bramę zamku, a dam ci 800 000 pkt EXP i 500 000 Zenów jako nagrodę. Jednak dotyczy to tylko Blood Castle Level 3.",
    101: "Mądra decyzja. Spróbuj szczęścia w Blood Castle Level 4. Zniszcz bramę zamku, a dam ci 1 Jewel of Chaos i 500 000 Zenów jako nagrodę. Jednak dotyczy to tylko Blood Castle Level 4.",
    102: "Mądra decyzja. Spróbuj szczęścia w Blood Castle Level 5. Zniszcz bramę zamku, a dam ci 1 Jewel of Soul jako nagrodę. Jednak dotyczy to tylko Blood Castle Level 5.",
    103: "Mądra decyzja. Spróbuj szczęścia w Blood Castle Level 6. Zniszcz przynajmniej bramę zamku, a dam ci 1 Jewel of Harmony jako nagrodę. Jednak dotyczy to tylko Blood Castle Level 6.",
    104: "Mądra decyzja. Spróbuj szczęścia w Blood Castle Level 7. Zniszcz przynajmniej bramę zamku, a dam ci 2 Jewele of Soul jako nagrodę. Jednak dotyczy to tylko Blood Castle Level 7.",
    105: "Mądra decyzja. Spróbuj szczęścia w Blood Castle Level 8. Zniszcz przynajmniej bramę zamku, a dam ci 2 Jewele of Bless jako nagrodę. Jednak dotyczy to tylko Blood Castle Level 8.",
    106: "Mądra decyzja. Watchers of Kundun mówią, że potrzebują 'Zagubionej Mapy', by wejść do bariery Kunduna, ale coraz trudniej ją zdobyć. Proszę przynieś mi 2 strony 'Zagubionej Mapy Lv. 4', a dam ci zadanie z pokaźną nagrodą.",
    107: "Mądra decyzja. Watchers of Kundun mówią, że potrzebują 'Zagubionej Mapy', by wejść do bariery Kunduna, ale coraz trudniej ją zdobyć. Proszę przynieś mi 3 strony 'Zagubionej Mapy Lv. 3', a dam ci zadanie z pokaźną nagrodą.",
    108: "Dostarczono ci błędny List Prośby. Proszę porozmawiaj z Mercenary Guild Manager Tercia.",
    118: "Przyjmij zadanie gens.",
    119: "Przyjmij zadanie.",
    120: "Przyjmij zadanie.",
    121: "Według naszych dochodzeń Necroni i Death Centurionowie absorbują energię szaleństwa, gdy zapieczętowany kamień odpoczywa. Proszę pozbądź się 30 Necronów i 20 Death Centurionów, by powstrzymać rozprzestrzenianie się energii szaleństwa. Przygotuję nagrodę, gdy skończysz tę robotę. (Można w drużynie)",
    122: "Według najnowszych informacji, Blood Assassini zostali wysłani, by zamordować kluczowe postacie Gens. Wyeliminuj 50 Blood Assassinów i chroń kluczowe postacie Gens.",
    123: "Zbieraj punkty EXP, by awansować na wyższy poziom. Możesz sprawdzić, ile punktów brakuje ci do następnego poziomu, otwierając okno Statystyk Postaci lub sprawdzając pasek EXP na dole ekranu.",
    130: "Awans Oddziału Zwiadowczego (1)",
    131: "Awans Oddziału Zwiadowczego (2)",
    132: "Awans Oddziału Zwiadowczego (3)",
    133: "Awans oddziału zwiadowczego....",
    134: "Natarcie na Latający Zamek...",
    136: "W końcu potrzebuję nowego ekwipunku. Czy powinienem spróbować?",
    137: "Po nauczeniu się umiejętności ze zwoju, możesz ją aktywować, przypisując ją w oknie Umiejętności.",
    138: "Po nauczeniu się umiejętności ze zwoju, możesz ją aktywować, przypisując ją w oknie Umiejętności.;Widzisz ponumerowane sloty na dole, na środku ekranu? Kliknij ikonę zaznaczoną na zielono, po prawej stronie slotu piątego.",
    139: "Po nauczeniu się umiejętności z kuli, możesz ją aktywować, przypisując ją w oknie Umiejętności.",
    140: "Po nauczeniu się umiejętności z kuli, możesz ją aktywować, przypisując ją w oknie Umiejętności.;Widzisz ponumerowane sloty na dole, na środku ekranu? Kliknij ikonę zaznaczoną na zielono, po prawej stronie slotu piątego.",
    141: "Po otrzymaniu wzmocnienia zobaczysz ikonę w lewym górnym rogu ekranu, niebieski efekt świetlny wokół postaci oraz będziesz miał godzinę zwiększonych obrażeń i obrony.",
    142: "Elfowie Zręczności, dla których priorytetem jest obrona, mogą uczyć się umiejętności poprzez wyposażanie broni, a Elfowie Energii, dla których priorytetem jest magia – poprzez kupowanie kul.",
    148: "Ach, muszę cofnąć się daleko w czasie, by to wyjaśnić.;Runedil, dawna królowa Elfów, była zrozpaczona stratą wszystkich nowych wojowników imperium MU, którzy oddali życie w ciągłych wojnach.",
    149: "Ach, w końcu przyszedłeś. Zadanie polega na zdobyciu dla mnie ekwipunku na zaopatrzenie wojenne. Nie ma bardziej dochodowego interesu niż dostawy wojenne. Nie jest już tak jak dawniej, ale wystarcza na stabilny dochód. Szczególnie drogie są Zbroja Tantalosa i Maczuga Burnt Murderera. (Lv. 350 - 400)",
    150: "Ach, odpowiedziałeś błędnie. Zabierz przedmioty, składniki i pieniądze potrzebne do łączenia do Goblina w Nori, by stworzyć nowy przedmiot. Spróbuj przynajmniej raz. Przejdźmy do następnego pytania.",
    151: "Ach, odpowiedziałeś błędnie. By handlować, naciśnij D i wybierz Handluj lub stanę twarzą do postaci i wpisz '/trade' w oknie czatu. Przejdźmy do następnego pytania.",
    152: "Ach, odpowiedziałeś błędnie. Wpisz '/Request off' w oknie czatu, by odrzucać propozycje drużyny. By znów zacząć je przyjmować, wpisz '/Request on' w oknie czatu. Przejdźmy do następnego pytania.",
    153: "Ach, odpowiedziałeś błędnie. Użyj M, by dowiedzieć się i podróżować do dostępnych obszarów z łatwością. Odkrywanie obszarów odpowiednich dla twojego poziomu i polowanie tam też może być bardzo fajne.;Przejdźmy do następnego pytania.",
    154: "Ach, odpowiedziałeś błędnie. Gdy chcesz porozmawiać z przyjacielem i znasz jego ID, lub gdy chcesz przekazać prywatne wiadomości, wysyłaj szeptu używając Tab z okna czatu. Przejdźmy do następnego pytania.",
    155: "Ach, odpowiedziałeś błędnie.; Będziesz mógł z łatwością naprawiać swój ekwipunek używając przycisku Napraw w oknie Ekwipunku, gdy osiągniesz poziom 50. Jednakże jest to droższe niż naprawianie u NPC.;Przejdźmy do następnego pytania.",
    156: "Ach. Więc o to chodziło....",
    163: "Dobrze, przyjmuję. (Przyjmij)",
    164: "Dobrze. (Przyjmij)",
    168: "Alquamosy to najbardziej kłopotliwe stworzenia w Icarus – ścieżce prowadzącej do Latającego Zamku. Gwiezdny Pył używany przez Alquamosy okazuje się dewastujący dla naszego oddziału zwiadowczego. Czy wyeliminujesz tych Alquamosów, by umożliwić naszemu oddziałowi awans? (Poziom 245-249)",
    169: "Świetnie! Zacznijmy samouczek.",
    170: "Dobrze. Dam z siebie wszystko.",
    171: "Poza tym, gdy znajdziesz się daleko od miasta lub zostaniesz zaskoczony podczas polowania, Town Portal Scroll może się bardzo przydać. Czy umiesz go używać?",
    194: "Jabłka można kupić u handlarzy mikstur. W Lorencji szukaj Potion Girl Amy, która stoi za mostem (128,85). W Elveland szukaj Silvii, która jest w kierunku 1-tej od środka rynku (45,227). W Nori szukaj Elf Lala, która jest lekko na północ od centrum miasta (172,124).",
    199: "Czy znasz ukryty teren treningowy zwany Devil Square? To świetne miejsce na rozwój swoich umiejętności. Może wysłuchasz, co mam do powiedzenia, a potem zdecydujesz? (Postać podstawowa: Poziom 131-180, Postać zaawansowana: Poziom 111-160)",
    200: "Czy znasz ukryty teren treningowy zwany Devil Square? To świetne miejsce na rozwój swoich umiejętności. Może wysłuchasz, co mam do powiedzenia, a potem zdecydujesz? (Postać podstawowa: Poziom 15-130, Postać zaawansowana: Poziom 10-110)",
    212: "Im silniejszy klan, tym silniejszy ty. Wróć proszę, jeśli zmienisz zdanie. (Zadanie zostało anulowane.)",
    220: "Zapytaj o Gens Duprian.",
    221: "Zapytaj o Gens Vanert.",
    222: "Zapytaj o spór gens.",
    224: "Natarcie Burning Lava Giantów",
    225: "W Devias 2 napotkasz Hommerdy błąkające się i wrzeszczące plugawym śmiechem. Pokonaj 30 Hommerdów i wróć do mnie po nagrodę.",
    226: "W Devias 2 napotkasz Yetis pokrytych białym futrem. Pokonaj 30 Yetis i wróć do mnie po nagrodę.",
    227: "W Devias 2 napotkasz Assasynów dzierżących ostrza. Pokonaj 30 Assasynów i wróć do mnie po nagrodę.",
    228: "W Devias 2 napotkasz półprzezroczyste Lódowe Stwory. Pokonaj 25 Lódowych Stworów i wróć do mnie po nagrodę.",
    229: "W Devias 2 napotkasz półprzezroczyste Lódowe Stwory. Pokonaj 30 Lódowych Stworów i wróć do mnie po nagrodę.",
    230: "W Devias 4 napotkasz wrzeszczące lodowe stworzenia. Pokonaj 3 Ice Queens i wróć do mnie po nagrodę.",
    231: "Na Poziomie 1 Lochu napotkasz Larwy nękające podróżnych przy wejściu. Pokonaj 40 Larw i wróć do mnie po nagrodę.",
    232: "Na Poziomie 1 Lochu napotkasz jednookich olbrzymów niosących topory, zwanych Cyklopami. Pokonaj 40 Cyklopów i wróć do mnie po nagrodę.",
    233: "Na Poziomie 1 Lochu napotkasz jednookich olbrzymów niosących topory, zwanych Cyklopami. Pokonaj 50 Cyklopów i wróć do mnie po nagrodę.",
    234: "Na Poziomie 2 Lochu napotkasz Hell Houndy używające ostrej magii. Pokonaj 50 Hell Pająków i wróć do mnie po nagrodę.",
    235: "Na Poziomie 2 Lochu napotkasz Szkieletowych Łuczników ukrywających się i strzelających strzałami. Pokonaj 50 Szkieletowych Łuczników i wróć do mnie po nagrodę.",
    236: "Na Poziomie 2 Lochu napotkasz Thunder Liches używające magii piorunów. Pokonaj 50 Thunder Liches i wróć do mnie po nagrodę.",
    237: "Na Poziomie 2 Lochu napotkasz Hell Houndy śliniące się jadem. Pokonaj 50 Hell Houndów i wróć do mnie po nagrodę.",
    238: "Na Poziomie 2 Lochu napotkasz Poison Bull Fighterów śliniących się jadem. Pokonaj 50 Poison Bull Fighterów i wróć do mnie po nagrodę.",
    239: "Na Poziomie 3 Lochu napotkasz potwory-przewodniki zwane Gorgonami. Pokonaj 15 Gorgonów i wróć do mnie po nagrodę.",
    240: "Na Poziomach 2 i 3 Lochu napotkasz Dark Knightów rzucających ciemność na swojej drodze. Pokonaj 50 Dark Knightów i wróć do mnie po nagrodę.",
    241: "W Elveland 2 napotkasz Cursed Liches dzierżące płonącą laskę. Pokonaj 50 Cursed Liches i wróć do mnie po nagrodę.",
    242: "W Elveland 3 (179, 81) napotkasz plugaste, owłosione stworzenia. Pokonaj 50 Grizzliów i wróć do mnie po nagrodę.",
    243: "W Elveland 3 (203, 37) napotkasz dowódców plugawych, owłosionych stworzeń zwanych Grizzliami. Pokonaj 50 Captain Grizzliów i wróć do mnie po nagrodę.",
    244: "W Elveland 3 napotkasz Totem Golemy narodzone z totemów. Pokonaj 50 Totem Golemów i wróć do mnie po nagrodę.",
    245: "W Icarus napotkasz Mega Crusty, które są jeszcze bardziej przerażające niż Alquamosy. Pokonaj 80 Mega Crustów i wróć do mnie po nagrodę.",
    246: "W Icarus napotkasz Queen Rainier, które maskują swoją śmiercionośną aurę pięknem. Pokonaj 80 Queen Rainier i wróć do mnie po nagrodę.",
    247: "W Icarus napotkasz Alquamosy niosące gwiezdny pył. Pokonaj 80 Alquamosów i wróć do mnie po nagrodę.",
    248: "W Tarkan 1 napotkasz Bloody Wolves i ich zapach śmierci. Pokonaj 60 Bloody Wolves i wróć do mnie po nagrodę.",
    249: "W Tarkan 1 napotkasz olbrzymich Mutantów dzierżących topory. Pokonaj 60 Mutantów i wróć do mnie po nagrodę.",
    252: "Na Poziomie 1 Lost Tower napotkasz Cienie, które są uosobieniem złej woli. Pokonaj 50 Cieni i wróć do mnie po nagrodę.",
    253: "Na Poziomie 7 Lost Tower napotkasz Balrogi dzierżące ogromne kosy i strzegące wejścia. Pokonaj 15 Balrogów i wróć do mnie po nagrodę.",
    254: "Na Poziomie 7 Lost Tower napotkasz Death Gorgony, które stały się silniejsze przez śmierć. Pokonaj 60 Death Gorgonów i wróć do mnie po nagrodę.",
    255: "Na Poziomach 1 i 2 Lost Tower napotkasz Poison Shadows – plujące jadem uosobienia złej woli. Pokonaj 50 Poison Shadows i wróć do mnie po nagrodę.",
    256: "Na Poziomach 2 i 3 Lost Tower napotkasz zepsute istoty znane jako Cursed Wizardzy. Pokonaj 50 Cursed Wizardów i wróć do mnie po nagrodę.",
    257: "Na Poziomach 3 i 4 Lost Tower napotkasz Death Krowy i ich chmurę złej energii. Pokonaj 50 Death Krów i wróć do mnie po nagrodę.",
    258: "Na Poziomach 5 i 6 Lost Tower napotkasz Death Knightów, którzy zrodzili się ze zła. Pokonaj 50 Death Knightów i wróć do mnie po nagrodę.",
    259: "Na Poziomach 5 i 6 Lost Tower napotkasz Death Knightów, którzy zrodzili się ze zła. Pokonaj 60 Death Knightów i wróć do mnie po nagrodę.",
    273: "Atak na Korpus Dostawczy!",
    320: "Bariery zainstalowane w regionach, gdzie potwory często się mobilizują, są atakowane. Musimy nauczyć te potwory posłuszeństwa, zabijając ich przełożonych. Czy przyjmiesz to zadanie? (Poziom 198-201)",
    324: "Bądź ostatnim ocalałym w Chaos Castle, dostarcz broń Archaniołowi w Blood Castle i przetrwaj do końca Devil Square. Ukończ wszystkie trzy i wróć do Phantom Soldier, by otrzymać nagrodę.",
    326: "Beam Knightowie coś knują w Tarkan. Idź na poziom 2 Tarkan i wytrop 100 Beam Knightów. Gdy to zrobisz, przyjdź do mnie po Devil's Invitation + 5 jako nagrodę. To silni przeciwnicy – powinieneś na nie polować z pomocą innych.",
    331: "Przed atakiem na magazyn zaopatrzeniowy planujemy najpierw pokonać potwory go strzegące. Gdy te potwory zostaną załatwione, oddział zwiadowczy zajmie się szturmem na magazyn. Czy przyjmiesz to zadanie? (Poziom 56-65)",
    346: "Lepiej chwycić szansę, niż żałować. Cóż, wróć później, jeśli zmienisz zdanie. (Zadanie zostało anulowane.)",
    370: "Adaptacja do Blood Castle (1)",
    371: "Adaptacja do Blood Castle (2)",
    372: "Adaptacja do Blood Castle (3)",
    373: "Adaptacja do Blood Castle (4)",
    374: "Wyzwanie Blood Castle (1)",
    375: "Wyzwanie Blood Castle (2)",
    376: "Wyzwanie Blood Castle (3)",
    377: "Wyzwanie Blood Castle (4)",
    379: "Blood Castle buduje i wystawia na próbę przyjaźń twoją i twoich towarzyszy broni. Jednakże nie jest to łatwe miejsce do osiągnięcia. Idź do Shadow Phantom Soldier i przyjmij zadanie, za które otrzymasz Invisibility Cloak – przedmiot potrzebny do wejścia do Blood Castle.",
    380: "Blood Castle buduje i wystawia na próbę przyjaźń twoją i twoich towarzyszy broni. Jeśli chcesz sprawdzić siłę więzi twojej drużyny, zapytaj Shadow Phantom Soldier o Blood Castle.",
    381: "Blood Castle to doskonałe miejsce na budowanie więzi drużyny. Mam zadanie, za które otrzymasz przedmiot potrzebny do wejścia do Blood Castle. Czy przyjmiesz to zadanie? (Postać podstawowa: Poziom 181-230, Postać zaawansowana: Poziom 161-210)",
    382: "Blood Castle...",
    441: "Burning Lava Giganci opanowali pola lawy w Vulcanus i spowodowali rozproszenie naszych członków gens. Pospiesz się i wytęp te Burning Lava Giganci w Vulcanus.",
    443: "Przez 'proste zadanie' rozumiesz zabijanie potworów?",
    444: "Wezwanie od Gens",
    445: "Możesz wyjaśnić bardziej szczegółowo?",
    478: "Zmiana w Podwodnym Świątyni",
    496: "Adaptacja do Chaos Castle (1)",
    497: "Adaptacja do Chaos Castle (2)",
    498: "Adaptacja do Chaos Castle (3)",
    499: "Adaptacja do Chaos Castle (4)",
    500: "Wyzwanie Chaos Castle (1)",
    501: "Wyzwanie Chaos Castle (2)",
    502: "Wyzwanie Chaos Castle (3)",
    503: "Wyzwanie Chaos Castle (4)",
    504: "Chaos Castle to miejsce, gdzie możesz sprawdzić własne ograniczenia. Jeśli chcesz poznać swoje granice, idź zapytaj Shadow Phantom Soldier o zamek.",
    505: "Chaos Castle wystawi cię na próbę i nie powinieneś go lekceważyć. Koniecznie się przygotuj, z tam pójdziesz. Idź do Shadow Phantom Soldier i przyjmij zadanie, za które otrzymasz przedmioty potrzebne w Chaos Castle.",
    506: "Chaos Castle...",
    518: "Wybór Postaci i Serwera",
    522: "Sprawdź lokalizację i klienta prośby z Listu Prośby.",
    523: "Sprawdź informacje o prośbie. (Przyjmij)",
    524: "Sprawdzanie Listu Prośby",
    539: "Przejdź Illusion Temple i wróć do Shadow Phantom Soldier, by otrzymać 3 000 000 Exp.",
    540: "Przejdź Illusion Temple i wróć do Shadow Phantom Soldier, by otrzymać 5 000 000 Exp.",
    541: "Przejdź Illusion Temple i wróć do Shadow Phantom Soldier, by otrzymać 8 000 000 Exp.",
    542: "Przejdź Illusion Temple i wróć do Shadow Phantom Soldier, by otrzymać 800 000 Exp.",
    543: "Oczyszczenie drogi do Icarus",
    545: "Zamknij okno Zadań i kliknij mnie ponownie. Następnie wybierz 'Otrzymaj wzmocnienie na obrażenia i obronę'.",
    546: "Zamknij okno Zadań i kliknij mnie ponownie. Następnie wybierz 'Otrzymaj wzmocnienie na obrażenia i obronę'. To wzmocnienie jest dostępne dla każdego poniżej poziomu 220.;Po otrzymaniu wzmocnienia zobaczysz ikonę w lewym górnym rogu ekranu, niebieski efekt świetlny wokół postaci oraz będziesz miał godzinę zwiększonych obrażeń i obrony.",
    549: "Zbierz 20 sztuk Gwiezdnego Pyłu od Queen Rainier w Icarus i zanieś je Zyro, by otrzymać nagrodę.",
    553: "Wróć i zobacz się ze mną, gdy osiągniesz poziom 25. Dam cię Unirię jako nagrodę za twój osiągnięcie.",
    554: "Wróć, gdy osiągniesz poziom 25.;Nagrodzę cię wtedy Unirią jako prezent.",
    555: "Wróć, gdy osiągniesz odpowiedni poziom, a dam ci Unirię jako nagrodę.",
    556: "Wróć, gdy będziesz gotowy, a dam ci wtedy pełną odprawę. (Zadanie zostało anulowane.)",
    561: "Ukończ misję Archanioła w Blood Castle Level 1, a następnie wróć do Shadow Phantom Soldier po swoją nagrodę. Jednak dotyczy to tylko Blood Castle Level 1.",
    562: "Ukończ misję Archanioła w Blood Castle Level 2, a następnie wróć do Shadow Phantom Soldier po swoją nagrodę. Jednak dotyczy to tylko Blood Castle Level 2.",
    563: "Ukończ misję Archanioła w Blood Castle Level 3, a następnie wróć do Shadow Phantom Soldier po swoją nagrodę. Jednak dotyczy to tylko Blood Castle Level 3.",
    564: "Ukończ misję Archanioła w Blood Castle Level 4, a następnie wróć do Shadow Phantom Soldier po swoją nagrodę. Jednak dotyczy to tylko Blood Castle Level 4.",
    565: "Ukończ misję Archanioła w Blood Castle Level 5, a następnie wróć do Shadow Phantom Soldier po swoją nagrodę. Jednak dotyczy to tylko Blood Castle Level 5.",
    566: "Ukończ misję Archanioła w Blood Castle Level 6, a następnie wróć do Shadow Phantom Soldier po swoją nagrodę. Jednak dotyczy to tylko Blood Castle Level 6.",
    567: "Ukończ misję Archanioła w Blood Castle Level 7, a następnie wróć do Shadow Phantom Soldier po swoją nagrodę. Jednak dotyczy to tylko Blood Castle Level 7.",
    568: "Ukończ misję Archanioła w Blood Castle Level 8, a następnie wróć do Shadow Phantom Soldier po swoją nagrodę. Jednak dotyczy to tylko Blood Castle Level 8.",
    570: "Zakończenie prośby",
    575: "Gratuluję zostania członkiem Gens Duprian. Wiele będzie od ciebie oczekiwane w imieniu naszej sprawy. Przyjdź do mnie, gdy będziesz potrzebował pomocy dotyczącej gens.",
    576: "Gratuluję zostania członkiem Gens Vanert. Wiele będzie od ciebie oczekiwane w imieniu naszej sprawy. Przyjdź do mnie, gdy będziesz potrzebował pomocy dotyczącej gens.",
    577: "Gratuluję. Ukończyłeś pierwszą misję. Więc od razu dam ci drugą misję. Czy przyjmiesz tę misję? (Postać podstawowa: Poziom 240 - 270, Postać zaawansowana: Poziom 220 - 260)",
    578: "Gratuluję. Ukończyłeś pierwszą misję. Więc od razu dam ci drugą misję. Czy przyjmiesz tę misję? (Postać podstawowa: Poziom 300 - 320, Postać zaawansowana: Poziom 271 - 320)",
    579: "Gratuluję. Ukończyłeś pierwszą misję. Więc od razu dam ci drugą misję. Czy przyjmiesz tę misję? (Poziom 331 - 350)",
    580: "Gratuluję. Ukończyłeś pierwszą misję. Więc od razu dam ci drugą misję. Czy przyjmiesz tę misję? (Poziom 351 - 380)",
    581: "Gratuluję. Ukończyłeś pierwszą misję. Więc od razu dam ci drugą misję. Czy przyjmiesz tę misję? (Poziom 381 - 400)",
    582: "Gratuluję. Ukończyłeś pierwszą misję. Więc od razu dam ci drugą misję. Czy przyjmiesz tę misję? (Poziom mistrzowski)",
    583: "Gratuluję. Włożyłeś więcej w sprawę gens niż jakikolwiek inny członek. Duprian Winston nagradza twoje osiągnięcia. Mam nadzieję zobaczyć jeszcze większe sukcesy od ciebie w przyszłym miesiącu.",
    584: "Gratuluję. Ukończyłeś samouczek. Weź ten Pierścień Bohatera i ten Pierścień Wojownika. To prezenty dla ciebie od królowej.",
    585: "Podbój Lochu! (1)",
    586: "Podbój Lochu! (2)",
    587: "Podbój Lochu! (3)",
    588: "Podbój Lochu! (4)",
    589: "Podbój Lochu! (5)",
    590: "Podbój Lochu! (6)",
    591: "Kontynuuj słuchanie.",
    592: "Kontynuuj rozmowę.",
    593: "Kontynuujące ataki na bariery (1)",
    594: "Kontynuujące ataki na bariery (2)",
    595: "Kontynuujące ataki na bariery (3)",
    596: "Kontynuujące prośby o pomoc (1)",
    597: "Kontynuujące prośby o pomoc (2)",
    598: "Kontynuujące prośby o pomoc (3)",
    599: "Kontynuujące prośby o pomoc (4)",
    603: "Odwaga to najważniejsza cecha bohatera. Jeśli brakuje ci właściwej odwagi, nigdy nie odrodzisz się jako bohater.",
    650: "Zgniecenie sił wrogiego klanu będzie najlepszą zemstą. Naucz ich lekcji, eliminując 5 z nich, którzy przeniknęli do Vulcanus. Zabij członka wrogiego klanu w Vulcanus i wróć do mnie po nagrodę. (Można wykonać tylko w Vulcanus)",
    680: "Dark Knightowie są wyjątkowi tym, że są potężnymi miecznikami polegającymi zarówno na broni, jak i kulach. Dam ci broń do użycia, byś lepiej zrozumiał.",
    681: "Dark Knightowie mogą uczyć się dodatkowych umiejętności udając się do Lorencji i kupując kule u Pasi the Mage (119,112). Po kupieniu kuli, kliknij ją prawym przyciskiem myszy, by nauczyć się umiejętności.",
    682: "Dark Knightowie mogą uczyć się dodatkowych umiejętności udając się do Lorencji i kupując zwoje u Pasi the Mage (119,112). Po kupieniu zwoju, kliknij go prawym przyciskiem myszy, by nauczyć się umiejętności.",
    726: "Dark Wizardzi są wyjątkowi tym, że potrafią opanować różnorodne zaklęcia z zwojów i pergaminów. Dam ci zwój jako prezent, byś zrozumiał, o co mi chodzi.",
    727: "Dark Wizardzi mogą uczyć się dodatkowych umiejętności udając się do Lorencji i kupując zwoje u Pasi the Mage (119,112) lub broń u Hanzo the Blacksmith (116,142).",
    740: "Death Knightowie z Poziomów 5 przez 7 Lost Tower wyrządzają wielkie szkody podróżnym tam będącymi. Idź do Lost Tower i pokonaj 80 Death Knightów. Przyjdź do mnie, gdy to zrobisz, by otrzymać Invisibility Cloak + 3 jako nagrodę. Na twoim obecnym poziomie polowanie na te potwory w pojedynkę będzie zbyt niebezpieczne. Lepiej będzie, jeśli będziesz polował w drużynie.",
    762: "Pokonaj 10 potworów w Chaos Castle, dostarcz broń Archaniołowi w Blood Castle i przetrwaj do końca Devil Square. Ukończ wszystkie trzy i wróć do Phantom Soldier, by otrzymać nagrodę.",
    763: "Pokonaj 100 Queen Rainier w Icarus, a następnie wróć do Shadow Phantom Soldier, by wybrać nagrodę między 10 Large SD Potions a 30 Complex Potions.",
    764: "Pokonaj 15 Agonów z okolic południowej strony miasta (173, 222) i wróć do mnie po nagrodę.",
    765: "Pokonaj 15 Gigantów z okolic wejścia do Devias (22, 45) po wschodniej stronie miasta i wróć do mnie po nagrodę.",
    766: "Pokonaj 15 Liches z okolic wejścia do Lochu (159, 205) po południowo-zachodniej stronie miasta i wróć do mnie po nagrodę.",
    767: "Pokonaj 20 Polluted Butterflies z okolic nagrobka (121, 156) po północnej stronie miasta i wróć do mnie po nagrodę.",
    768: "Pokonaj 20 Gigantów z okolic wejścia do Devias (22, 45) po wschodniej stronie miasta i wróć do mnie po nagrodę.",
    769: "Pokonaj 20 Hideous Rabbitów z okolic rzeźby twarzy po północnej stronie miasta (151, 146) i wróć do mnie po nagrodę.",
    770: "Pokonaj 20 Szkieletowych Wojowników z okolic wejścia do Lochu (123, 227) po południowo-zachodniej stronie miasta i wróć do mnie po nagrodę.",
    771: "Pokonaj 20 Stone Golemów z okolic południowo-zachodniej strony miasta (30, 214) i wróć do mnie po nagrodę.",
    772: "Pokonaj 20 potworów w Chaos Castle, dostarcz broń Archaniołowi w Blood Castle i przetrwaj do końca Devil Square. Ukończ wszystkie trzy i wróć do Phantom Soldier, by otrzymać nagrodę.",
    773: "Pokonaj 30 potworów w Chaos Castle, dostarcz broń Archaniołowi w Blood Castle i przetrwaj do końca Devil Square. Ukończ wszystkie trzy i wróć do Phantom Soldier, by otrzymać nagrodę.",
    774: "Pokonaj 40 Larw z Poziomu 1 Lochu i wróć do Shadow Phantom Soldier, by wybrać dwie nagrody spośród 30 Healing Potions, 30 Mana Potions i 4 Small SD Potions.",
    775: "Pokonaj 5 potworów w Chaos Castle, dostarcz broń Archaniołowi w Blood Castle i przetrwaj do końca Devil Square. Ukończ wszystkie trzy i wróć do Phantom Soldier, by otrzymać nagrodę.",
    776: "Pokonaj 50 Cursed Liches w Elveland (Obszar 2) i 50 Yetis w Devias (Obszar 2). Zrób to, a otrzymasz 60 000 pkt EXP, 1 500 000 Zenów i 1 Jewel of Chaos jako nagrodę od Shadow Phantom Soldier.",
    777: "Pokonaj 50 Totem Golemów w Elveland (Obszar 3) i 50 Elite Yetis w Devias (Obszar 3). Zrób to, a otrzymasz 60 000 pkt EXP, 1 500 000 Zenów i 1 Jewel of Chaos jako nagrodę od Shadow Phantom Soldier.",
    778: "Pokonaj 60 Hell Pająków z Poziomu 2 Lochu i wróć do Shadow Phantom Soldier, by wybrać dwie nagrody spośród 15 Large Healing Potions, 15 Large Mana Potions i 8 Small SD Potions.",
    779: "Pokonaj 80 Dark Knightów z Poziomu 3 Lochu i wróć do Shadow Phantom Soldier, by wybrać dwie nagrody spośród 30 Large Healing Potions, 30 Large Mana Potions i 15 Small Complex Potions.",
    830: "Adaptacja do Devil Square (1)",
    831: "Adaptacja do Devil Square (2)",
    832: "Adaptacja do Devil Square (3)",
    833: "Adaptacja do Devil Square (4)",
    834: "Wyzwanie Devil Square (1)",
    835: "Wyzwanie Devil Square (2)",
    836: "Wyzwanie Devil Square (3)",
    837: "Wyzwanie Devil Square (4)",
    839: "Devil Square to miejsce, gdzie możesz szybko rozwijać swoje umiejętności. Przygotuj się dokładnie przed wejściem, ponieważ nie jest to miejsce do lekceważenia. Idź do Shadow Phantom Soldier i przyjmij zadanie, by zdobyć Devil's Invitation – przedmiot potrzebny do wejścia do Devil Square.",
    840: "Devil Square to miejsce, gdzie możesz szybko doskonalić i rozwijać swoje umiejętności. Jeśli chcesz szybko stać się silniejszy, zapytaj Shadow Phantom Soldier o Devil Square.",
    841: "Devil Square to miejsce, gdzie niegdyś stało Drzewo Elfów. Drzewo Elfów zostało stworzone przez matkę wszystkich Elfów – podziemną Elfę znaną jako Aria. To drzewo miało zdolność regularnego wytwarzania Elfów. Następnie Secrarium oszukał Lugarda i pojawił się w Nori, w miejscu Drzewa Elfów.",
    842: "Devil Square daje możliwość treningu i zdobywania doświadczenia. Mam mały test, który pozwoli mi ocenić twoje umiejętności i doświadczenie. Czy chcesz go przystąpić? (Wszystkie postacie: Master Level)",
    843: "Devil Square daje możliwość treningu i zdobywania doświadczenia. Mam mały test, który pozwoli mi ocenić twoje umiejętności i doświadczenie. Czy chcesz go przystąpić? (Postać podstawowa: Poziom 330-400, Postać zaawansowana: Poziom 311-400)",
    844: "Devil Square daje możliwość treningu i zdobywania doświadczenia. Mam mały test, który pozwoli mi ocenić twoje umiejętności i doświadczenie. Czy chcesz go przystąpić? (Postać podstawowa: Poziom 131-180, Postać zaawansowana: Poziom 111-160)",
    845: "Devil Square daje możliwość treningu i zdobywania doświadczenia. Mam mały test, który pozwoli mi ocenić twoje umiejętności i doświadczenie. Czy chcesz go przystąpić? (Postać podstawowa: Poziom 181-230, Postać zaawansowana: Poziom 161-210)",
    846: "Devil Square daje możliwość treningu i zdobywania doświadczenia. Mam mały test, który pozwoli mi ocenić twoje umiejętności i doświadczenie. Czy chcesz go przystąpić? (Postać podstawowa: Poziom 231-280, Postać zaawansowana: Poziom 211-260)",
    847: "Devil Square daje możliwość treningu i zdobywania doświadczenia. Mam mały test, który pozwoli mi ocenić twoje umiejętności i doświadczenie. Czy chcesz go przystąpić? (Postać podstawowa: Poziom 281-330, Postać zaawansowana: Poziom 261-310)",
    848: "Devil Square daje możliwość treningu i zdobywania doświadczenia. Czy chcesz trenować w Devil Square? (Postać podstawowa: Poziom 15-130, Postać zaawansowana: Poziom 10-110)",
    849: "Devil Square...",
    853: "Diabły z Poziomów 4 przez 6 Lost Tower powinny wystarczyć. Idź do Lost Tower i pokonaj 100 Diabłów. Przyjdź do mnie potem, a dam ci wybór między 15 SD Potions a 15 Complex Potions jako nagrodę. Gdy będziesz odbierał nagrody, upewnij się, że masz co najmniej 15 pustych slotów w ekwipunku. Pamiętaj o tym.",
    854: "Uruchomiłeś okno Statystyk Postaci?;To okno zawiera imię i poziom postaci, nazwę bieżącego serwera oraz statusy postaci.",
    855: "Mówiłeś o spacji?",
    860: "Pozbądź się przywódcy Grabieżców!",
    861: "Rozpraw się z Grabieżcami Miasta!",
    872: "Nie brzmi zbyt trudno....",
    927: "Dreadfeary w Kanturu Relics wyrządzają wielkie szkody podróżnym tam będącymi. Idź do Kanturu Relics i wytrop 100 Dreadfearów. Przyjdź do mnie, gdy to zrobisz, by otrzymać Invisibility Cloak + 8 jako nagrodę. Na twoim obecnym poziomie polowanie na te potwory w pojedynkę będzie zbyt niebezpieczne. Lepiej będzie, jeśli będziesz polował w drużynie.",
    928: "Jednak dzięki zaklęciom iluzji Leva, dusze zmarłych naśladowców pozostały na tym świecie, by bronić świątyni. Te dusze wierzyły, że powrót Leva pozwoli im odzyskać ciała, i kontynuowały strzeżenie świątyni. Dzisiaj świątynia jest strzeżona przez przymierze na wypadek, gdyby Lev faktycznie powrócił, a Illusion Sorcery używa starożytnych relikwii, by zwabiać niczego nie podejrzewających podróżnych do swojej sprawy.",
    937: "Czyszczenie Lochu!",
    947: "Dural, pierwszy mistrz gildii, był legendarnym dowódcą, który poprowadził nas do wielkiego zwycięstwa nad armią Kunduna. Musiał się odciąć od świata od czasu buntu Gaiona i rozkazu wytępienia 5 głównych klanów. Nowo utworzona gildia najemników zerwała wszelkie relacje z Gaionem, ale 5 głównych klanów wciąż chce, by gildia najemników pozbyła się Gaiona.",
    948: "Punkty EXP i awansowanie",
    954: "Zdobyć wartościowy ekwipunek wykonując proste zadania?",
    981: "Wyeliminuj 1 Hero Zombie Fighter i 1 Hero Reborn Gladiator, a następnie wróć do swojego Gens Steward po nagrodę.",
    982: "Wyeliminuj 20 Bloody Slayer i 10 Vicious Bloody Slayer, a następnie wróć do swojego Gens Steward po nagrodę.",
    983: "Wyeliminuj 30 Aegis i 20 Rogue Centurionów i wróć do Beiny po nagrodę.",
    984: "Wyeliminuj 30 Bloody Soldierów i 20 Death Angels w Kalima 6 i wróć do Beiny po nagrodę.",
    985: "Wyeliminuj 30 Necronów i 20 Death Centurionów, a następnie wróć do Beiny po nagrodę.",
    986: "Wyeliminuj 5 graczy z wrogiego Gens, a następnie wróć do swojego Gens Steward po nagrodę.",
    987: "Wyeliminuj 50 Blood Assassinów, a dam ci nagrodę.",
    988: "Wyeliminuj 50 Burning Lava Giantów i wróć do mnie po nagrodę.",
    989: "Wyeliminuj 50 Death Riderów i wróć do mnie po nagrodę.",
    990: "Wyeliminuj 50 Death Trees i wróć do mnie po nagrodę.",
    991: "Wyeliminuj 50 Ghost Napinów i wróć do mnie po nagrodę.",
    992: "Wyeliminuj 50 Iron Riderów, by powstrzymać ich partyzanckie ataki, a dam ci nagrodę.",
    993: "Wyeliminuj 50 Sapi-Duos, by powstrzymać ataki na naszych członków gens, a dam ci nagrodę.",
    994: "Wyeliminuj 50 Silver Valkyrie i wróć do mnie po nagrodę.",
    995: "Wyeliminuj 50 Splinter Wolves i wróć do mnie po nagrodę.",
    996: "Wyeliminuj Advisor Jerinda i Gaiona Khareina, a następnie wróć do Mercenary Guild Manager Tercia po nagrodę.",
    997: "Wyeliminuj Blood Assassinów",
    998: "Wyeliminuj Kunduna i 10 Schrikerów – strażniczych żołnierzy – a następnie wróć do Beiny po nagrodę.",
    999: "Wyeliminuj grabieżcze Silver Valkyrie",
    1000: "Wyeliminuj Raymonda i Erkanne w Varka, a następnie wróć do Mercenary Guild Manager Tercia po nagrodę.",
    1001: "Wyeliminuj Sapi-Duos",
    1002: "Wyeliminuj Splinter Wolves",
    1024: "Elveland nie powinien być taki trudny.",
    1030: "Elfowie mogą uczyć się dodatkowych umiejętności udając się do Nori i kupując kule u Elf Lala (173,124) lub broń u Eo the Craftsman (195,123).",
    1036: "Powstrzymaj rozprzestrzenianie Death Trees",
    1042: "Wejdź do Devil Square Level 1, pokonuj pojawiające się potwory i przetrwaj do samego końca. Wróć potem, a dam ci 100 000 pkt EXP i 200 000 Zenów jako nagrodę. Jednak dotyczy to tylko Devil Square Level 1.",
    1043: "Wejdź do Devil Square Level 2, pokonuj pojawiające się potwory i przetrwaj do samego końca. Wróć do mnie potem, a dam ci 400 000 pkt EXP i 300 000 Zenów jako nagrodę. Jednak dotyczy to tylko Devil Square Level 2.",
    1044: "Wejdź do Devil Square Level 3, pokonuj pojawiające się potwory i przetrwaj do samego końca. Wróć do mnie potem, a dam ci 1 000 000 pkt EXP i 1 Jewel of Chaos jako nagrodę. Jednak dotyczy to tylko Devil Square Level 3.",
    1045: "Wejdź do Devil Square Level 4, pokonuj pojawiające się potwory i przetrwaj do samego końca. Dam ci 1 Jewel of Soul jako nagrodę, gdy wrócisz. Jednak dotyczy to tylko Devil Square Level 4.",
    1046: "Wejdź do Devil Square Level 5, pokonuj pojawiające się potwory i przetrwaj do samego końca. Dam ci 1 Jewel of Bless jako nagrodę, gdy wrócisz. Jednak dotyczy to tylko Devil Square Level 5.",
    1047: "Wejdź do Devil Square Level 6, pokonuj pojawiające się potwory i przetrwaj do samego końca. Dam ci 1 Jewel of Life jako nagrodę, gdy wrócisz. Jednak dotyczy to tylko Devil Square Level 6.",
    1048: "Wejdź do Devil Square Level 7, pokonuj pojawiające się potwory i przetrwaj do samego końca. Dam ci 2 Jewele of Bless jako nagrodę, gdy wrócisz. Jednak dotyczy to tylko Devil Square Level 7.",
    1049: "Wejdź na Aida 2, a znajdziesz Witch Queens. Zawsze noszą przy sobie 'Kalt Stone', więc wyeliminuj je i zabierz kamień. Przynieś mi 10 Kalt Stones. (Można w drużynie)",
    1095: "Zła energia uciekła z Lost Tower i teraz zepsuca dusze mieszkańców Devias, zamieniając ich w potwory. Chciałbym poprosić cię o oczyszczenie ich dusz i danie im wiecznego spoczynku. Czy przyjmiesz to zadanie? (Poziom 186-189)",
    1103: "Doskonale! Dawaj test!",
    1104: "Doskonale! Zaraz wrócę.",
    1105: "Doskonale! Czas na następne zadanie. Skoro już znasz się na polowaniu, zmusimy cię do pogoń za twardszym potworem.",
    1106: "Doskonale! Zacznijmy samouczek.",
    1107: "Doskonale! Jak nazywa się potwór, który mam wytropić?",
    1108: "Rozszerzanie biznesu",
    1114: "Wyjaśnij mi jeszcze raz o miksturach.",
    1122: "Szybki wzrost...",
    1123: "Najszybszy sposób na trening (1)",
    1124: "Najszybszy sposób na trening (2)",
    1125: "Najszybszy sposób na trening (3)",
    1126: "Najszybszy sposób na trening (4)",
    1127: "Najszybszy sposób na trening (5)",
    1130: "Ostateczny test, by zostać bohaterem",
    1131: "W końcu zadanie! Chcesz, żebym kupił 5 jabłek u kupca?",
    1132: "Znajdź 2 strony 'Zagubionej Mapy Lv. 4' i wróć do 'Shadow Phantom Soldier'.",
    1133: "Znajdź 2 strony 'Zagubionej Mapy Lv. 5' i wróć do 'Shadow Phantom Soldier'.",
    1134: "Znajdź 3 strony 'Zagubionej Mapy Lv. 3' i wróć do 'Shadow Phantom Soldier'.",
    1135: "Znajdź General Goods Merchant Zyro",
    1136: "Znajdź General Goods Merchant Zyro i sprawdź szczegóły jego prośby do gildii najemników.",
    1137: "Znajdź General Goods Merchant Zyro, który krąży po Nori, Elveland, Lorencji i Devias i sprzedaje rzeczy.",
    1138: "Znajdź Priestess Beinę z Podwodnej Świątyni w Kalima 6 i sprawdź informacje o prośbie.",
    1139: "Znajdź kupca Zyro, który krąży po Nori, Elveland, Lorencji i Devias i sprzedaje rzeczy.",
    1141: "Znajdź menedżera biura gildii Tercia i wpłać 500 000 Zen jako kaucję, by otrzymać List Prośby Lv. 1 zawierający zadanie dnia.",
    1142: "Znajdź swojego Gens Steward.",
    1168: "Pierwszym zadaniem jest zebranie Gwiezdnego Pyłu, który jest podstawowym materiałem popularnego kosmetyku Della. Panie w kolejce mi grożą, więc musiałem poprosić gildię najemników. Możesz wyekstrahować niewielką ilość Gwiezdnego Pyłu od Queen Rainier w Icarus. Proszę przynieś mi 20 sztuk Gwiezdnego Pyłu. (Można w drużynie)",
    1169: "Najpierw musisz wyeliminować żołnierzy Kunduna atakujących wejście do świątyni, a potem pozbyć się wrogów rzucających zaklęcia na zapieczętowany kamień. Dam ci drugi cel, gdy skończysz pierwszy i wrócisz do mnie. Oto pierwszy cel: idź do Kalima 6 i wyeliminuj 30 Aegis i 20 Rogue Centurionów – żołnierzy Kunduna. (Można w drużynie)",
    1188: "Wolny najemnik tak naprawdę nie należy do gildii najemników; każdy może otrzymać prośbę i dostać nagrodę, o ile ma odpowiednią sumę pieniędzy na rejestrację. Pobieramy kaucję za każdą prośbę, ale jest ona w pełni zwrotna po ukończeniu prośby. Nie martw się. Przydzielamy ci to, co dasz radę.",
    1191: "Z okna czatu użyj przycisku Ctrl.",
    1192: "Z okna czatu użyj przycisku Shift.",
    1193: "Z okna czatu użyj przycisku Tab.",
    1202: "Zbieraj punkty EXP, by awansować na wyższy poziom.;Możesz sprawdzić, ile punktów brakuje ci do następnego poziomu, otwierając okno Statystyk Postaci lub sprawdzając pasek EXP na dole ekranu.;Pasek jest podzielony na dziesięć segmentów, a ich zapełnienie przeniesie cię na następny poziom.",
    1218: "Gens Duprian to gildia największych bohaterów w Arce, a w jej sercu jest klan Duprian – najpotężniejsza szlachecka krew w MU. Prowadzi nas Duprian Winston, rycerz nie znający sobie równych w całym imperium MU.",
    1219: "Nagroda za Ranking Gens",
    1221: "Gens Vanert to szlachecka rodzina prowadzona przez Vanerta Reichta – największego bywalca towarzyskiego w całym imperium MU. Mistrz niestrudzenie pracuje, by powstrzymać Dupriana Winstona i jego marzenie o absolutnych rządach nad imperium.",
    1222: "Spór gens? Bardziej jak bunt Gens Vanert. Spór gens rozpoczął się z powodu chciwości Vanerta Reichta, dowódcy rycerskiego Gens Vanert. Dokładnie pięć lat temu banda bohaterów poszukujących w La Cleon kamienia z mocą zapieczętowania Kunduna została wymordowana. Wtedy wierzyliśmy, że to dzieło Selupana – gigantycznego pająka i władcy La Cleon – ale wkrótce dowiedzieliśmy się, że to tak naprawdę Gens Vanert. Obowiązkiem naszych dumnych mistrzów Gens Duprian jest odwet i walka.",
    1223: "Nagrody za ranking gens są przyznawane w pierwszym tygodniu każdego miesiąca.",
    1224: "Pozbądź się Kunduna i 10 Schrikerów – strażniczych żołnierzy w najgłębszym zakątku Kalima 6 – i wróć do mnie po nagrodę. (Można w drużynie)",
    1243: "Daj mi list prośby.",
    1244: "Daj mi czas na przygotowanie. (Odrzuć)",
    1252: "Chwała Gens",
    1253: "Śmiało, naucz się umiejętności Kula Ognia.",
    1254: "Wróć.",
    1255: "Wyjdź poza mury Elveland i wytrop 3 Strange Rabbits.",
    1256: "Wyjdź poza mury Elveland i wytrop 3 Strange Rabbits.;Jeśli będziesz miał kłopoty, naciśnij przycisk Q, by odzyskać HP. Jestem pewien, że to polowanie jest w twoich możliwościach.",
    1257: "Wyjdź poza mury Elveland i wytrop 30 Polluted Butterflies.",
    1258: "Wyjdź poza mury Elveland i wytrop 30 Polluted Butterflies. Jestem pewien, że to polowanie jest w twoich możliwościach.",
    1259: "Wyjdź poza mury Lorencji i wytrop 3 Budge Dragons.",
    1260: "Wyjdź poza mury Lorencji i wytrop 3 Budge Dragons.;Jeśli będziesz miał kłopoty, naciśnij przycisk Q, by odzyskać HP. Jestem pewien, że to polowanie jest w twoich możliwościach.",
    1261: "Wyjdź poza mury Lorencji i wytrop 30 Houndów.",
    1262: "Wyjdź poza mury Lorencji i wytrop 30 Houndów. Jestem pewien, że to polowanie jest w twoich możliwościach.",
    1263: "Wyjdź poza mury Nori i wytrop 3 Chain Scorpions.",
    1264: "Wyjdź poza mury Nori i wytrop 3 Chain Scorpions.;Jeśli będziesz miał kłopoty, naciśnij przycisk Q, by odzyskać HP. Jestem pewien, że to polowanie jest w twoich możliwościach.",
    1265: "Wyjdź poza mury Nori i wytrop 30 Beetle Monsters.",
    1266: "Wyjdź poza mury Nori i wytrop 30 Beetle Monsters. Jestem pewien, że to polowanie jest w twoich możliwościach.",
    1267: "Idź znajdź kupca w mieście i przynieś 5 jabłek.",
    1268: "Idź znajdź kupca w mieście i przynieś 5 jabłek.;Nazwa NPC będzie pokazana na jasnoniebiesko, a symbol punktu zmieni się w symbol zęba, gdy najedziesz na niego myszą.",
    1269: "Przejdź przez bramę zamku i pokonaj dwóch Czerwonych Czaszek, które ukryły Absolutną Broń. To da ci trochę więcej czasu i ujawni szkatułkę z bronią. Zniszcz szkatułkę, pokonaj więcej potworów i zwróć Absolutną Broń Archaniołowi, by pomyślnie ukończyć zadanie Blood Castle.",
    1270: "Idź znowu do handlarza miksturami i kup tylko 1 Town Portal Scroll.",
    1271: "Idź do Devias 4 i pokonaj 5 Ice Queens. Gdy to zrobisz, będziesz mógł otrzymać nagrodę od Shadow Phantom Soldier.",
    1272: "Idź do Devias 4 i pokonaj 5 Ice Queens. Gdy wrócisz, dam ci Ancient Gloves + 7 jako nagrodę.",
    1273: "Idź do Devias 4 i pokonaj 5 Ice Queens. Gdy wrócisz, dam ci Eclipse Gloves + 7 jako nagrodę.",
    1274: "Idź do Devil Square Level 1. Pokonuj pojawiające się potwory i przetrwaj do samego końca, by otrzymać nagrodę od Shadow Phantom Soldier. Jednak dotyczy to tylko Devil Square Level 1.",
    1275: "Idź do Devil Square Level 2. Pokonuj pojawiające się potwory i przetrwaj do samego końca, by otrzymać nagrodę od Shadow Phantom Soldier. Jednak dotyczy to tylko Devil Square Level 2.",
    1276: "Idź do Devil Square Level 3. Pokonuj pojawiające się potwory i przetrwaj do samego końca, by otrzymać nagrodę od Shadow Phantom Soldier. Jednak dotyczy to tylko Devil Square Level 3.",
    1277: "Idź do Devil Square Level 4. Pokonuj pojawiające się potwory i przetrwaj do samego końca, by otrzymać nagrodę od Shadow Phantom Soldier. Jednak dotyczy to tylko Devil Square Level 4.",
    1278: "Idź do Devil Square Level 5. Pokonuj pojawiające się potwory i przetrwaj do samego końca, by otrzymać nagrodę od Shadow Phantom Soldier. Jednak dotyczy to tylko Devil Square Level 5.",
    1279: "Idź do Devil Square Level 6. Pokonuj pojawiające się potwory i przetrwaj do samego końca, by otrzymać nagrodę od Shadow Phantom Soldier. Jednak dotyczy to tylko Devil Square Level 6.",
    1280: "Idź do Devil Square Level 7. Pokonuj pojawiające się potwory i przetrwaj do samego końca, by otrzymać nagrodę od Shadow Phantom Soldier. Jednak dotyczy to tylko Devil Square Level 7.",
    1281: "Idź do Poziomu 2 Lochu i pokonaj 50 Chief Skeleton Warriors i 30 Thunder Liches. Gdy to zrobisz, będziesz mógł otrzymać nagrodę od Shadow Phantom Soldier.",
    1282: "Idź do Poziomu 2 Lochu i pokonaj 50 Hell Houndów i 30 Hell Pająków. Gdy to zrobisz, będziesz mógł otrzymać nagrodę od Shadow Phantom Soldier.",
    1283: "Idź do Poziomu 2 Lochu i pokonaj 50 Hell Pająków i 30 Chief Skeleton Warriors. Gdy to zrobisz, będziesz mógł otrzymać nagrodę od Shadow Phantom Soldier.",
    1284: "Idź do Poziomu 2 Lochu i pokonaj 50 Poison Bull Fighterów i 30 Dark Knightów. Gdy to zrobisz, będziesz mógł otrzymać nagrodę od Shadow Phantom Soldier.",
    1285: "Idź do Poziomu 2 Lochu i pokonaj 50 Szkieletowych Łuczników i 30 Hell Houndów. Gdy to zrobisz, będziesz mógł otrzymać nagrodę od Shadow Phantom Soldier.",
    1286: "Idź do Poziomu 2 Lochu. Pokonaj 40 Hell Houndów i wróć do Shadow Phantom Soldier, by otrzymać Invisibility Cloak + 1 – przedmiot potrzebny do wejścia do Blood Castle.",
    1287: "Idź do Poziomu 2 Lochu. Pokonaj 50 Chief Skeleton Warriors i 30 Thunder Liches, a dam ci Dragon Helm + 8 jako nagrodę.",
    1288: "Idź do Poziomu 2 Lochu. Pokonaj 50 Chief Skeleton Warriors i 30 Thunder Liches, a dam ci Guardian Helm + 8 jako nagrodę.",
    1289: "Idź do Poziomu 2 Lochu. Pokonaj 50 Chief Skeleton Warriors i 30 Thunder Liches, a dam ci Legendary Armor + 8 jako nagrodę.",
    1290: "Idź do Poziomu 2 Lochu. Pokonaj 50 Chief Skeleton Warriors i 30 Thunder Liches, a dam ci Red Wing Armor + 8 jako nagrodę.",
    1291: "Idź do Poziomu 2 Lochu. Pokonaj 50 Cyklopów i 30 Duchów, a dam ci Legendary Gloves + 8 jako nagrodę.",
    1292: "Idź do Poziomu 2 Lochu. Pokonaj 50 Cyklopów i 30 Duchów, a dam ci Red Wing Gloves + 8 jako nagrodę.",
    1293: "Idź do Poziomu 2 Lochu. Pokonaj 50 Hell Houndów i 30 Hell Pająków, a dam ci Dragon Boots + 8 jako nagrodę.",
    1294: "Idź do Poziomu 2 Lochu. Pokonaj 50 Hell Houndów i 30 Hell Pająków, a dam ci Guardian Boots + 8 jako nagrodę.",
    1295: "Idź do Poziomu 2 Lochu. Pokonaj 50 Hell Houndów i 30 Hell Pająków, a dam ci Legendary Helm + 8 jako nagrodę.",
    1296: "Idź do Poziomu 2 Lochu. Pokonaj 50 Hell Houndów i 30 Hell Pająków, a dam ci Red Wing Helm + 8 jako nagrodę.",
    1297: "Idź do Poziomu 2 Lochu. Pokonaj 50 Hell Pająków i 30 Chief Skeleton Warriors, a dam ci Legendary Pants + 8 jako nagrodę.",
    1298: "Idź do Poziomu 2 Lochu. Pokonaj 50 Hell Pająków i 30 Chief Skeleton Warriors, a dam ci Red Wing Pants + 8 jako nagrodę.",
    1299: "Idź do Poziomu 2 Lochu. Pokonaj 50 Szkieletowych Łuczników i 30 Hell Houndów, a dam ci Dragon Gloves + 8 jako nagrodę.",
    1300: "Idź do Poziomu 2 Lochu. Pokonaj 50 Szkieletowych Łuczników i 30 Hell Houndów, a dam ci Guardian Gloves + 8 jako nagrodę.",
    1301: "Idź do Poziomu 2 Lochu. Pokonaj 50 Szkieletowych Łuczników i 30 Hell Houndów, a dam ci Legendary Boots + 8 jako nagrodę.",
    1302: "Idź do Poziomu 2 Lochu. Pokonaj 50 Szkieletowych Łuczników i 30 Hell Houndów, a dam ci Red Wing Boots + 8 jako nagrodę.",
    1303: "Idź do Poziomu 3 Lochu i pokonaj 50 Dark Knightów i 10 Gorgonów. Gdy to zrobisz, będziesz mógł otrzymać nagrodę od Shadow Phantom Soldier.",
    1304: "Idź do Poziomu 3 Lochu. Pokonaj 50 Dark Knightów i 10 Gorgonów, a dam ci Dragon Armor + 8 jako nagrodę.",
    1305: "Idź do Poziomu 3 Lochu. Pokonaj 50 Dark Knightów i 10 Gorgonów, a dam ci Guardian Armor + 8 jako nagrodę.",
    1306: "Idź do Poziomu 3 Lochu. Pokonaj 50 Poison Bull Fighterów, 5 Dark Knightów i 1 Gorgonę, a dam ci Legendary Staff + 7 jako nagrodę.",
    1307: "Idź do Poziomu 3 Lochu. Pokonaj 50 Poison Bull Fighterów, 5 Dark Knightów i 1 Gorgonę, a dam ci Red Wing Stick + 7 jako nagrodę.",
    1308: "Idź do Poziomu 3 Lochu. Pokonaj 50 Poison Bull Fighterów, 50 Dark Knightów i 30 Gorgonów, a dam ci Bluewing Crossbow + 8 + Skill jako nagrodę.",
    1309: "Idź do Poziomu 3 Lochu. Pokonaj 50 Poison Bull Fighterów, 50 Dark Knightów i 30 Gorgonów, a dam ci dwie Double Blades + 8 + Skill jako nagrodę.",
    1310: "Idź do Poziomu 3 Lochu. Pokonaj 60 Gorgonów i wróć do Shadow Phantom Soldier, by otrzymać Invisibility Cloak + 2 – przedmiot potrzebny do wejścia do Blood Castle.",
    1311: "Idź do Poziomów 1 i 2 Lochu i pokonaj 50 Cyklopów i 30 Duchów. Gdy to zrobisz, będziesz mógł otrzymać nagrodę od Shadow Phantom Soldier.",
    1312: "Idź do Poziomów 1 i 2 Lochu i pokonaj 50 Szkieletowych Łuczników i 30 Hell Houndów. Gdy to zrobisz, będziesz mógł otrzymać nagrodę od Shadow Phantom Soldier.",
    1313: "Idź do Poziomów 2 i 3 Lochu i pokonaj 50 Poison Bull Fighterów, 5 Dark Knightów i 1 Gorgonę. Gdy to zrobisz, będziesz mógł otrzymać nagrodę od Shadow Phantom Soldier.",
    1314: "Idź do Poziomów 2 i 3 Lochu i pokonaj 50 Poison Bull Fighterów, 50 Dark Knightów i 30 Gorgonów. Gdy to zrobisz, będziesz mógł otrzymać nagrodę od Shadow Phantom Soldier.",
    1315: "Idź do Poziomów 2 i 3 Lochu. Pokonaj 50 Poison Bull Fighterów i 30 Dark Knightów, a dam ci Dragon Pants + 8 jako nagrodę.",
    1316: "Idź do Poziomów 2 i 3 Lochu. Pokonaj 50 Poison Bull Fighterów i 30 Dark Knightów, a dam ci Guardian Pants + 8 jako nagrodę.",
    1317: "Idź do Elveland 2. Pokonaj 40 Cursed Liches i wróć do Shadow Phantom Soldier, by otrzymać Devil's Invitation + 1 – przedmiot potrzebny do wejścia do Devil Square.",
    1318: "Idź do Elveland 3 i pokonaj 100 Captain Grizzliów. Dam ci Ancient Helm + 7 i Ancient Pants + 7 jako nagrodę.",
    1319: "Idź do Elveland 3 i pokonaj 100 Captain Grizzliów. Dam ci Eclipse Helm + 7 i Eclipse Pants + 7 jako nagrodę.",
    1320: "Idź do Elveland 3 i pokonaj 100 Captain Grizzliów. Gdy to zrobisz, będziesz mógł otrzymać nagrodę od Shadow Phantom Soldier.",
    1321: "Idź do Elveland 3 i pokonaj 100 Grizzliów. Dam ci Ancient Boots + 7 jako nagrodę.",
    1322: "Idź do Elveland 3 i pokonaj 100 Grizzliów. Dam ci Eclipse Boots + 7 jako nagrodę.",
    1323: "Idź do Elveland 3 i pokonaj 100 Grizzliów. Gdy to zrobisz, będziesz mógł otrzymać nagrodę od Shadow Phantom Soldier.",
    1324: "Idź do Icarus, zabij 20 Alquamosów i 10 Alpha Crustów i wróć do 'Shadow Phantom Soldier' po swoją nagrodę.",
    1325: "Idź do Icarus, zabij 20 Alquamosów i 20 Drakanów i wróć do 'Shadow Phantom Soldier' po swoją nagrodę.",
    1326: "Idź do Icarus, zabij 20 Alquamosów i wróć do 'Shadow Phantom Soldier' z 1 Crystal Sword (Atak +12) po swoją nagrodę.",
    1327: "Idź do Icarus, zabij 20 Alquamosów i wróć do 'Shadow Phantom Soldier' z 1 Sword of Destruction (Atak +12) po swoją nagrodę.",
    1328: "Idź do Icarus, zabij 30 Queen Rainier i wróć do 'Shadow Phantom Soldier' po swoją nagrodę.",
    1329: "Idź do Icarus. Pokonaj 100 Phantom Knights i wróć do Shadow Phantom Soldier, by otrzymać Invisibility Cloak + 6 – przedmiot potrzebny do wejścia do Blood Castle.",
    1330: "Idź do Icarus. Pokonaj 130 Giant Drakanów i wróć do Shadow Phantom Soldier, by otrzymać Scroll of Blood + 5 – przedmiot potrzebny do wejścia do Illusion Temple.",
    1331: "Idź do Icarus. Pokonaj 80 Alquamosów i wróć do Shadow Phantom Soldier, by otrzymać Devil's Invitation + 3 – przedmiot potrzebny do wejścia do Devil Square.",
    1332: "Idź do Icarus. Pokonaj 80 Mega Crustów i wróć do Shadow Phantom Soldier, by otrzymać Invisibility Cloak + 4 – przedmiot potrzebny do wejścia do Blood Castle.",
    1333: "Idź do Icarus. Pokonaj 90 Drakanów i wróć do Shadow Phantom Soldier, by otrzymać Scroll of Blood + 3 – przedmiot potrzebny do wejścia do Illusion Temple.",
    1334: "Idź do Kanturu Relics. Pokonaj 100 Dreadfearów i wróć do Shadow Phantom Soldier, by otrzymać Invisibility Cloak + 8 – przedmiot potrzebny do wejścia do Blood Castle.",
    1335: "Idź do Kanturu Relics. Pokonaj 100 Twin Tails i wróć do Shadow Phantom Soldier, by otrzymać Invisibility Cloak + 7 – przedmiot potrzebny do wejścia do Blood Castle.",
    1336: "Idź do Kanturu Ruins, zabij 20 Splinter Wolves i 10 Blade Hunterów i wróć do 'Shadow Phantom Soldier' po swoją nagrodę.",
    1337: "Idź do Kanturu Ruins, zabij 20 Splinter Wolves i 20 Satyrosów i wróć do 'Shadow Phantom Soldier' po swoją nagrodę.",
    1338: "Idź do Kanturu Ruins, zabij 20 Splinter Wolves i 5 Kentaurosów i wróć do 'Shadow Phantom Soldier' po swoją nagrodę.",
    1339: "Idź do Kanturu Ruins, zabij 20 Splinter Wolves i wróć do 'Shadow Phantom Soldier' z 1 Ancient Stick (Obrażenia magiczne +12) po swoją nagrodę.",
    1340: "Idź do Kanturu Ruins, zabij 30 Iron Riderów i wróć do 'Shadow Phantom Soldier' po swoją nagrodę.",
    1341: "Idź do La Cleon. Pokonaj 120 Ice Walkerów i wróć do Shadow Phantom Soldier, by otrzymać Devil's Invitation + 6 – przedmiot potrzebny do wejścia do Devil Square.",
    1342: "Idź do Poziomów 4-6 Lost Tower i pokonaj 100 Diabłów. Wróć do Shadow Phantom Soldier, by wybrać nagrodę między 15 SD Potions a 15 Complex Potions.",
    1343: "Idź do Tarkan 2 i pokonaj 30 Zaikanów. Wróć ponownie do Shadow Phantom Soldier, by wybrać nagrodę między 20 Large SD Potions a 30 Large Complex Potions.",
    1344: "Idź do Tarkan 2. Pokonaj 100 Beam Knightów i wróć do Shadow Phantom Soldier, by otrzymać Devil's Invitation + 5 – przedmiot potrzebny do wejścia do Devil Square.",
    1345: "Idź do Tarkan 2. Pokonaj 100 Tantalosów i wróć do Shadow Phantom Soldier, by otrzymać Invisibility Cloak + 5 – przedmiot potrzebny do wejścia do Blood Castle.",
    1346: "Idź do Tarkan 2. Pokonaj 30 Death Beam Knightów i wróć do Shadow Phantom Soldier, by otrzymać Scroll of Blood + 4 – przedmiot potrzebny do wejścia do Illusion Temple.",
    1347: "Idź do Tarkan, zabij 20 Mutantów i 10 Beam Knightów i wróć do 'Shadow Phantom Soldier' po swoją nagrodę.",
    1348: "Idź do Tarkan, zabij 20 Mutantów i 20 Tantalosów i wróć do 'Shadow Phantom Soldier' po swoją nagrodę.",
    1349: "Idź do Tarkan, zabij 20 Mutantów i wróć do 'Shadow Phantom Soldier' z 1 Staff of Resurrection (Obrażenia magiczne +12) po swoją nagrodę.",
    1350: "Idź do Tarkan, zabij 20 Mutantów i wróć do 'Shadow Phantom Soldier' z 10 Uniriami po swoją nagrodę.",
    1351: "Idź do Tarkan, zabij 30 Iron Wheeli i wróć do 'Shadow Phantom Soldier' po swoją nagrodę.",
    1352: "Idź do Tarkan. Pokonaj 100 Iron Wheeli i wróć do Shadow Phantom Soldier, by otrzymać Devil's Invitation + 4 – przedmiot potrzebny do wejścia do Devil Square.",
    1353: "Idź do Tarkan. Pokonaj 50 Bloody Wolves i wróć do Shadow Phantom Soldier, by otrzymać Scroll of Blood + 1 – przedmiot potrzebny do wejścia do Illusion Temple.",
    1354: "Idź do Tarkan. Pokonaj 70 Iron Wheeli i wróć do Shadow Phantom Soldier, by otrzymać Scroll of Blood + 2 – przedmiot potrzebny do wejścia do Illusion Temple.",
    1355: "Idź do Varki i wyeliminuj Advisor Jerinda i Gaiona Khareina. Gdy skończysz robotę i wrócisz do mnie, dam ci nagrodę od gildii. Poza tym możesz dostać zwrot kaucji bez Świadectwa Ukończenia Prośby Lv. 1, gdy ukończysz to zadanie.",
    1356: "Idź do Vulcanus i wyeliminuj 50 Blood Assassinów, a dam ci nagrodę.",
    1357: "Idź do Poziomu 1 Lost Tower i pokonaj 100 Cieni. Dam ci Ancient Armor + 7 i Chaos Dragon Axe + 4 + Option jako nagrodę.",
    1358: "Idź do Poziomu 1 Lost Tower i pokonaj 100 Cieni. Dam ci Eclipse Armor + 7 i Chaos Dragon Axe + 4 + Option jako nagrodę.",
    1359: "Idź do Poziomu 1 Lost Tower i pokonaj 100 Cieni. Gdy to zrobisz, będziesz mógł otrzymać nagrodę od Shadow Phantom Soldier.",
    1360: "Idź do Poziomu 1 Lost Tower i pokonaj 50 Cieni i 50 Poison Shadows. Gdy to zrobisz, będziesz mógł otrzymać nagrodę od Shadow Phantom Soldier.",
    1361: "Idź do Poziomu 1 Lost Tower. Pokonaj 50 Cieni i 30 Poison Shadows, a dam ci Ancient Gloves + 8 jako nagrodę.",
    1362: "Idź do Poziomu 1 Lost Tower. Pokonaj 50 Cieni i 30 Poison Shadows, a dam ci Eclipse Gloves + 8 jako nagrodę.",
    1363: "Idź do Poziomu 1 Lost Tower. Pokonaj 50 Cieni i 50 Poison Shadows, a dam ci Ashcrow Gloves + 7 jako nagrodę.",
    1364: "Idź do Poziomu 1 Lost Tower. Pokonaj 50 Cieni i 50 Poison Shadows, a dam ci Iris Gloves + 7 jako nagrodę.",
    1365: "Idź do Poziomu 2 Lost Tower i pokonaj 50 Poison Shadows i 30 Cursed Wizardów. Gdy to zrobisz, będziesz mógł otrzymać nagrodę od Shadow Phantom Soldier.",
    1366: "Idź do Poziomu 2 Lost Tower. Pokonaj 50 Poison Shadows i 30 Cursed Wizardów, a dam ci Ancient Boots + 8 jako nagrodę.",
    1367: "Idź do Poziomu 2 Lost Tower. Pokonaj 50 Poison Shadows i 30 Cursed Wizardów, a dam ci Ashcrow Boots + 7 jako nagrodę.",
    1368: "Idź do Poziomu 2 Lost Tower. Pokonaj 50 Poison Shadows i 30 Cursed Wizardów, a dam ci Eclipse Boots + 8 jako nagrodę.",
    1369: "Idź do Poziomu 2 Lost Tower. Pokonaj 50 Poison Shadows i 30 Cursed Wizardów, a dam ci Iris Boots + 7 jako nagrodę.",
    1370: "Idź do Poziomu 3 Lost Tower i pokonaj 50 Cursed Wizardów i 50 Death Krów. Gdy to zrobisz, będziesz mógł otrzymać nagrodę od Shadow Phantom Soldier.",
    1371: "Idź do Poziomu 3 Lost Tower. Pokonaj 50 Cursed Wizardów i 50 Death Krów, a dam ci Ancient Helm + 8 jako nagrodę.",
    1372: "Idź do Poziomu 3 Lost Tower. Pokonaj 50 Cursed Wizardów i 50 Death Krów, a dam ci Ashcrow Helm + 7 i Ashcrow Pants + 7 jako nagrodę.",
    1373: "Idź do Poziomu 3 Lost Tower. Pokonaj 50 Cursed Wizardów i 50 Death Krów, a dam ci Eclipse Helm + 8 jako nagrodę.",
    1374: "Idź do Poziomu 3 Lost Tower. Pokonaj 50 Cursed Wizardów i 50 Death Krów, a dam ci Iris Helm + 7 i Iris Pants + 7 jako nagrodę.",
    1375: "Idź do Poziomu 4 Lost Tower i pokonaj 50 Death Krów i 30 Diabłów. Gdy to zrobisz, będziesz mógł otrzymać nagrodę od Shadow Phantom Soldier.",
    1376: "Idź do Poziomu 4 Lost Tower. Pokonaj 50 Death Krów i 30 Diabłów, a dam ci Ashcrow Gloves + 8 jako nagrodę.",
    1377: "Idź do Poziomu 4 Lost Tower. Pokonaj 50 Death Krów i 30 Diabłów, a dam ci Iris Gloves + 8 jako nagrodę.",
    1378: "Idź do Poziomu 7 Lost Tower i pokonaj 50 Death Gorgonów i 10 Balrogów. Gdy to zrobisz, będziesz mógł otrzymać nagrodę od Shadow Phantom Soldier.",
    1379: "Idź do Poziomu 7 Lost Tower i pokonaj 50 Death Knightów i 50 Death Gorgonów. Gdy to zrobisz, będziesz mógł otrzymać nagrodę od Shadow Phantom Soldier.",
    1380: "Idź do Poziomu 7 Lost Tower i pokonaj 50 Death Knightów, 30 Death Gorgonów i 20 Balrogów. Gdy to zrobisz, będziesz mógł otrzymać nagrodę od Shadow Phantom Soldier.",
    1381: "Idź do Poziomu 7 Lost Tower. Pokonaj 50 Death Gorgonów i 10 Balrogów, a dam ci Ashcrow Armor + 8 jako nagrodę.",
    1382: "Idź do Poziomu 7 Lost Tower. Pokonaj 50 Death Gorgonów i 10 Balrogów, a dam ci Iris Armor + 8 jako nagrodę.",
    1383: "Idź do Poziomu 7 Lost Tower. Pokonaj 50 Death Knightów i 30 Death Gorgonów, a dam ci Ashcrow Pants + 8 jako nagrodę.",
    1384: "Idź do Poziomu 7 Lost Tower. Pokonaj 50 Death Knightów i 30 Death Gorgonów, a dam ci Iris Pants + 8 jako nagrodę.",
    1385: "Idź do Poziomu 7 Lost Tower. Pokonaj 50 Death Knightów, 30 Death Gorgonów i 20 Balrogów, a dam ci Crystal Sword + 7 + Skill jako nagrodę.",
    1386: "Idź do Poziomu 7 Lost Tower. Pokonaj 50 Death Knightów, 30 Death Gorgonów i 20 Balrogów, a dam ci Aquagold Crossbow + 7 + Skill jako nagrodę.",
    1387: "Idź do Poziomów 2 i 3 Lost Tower. Pokonaj 60 Death Krów i wróć do Shadow Phantom Soldier, by otrzymać Devil's Invitation + 2 – przedmiot potrzebny do wejścia do Devil Square.",
    1388: "Idź do Poziomów 3 i 4 Lost Tower i pokonaj 100 Death Krów. Dam ci Ancient Pants + 8 jako nagrodę.",
    1389: "Idź do Poziomów 3 i 4 Lost Tower i pokonaj 100 Death Krów. Dam ci Eclipse Pants + 8 jako nagrodę.",
    1390: "Idź do Poziomów 3 i 4 Lost Tower i pokonaj 100 Death Krów. Dam ci Ashcrow Armor + 7 i Chaos Dragon Axe + 4 + Option jako nagrodę.",
    1391: "Idź do Poziomów 3 i 4 Lost Tower i pokonaj 100 Death Krów. Dam ci Iris Armor + 7 i Chaos Dragon Axe + 4 + Option jako nagrodę.",
    1392: "Idź do Poziomów 3 i 4 Lost Tower i pokonaj 100 Death Krów. Gdy to zrobisz, będziesz mógł otrzymać nagrodę od Shadow Phantom Soldier.",
    1393: "Idź do Poziomów 4 i 5 Lost Tower i pokonaj 100 Diabłów. Dam ci Ashcrow Boots + 8 jako nagrodę.",
    1394: "Idź do Poziomów 4 i 5 Lost Tower i pokonaj 100 Diabłów. Dam ci Iris Boots + 8 jako nagrodę.",
    1395: "Idź do Poziomów 4 przez 6 Lost Tower i pokonaj 100 Diabłów. Dam ci Ancient Armor + 8 jako nagrodę.",
    1396: "Idź do Poziomów 4 przez 6 Lost Tower i pokonaj 100 Diabłów. Dam ci Eclipse Armor + 8 jako nagrodę.",
    1397: "Idź do Poziomów 4 przez 6 Lost Tower i pokonaj 100 Diabłów. Gdy to zrobisz, będziesz mógł otrzymać nagrodę od Shadow Phantom Soldier.",
    1398: "Idź do Poziomów 4 przez 6 Lost Tower, a napotkasz Diabły używające ciemnej magii. Pokonaj 50 Diabłów i wróć do mnie po nagrodę.",
    1399: "Idź do Poziomów 4 przez 6 Lost Tower, a napotkasz Diabły używające ciemnej magii. Pokonaj 60 Diabłów i wróć do mnie po nagrodę.",
    1400: "Idź do Poziomów 5 przez 7 Lost Tower i pokonaj 100 Death Knightów. Dam ci Legendary Staff + 8 jako nagrodę.",
    1401: "Idź do Poziomów 5 przez 7 Lost Tower i pokonaj 100 Death Knightów. Dam ci Red Wing Stick + 8 jako nagrodę.",
    1402: "Idź do Poziomów 5 przez 7 Lost Tower i pokonaj 100 Death Knightów. Dam ci Ashcrow Helm + 8 jako nagrodę.",
    1403: "Idź do Poziomów 5 przez 7 Lost Tower i pokonaj 100 Death Knightów. Dam ci Iris Helm + 8 jako nagrodę.",
    1404: "Idź do Poziomów 5 przez 7 Lost Tower i pokonaj 100 Death Knightów. Gdy to zrobisz, będziesz mógł otrzymać nagrodę od Shadow Phantom Soldier.",
    1405: "Idź do Lost Tower. Pokonaj 80 Death Knightów i wróć do Shadow Phantom Soldier, by otrzymać Invisibility Cloak + 3 – przedmiot potrzebny do wejścia do Blood Castle.",
    1406: "Idź do Bagna Spokoju i pokonaj 100 Shadow Pawns. Wróć ponownie do Shadow Phantom Soldier, by wybrać nagrodę między 30 Large SD Potions a 45 Large Complex Potions.",
    1407: "Idź do Bagna Spokoju. Pokonaj 140 Shadow Knights i wróć do Shadow Phantom Soldier, by otrzymać Devil's Invitation + 7 – przedmiot potrzebny do wejścia do Devil Square.",
    1408: "Idź do Bagna Spokoju. Pokonaj 150 Shadow Looks i wróć do Shadow Phantom Soldier, by otrzymać Scroll of Blood + 6 – przedmiot potrzebny do wejścia do Illusion Temple.",
    1409: "Idź na obszar między Tarkan 1 a Tarkan 2, a zobaczysz tych zabójców zwanych Iron Wheels. Pokonaj 60 Iron Wheeli i wróć do mnie po nagrodę.",
    1439: "Dobra decyzja. Pierwsza misja drugiej próby polega na pokonaniu 10 Gwardzistów w Chaos Castle, dostarczeniu broni Archanioła w Blood Castle i przetrwaniu do końca Devil Square. Ukończ misję, a zostaniesz nagrodzony jednym z następujących: Jewel of Bless, Jewel of Soul, Jewel of Chaos lub Jewel of Harmony.",
    1440: "Dobra decyzja. Pierwsza misja piątej próby polega na przetrwaniu w Chaos Castle, dostarczeniu broni Archanioła w Blood Castle i przetrwaniu do końca Devil Square. Ukończ misję, a zostaniesz nagrodzony jednym z następujących: Jewel of Bless, Jewel of Life, Jewel of Harmony lub dwa Jele of Soul.",
}

# ============================================================
# Continue with remaining IDs
# ============================================================

TR.update({
    1441: "Dobra decyzja. Pierwsza misja pierwszej próby polega na pokonaniu 5 potworów w Chaos Castle, dostarczeniu broni Archanioła w Blood Castle i przetrwaniu do końca Devil Square. Ukończ misję, a zostaniesz nagrodzony jednym z następujących: Jewel of Bless, Jewel of Soul, Jewel of Chaos lub Jewel of Harmony.",
    1442: "Dobra decyzja. Pierwsza misja trzeciej próby polega na pokonaniu 15 potworów w Chaos Castle, dostarczeniu broni Archanioła w Blood Castle i przetrwaniu do końca Devil Square. Ukończ misję, a zostaniesz nagrodzony jednym z następujących: Jewel of Bless, Jewel of Soul, Jewel of Chaos lub Jewel of Harmony.",
    1443: "Dobra decyzja. Pierwsza misja czwartej próby polega na pokonaniu 20 potworów w Chaos Castle, dostarczeniu broni Archanioła w Blood Castle i przetrwaniu do końca Devil Square. Ukończ misję, a zostaniesz nagrodzony jednym z następujących: Jewel of Bless, Jewel of Soul, Jewel of Chaos lub Jewel of Harmony.",
    1445: "Dobra decyzja. Pierwsza misja pierwszej próby polega na byciu ostatnim ocalałym w Chaos Castle, dostarczeniu broni Archanioła w Blood Castle i przetrwaniu do końca Devil Square. Ukończ misję, a otrzymasz 3 Jewele of Chaos.",
    1446: "Dobra decyzja. Pierwsza misja drugiej próby polega na byciu ostatnim ocalałym w Chaos Castle, dostarczeniu broni Archanioła w Blood Castle i przetrwaniu do końca Devil Square. Ukończ misję, a otrzymasz 3 Jewele of Soul.",
    1447: "Dobra decyzja. Pierwsza misja trzeciej próby polega na byciu ostatnim ocalałym w Chaos Castle, dostarczeniu broni Archanioła w Blood Castle i przetrwaniu do końca Devil Square. Ukończ misję, a otrzymasz 3 Jewele of Bless.",
    1448: "Dobra decyzja. Pierwsza misja czwartej próby polega na byciu ostatnim ocalałym w Chaos Castle, dostarczeniu broni Archanioła w Blood Castle i przetrwaniu do końca Devil Square. Ukończ misję, a otrzymasz 1 Jewel of Life.",
    1449: "Dobra decyzja. Pierwsza misja piątej próby polega na byciu ostatnim ocalałym w Chaos Castle, dostarczeniu broni Archanioła w Blood Castle i przetrwaniu do końca Devil Square. Ukończ misję, a otrzymasz 2 Jele of Life.",
    1457: "Duch rycerski. Jeśli nie masz silnej woli, by nigdy się nie poddawać, nigdy nie staniesz się prawdziwym bohaterem. (Odrzuć)",
    1465: "Wyczuwasz dziwny zapach...",
    1468: "Tusk mruży oczy i bada cię wzrokiem.",
    1471: "Dwa dni temu grupa najemników wyruszyła do Kanturu Ruins, by odzyskać kamień. Jesteś jednym z nich, prawda? Jak widać, kamień wciąż nie został odzyskany. Wygląda na to, że potwory są silniejsze, niż myśleliśmy. (Poziom 211-220)",
    1472: "W Icarus, ścieżce prowadzącej do Latającego Zamku, Alquamosy utrudniają awans naszym oddziałom zwiadowczym. Twoim zadaniem jest wyeliminowanie 80 Alquamosów i odblokowanie drogi. (Poziom 245-249)",
    1473: "Według doniesień, Lódowe Stwory w Devias atakują podróżnych. Zostałeś wezwany, by rozwiązać ten problem. Proszę pokonaj 30 Lódowych Stworów i wróć do mnie. (Poziom 96-100)",
    1476: "Dziwna rzecz. Miałem zamiar cię zapytać, czy chcesz zostać członkiem Gens Vanert, ale wydaje się, że już jesteś członkiem innego gens. Możesz dołączyć tylko do jednego gens. (Zadanie zostało anulowane.)",
    1477: "Dziwna rzecz. Miałem zamiar cię zapytać, czy chcesz zostać członkiem Gens Duprian, ale wydaje się, że już jesteś członkiem innego gens. Możesz dołączyć tylko do jednego gens. (Zadanie zostało anulowane.)",
    1478: "Spór gens to konflikt między Gens Duprian a Gens Vanert. Obie strony walczą ze sobą, by zdobyć 'Klejnot Władzy', który zapewnia absolutną władzę nad całym kontynem. Możesz dołączyć do jednej ze stron i walczyć w imieniu swojej sprawy.",
    1479: "Gens to wielka organizacja złożona z dwóch frakcji: Duprian i Vanert. Członkowie gens mogą podejmować się specjalnych zadań gens, otrzymywać wyjątkowe nagrody i cieszyć się wieloma innymi korzyściami. Obecnie trwa wielki spór między Gens Duprian a Gens Vanert. Wybierz stronę i walcz w imieniu swojej sprawy.",
    1480: "Gratuluję. Zdałeś egzamin i zostałeś pełnoprawnym członkiem Gens Vanert. Jako członek Gens Vanert będziesz mógł podejmować się specjalnych zadań gens, otrzymywać wyjątkowe nagrody i cieszyć się wieloma innymi korzyściami. Otrzymujesz też tytuł Początkujący Vanert.",
    1481: "Gratuluję. Zdałeś egzamin i zostałeś pełnoprawnym członkiem Gens Duprian. Jako członek Gens Duprian będziesz mógł podejmować się specjalnych zadań gens, otrzymywać wyjątkowe nagrody i cieszyć się wieloma innymi korzyściami. Otrzymujesz też tytuł Początkujący Duprian.",
    1482: "Idź i porozmawiaj z członkiem Gens Vanert, by się dowiedzieć więcej.",
    1483: "Idź i porozmawiaj z członkiem Gens Duprian, by się dowiedzieć więcej.",
    1484: "Miałem zamiar cię zapytać, czy chcesz dołączyć do Gens Vanert i walczyć w imieniu naszej sprawy. Jeśli zdasz egzamin, staniesz się pełnoprawnym członkiem Gens Vanert i będziesz mógł cieszyć się wieloma korzyściami. Czy chcesz przystąpić do egzaminu?",
    1485: "Miałem zamiar cię zapytać, czy chcesz dołączyć do Gens Duprian i walczyć w imieniu naszej sprawy. Jeśli zdasz egzamin, staniesz się pełnoprawnym członkiem Gens Duprian i będziesz mógł cieszyć się wieloma korzyściami. Czy chcesz przystąpić do egzaminu?",
    1486: "Witam cię. Jestem stewardem Gens Vanert. Czy mogę ci jakoś pomóc?",
    1487: "Witam cię. Jestem stewardem Gens Duprian. Czy mogę ci jakoś pomóc?",
    1488: "Szkoda. Jeśli zmienisz zdanie i zdecydujesz się walczyć w imieniu Gens Vanert, przyjdź i mnie odwiedź. (Zadanie zostało anulowane.)",
    1489: "Szkoda. Jeśli zmienisz zdanie i zdecydujesz się walczyć w imieniu Gens Duprian, przyjdź i mnie odwiedź. (Zadanie zostało anulowane.)",
    1490: "Zadaniem egzaminacyjnym jest wyeliminowanie 30 Goblinów i 20 Orków w okolicach miasta. Gdy je wyeliminujesz, wróć do mnie. Wtedy będę cię uważał za pełnoprawnego członka Gens Vanert.",
    1491: "Zadaniem egzaminacyjnym jest wyeliminowanie 30 Goblinów i 20 Orków w okolicach miasta. Gdy je wyeliminujesz, wróć do mnie. Wtedy będę cię uważał za pełnoprawnego członka Gens Duprian.",
    1498: "Półświeżość, powiedzielibyśmy. W każdym razie dobrze, że przyszedłeś. Słyszałem, że potwory w okolicach miasta stają się ostatnio coraz bardziej agresywne. Chciałbym poprosić cię o kilka drobnych zadań. Czy chcesz posłuchać?",
    1499: "To prawda, że potwory ostatnio stają się coraz bardziej agresywne?;Chętnie pomogę.",
    1500: "Tusk powiedział coś o jakiejś broni...;Wróć.",
    1507: "Pierwsze zadanie: wyeliminuj 20 Goblinów i 15 Orków w okolicach miasta. Jeśli zrobisz to dobrze, dam ci następne zadanie. Wróć, gdy skończysz.",
    1514: "Ha, ha! Słyszałem, że jesteś całkiem niezły. Skoro tak, to dam ci następne zadanie. Pokonaj 15 Stone Golemów w okolicach miasta. Wróć, gdy skończysz.",
    1521: "Ukończyłeś moje zadania szybciej, niż myślałem. Jesteś całkiem niezły, jak na kogoś takiego. Dobrze, to ostatnie zadanie. Idź do Poziomu 1 Lochu i pokonaj 10 Cyklopów. Wróć, gdy skończysz.",
    1528: "Jesteś zaskakująco silny. Szczerze mówiąc, nie spodziewałem się tak wiele. Może naprawdę możesz mi pomóc. Dobrze. Idź do Poziomu 2 Lochu i pokonaj 10 Szkieletowych Wojowników. Wróć, gdy skończysz.",
    1535: "Ha! W końcu ktoś godny mojego czasu. Słuchaj uważnie. Wiem, że szukasz sposobu, by stać się silniejszym. Jeśli wykonasz dla mnie kilka zadań, dam ci potężną broń. Co mówisz? Przyjmujesz?",
    1536: "Oczywiście! Dam wszystko, by zdobyć potężną broń!;Co mam zrobić?",
    1543: "Dobrze, słuchaj. Pierwsze zadanie to przetestowanie twoich umiejętności walki. Idź do Devias i pokonaj 30 Gigantów. Wróć, gdy skończysz. Dam ci wtedy następne zadanie.",
    1550: "Dobrze, następne zadanie. Idź do Poziomu 2 Lost Tower i pokonaj 20 Poison Shadows. Wróć, gdy skończysz.",
    1557: "Cóż, nie jest źle. Następne zadanie jest trudniejsze. Idź do Tarkan i pokonaj 20 Bloody Wolves. Wróć, gdy skończysz.",
    1564: "Hmm... Jesteś silniejszy, niż myślałem. Dobrze, to ostatnie zadanie. Idź do Icarus i pokonaj 20 Alquamosów. Jeśli ci się uda, dam ci obiecaną broń.",
    1571: "Jesteś naprawdę niesamowity. Jak obiecałem, dam ci tę broń. To dobra broń, ale pamiętaj: prawdziwa siła nie leży w broni, ale w tobie samym. Idź i stań się prawdziwym bohaterem.",
    1572: "Wziąłeś broń od Tuska.",
    1578: "Jak śmiesz przeszkadzać mi w moich badaniach! Co chcesz, śmiertelniku?",
    1579: "Jestem Marlon, alchemik. Badam tajemnice kamienia szaleństwa. Jeśli pomożesz mi w moich badaniach, dam ci coś w zamian. Co mówisz? Chcesz pomóc?",
    1580: "Badania nad kamieniem szaleństwa?;Brzmi interesująco. Pomogę.",
    1586: "Dobrze. Najpierw muszę zebrać trochę materiałów. Idź do Lochu i zbierz 30 trujących gruzu od Poison Bull Fighterów. Wróć z nimi, a zacznę eksperyment.",
    1593: "Dobrze, dobrze. Masz trujący gruz. Teraz potrzebuję czegoś silniejszego. Idź do Lost Tower i zbierz 20 cieni duszy od Cieni. Wróć z nimi.",
    1600: "Hmm... Te cienie duszy są bardziej stabilne, niż myślałem. Potrzebuję czegoś, co posłuży jako katalizator. Idź do Devias i przynieś mi 15 lśniących odłamków od Lódowych Stworów. Pospiesz się!",
    1607: "Doskonałe! Dzięki tym materiałom mogę dokończyć eksperyment. Oto coś dla ciebie – efekt kamienia szaleństwa skonsolidowany w pierścieniu. Zwiększy twoją siłę, ale używaj go ostrożnie.",
    1608: "Otrzymałeś Pierścień Szaleństwa od Marlona.",
    1614: "Pozdrawiam, podróżniku. Jestem Lucretia, kapłanka Świątyni Iluzji. Przybyłeś we właściwym czasie. Starożytna moc budzi się w głębi świątyni, a my potrzebujemy pomocy dzielnego wojownika takiego jak ty. Czy zechcesz nam pomóc?",
    1615: "Starożytna moc w Świątyni Iluzji?;Oczywiście, że pomogę!",
    1621: "Dziękuję. Posłuchaj uważnie. W głębi Illusion Temple mieszka Illusion Sorcerer, który używa zaklęć iluzji, by zwodzić podróżnych. Twoim zadaniem jest wejście do Illusion Temple i go pokonanie. Weź ten Zwój Krwi – pozwoli ci wejść do świątyni.",
    1622: "Otrzymałeś Scroll of Blood od Lucretii.",
    1628: "Widzę, że ci się udało. Pokonałeś Illusion Sorcerera i oczyściłeś świątynię. Dziękujemy ci za twoją odwagę. Weź tę nagrodę jako znak naszej wdzięczności.",
    1629: "Otrzymałeś nagrodę od Lucretii.",
    1635: "Tak więc chciałeś zostać bohaterem. Ha! Bycie bohaterem to nie tylko sława i fortuna. To ciężka praca i poświęcenie. Ale jeśli naprawdę chcesz... Możesz zostać moim uczniem. Czy chcesz?",
    1636: "Zostać twoim uczniem?;Zdecydowanie!",
    1642: "Dobrze. Pierwsza lekcja: odwaga. Odwaga to nie brak strachu. To działanie pomimo strachu. By to udowodnić, idź do Lochu i pokonaj 50 Cyklopów. Wróć, gdy skończysz.",
    1649: "Druga lekcja: siła woli. Nawet najsilniejszy wojownik jest bezużyteczny, jeśli brak mu woli. By to udowodnić, idź do Lost Tower i pokonaj 30 Death Knightów. Wróć, gdy skończysz.",
    1656: "Trzecia lekcja: współczucie. Bohater nie walczy tylko dla siebie. Walczy dla tych, którzy nie mogą walczyć sami. Idź do Aidy i wyeliminuj 50 Death Trees. Wróć, gdy skończysz.",
    1663: "Czwarta lekcja: mądrość. Siła bez mądrości to tylko dzikość. Rozwiąż tę zagadkę: Co jest silniejsze od miecza, ostrzejsze od węża, a i tak służy bohaterowi?",
    1664: "Odpowiedź to... serce?;Odpowiedź to... wola?;Odpowiedź to... umysł?",
    1670: "Piąta i ostatnia lekcja: ostateczna próba. Wejdź do Chaos Castle i wyjdź zwycięsko. Jeśli ci się uda, staniesz się prawdziwym bohaterem.",
    1677: "Udało ci się... przeszedłeś wszystkie próby. Wstaję, uczniu. Jesteś teraz prawdziwym bohaterem. Idź i nieś światło nadziei tym, którzy go potrzebują.",
    1678: "Zostałeś Bohaterem!",
    1684: "Witaj, młody wojowniku. Jestem Pasi, mag z Lorencji. Widzę, że dopiero zaczynasz swoją podróż. Pozwól, że nauczę cię paru podstawowych umiejętności magicznych. Czy chcesz się nauczyć?",
    1685: "Nauczyć się magii?;Oczywiście!",
    1691: "Dobrze. Pierwsze i najpodstawniejsze zaklęcie to Kula Ognia. Nauczenie cię go nic nie kosztuje. Weź ten zwój i kliknij go prawym przyciskiem myszy, by nauczyć się umiejętności.",
    1692: "Otrzymałeś Zwój Kuli Ognia od Pasi.",
    1698: "Widzę, że nauczyłeś się Kuli Ognia. Dobrze. Pamiętaj, by ćwiczyć często – tylko wtedy magia stanie się naprawdę potężna. Gdy będziesz gotów na więcej, przyjdź i mnie odwiedź.",
    1705: "Witaj, młody elfie. Jestem Elf Lala. Widzę, że szukasz swojej drogi w tym świecie. Pozwól, że dam ci radę i parę przedmiotów na początek. Czy chcesz?",
    1706: "Rada i prezenty?;Chętnie!",
    1712: "Dobrze. Po pierwsze: zawsze miej przy sobie Town Portal Scroll. Może uratować ci życie, gdy będziesz w tarapatach. Po drugie: ucz się umiejętności odpowiednich dla twojej ścieżki. Weź ten prezent ode mnie.",
    1713: "Otrzymałeś prezent od Elf Lala.",
    1719: "Pamiętaj: prawdziwa siła elfa leży w zwinności i dystansie. Nie angażuj się w walkę w zwarciu, jeśli możesz tego uniknąć. Powodzenia na twojej drodze.",
    1726: "Witaj, podróżniku. Jestem Hanzo, kowal z Lorencji. Widzę, że twój ekwipunek pozostawia wiele do życzenia. Mogę go dla ciebie ulepszyć... za odpowiednią opłatą, rzecz jasna. Co mówisz?",
    1727: "Ulepszanie ekwipunku?;Powiedz mi więcej.",
    1733: "Aby ulepszyć przedmiot, potrzebujesz klejnotów. Jewel of Bless zwiększa poziom ulepszenia broni i zbroi o +1. Jewel of Soul to robi samo, ale może się nie udać. Aby bezpiecznie ulepszać, używaj Jewel of Bless. To wszystko, co musisz wiedzieć na początek.",
    1740: "Witaj, wędrowcze. Jestem Hanzo the Blacksmith. Możesz u mnie naprawić lub ulepszyć swój ekwipunek. Odwiedź mnie, gdy będziesz potrzebował moich usług.",
    1747: "Witaj! Jestem Amelia, dziewczyna od mikstur. Sprzedaję różnego rodzaju mikstury, które pomogą ci w podróży. Healing Potions odnawiają HP, a Mana Potions – MANĘ. Czego potrzebujesz?",
    1748: "Healing Potions i Mana Potions...;Dziękuję za informację!",
    1754: "Pamiętaj, by zawsze mieć przy sobie wystarczającą liczbę mikstur. Nigdy nie wiesz, co czeka cię za rogiem. Do zobaczenia!",
    1761: "Hej! Chcesz handlować? Mam mnóstwo świetnych towarów. Spójrz tylko!",
    1762: "Handel?;Pokaż, co masz.",
    1768: "Jak widzisz, mam wszystko, czego może potrzebować podróżny. Od mikstur po zwoje umiejętności – wszystko, co trzeba. Pamiętaj o mnie, gdy będziesz czegoś potrzebował!",
    1775: "Witaj, przyjacielu. Jestem starcem z wioski. Przyszedłem tu poprosić o pomoc. Potwory z pobliskiego lasu zaczęły atakować naszą wioskę. Czy mógłbyś nam pomóc?",
    1776: "Potwory atakują wioskę?;Oczywiście, że pomogę!",
    1782: "Dziękuję ci z całego serca. Potwory to Gobliny i Orki. Ukrywają się w lesie na północ od miasta. Proszę, wyeliminuj ich, zanim zaatakują ponownie.",
    1789: "Och, dziękuję ci! Uratowałeś naszą wioskę. Proszę, weź tę niewielką nagrodę jako znak naszej wdzięczności.",
    1790: "Otrzymałeś nagrodę od starca.",
    1796: "Muszę iść i powiedzieć mieszkańcom wioski, że są bezpieczni. Jeszcze raz dziękuję, dzielny wojowniku!",
    1803: "Psst... Hej, ty. Chcesz zarobić trochę szybkiego zenów? Mam dla ciebie robotę... jeśli nie masz nic przeciwko nieco ryzykownym zadaniom.",
    1804: "Szybkie zeny?;Co mam zrobić?",
    1810: "Dobrze, słuchaj. Jest pewien kupiec, który jest mi winny dużo pieniędzy. Zamiast spłacać dług, ukrył się w Lochu. Weź od niego to, co jest mi winien. I nie pytaj nic więcej. Rozumiesz?",
    1811: "Rozumiem.;Zaraz się tym zajmę.",
    1817: "Dobrze. Idź do Poziomu 2 Lochu i znajdź tego kupca. A raczej to, co zostanie po nim... i przynieś mi jego torbę z zenami. Wróć, gdy będziesz miał.",
    1824: "Oto twoja zapłata. Dobrze się spisałeś. Jeśli będziesz chciał więcej roboty, wiesz, gdzie mnie szukać. Hehe...",
    1825: "Otrzymałeś zapłatę od tajemniczego człowieka.",
    1831: "Witaj, dzielny wojowniku. Słyszałem o twoich wyczynach. Jestem David, dowódca straży miejskiej. Potrzebujemy kogoś takiego jak ty do specjalnej misji. Czy jesteś zainteresowany?",
    1832: "Specjalna misja?;Oczywiście!",
    1838: "Dobrze. Według naszych informacji, grupa bandytów ukrywa się w jaskini na wschód od miasta. Planują napad na karawanę handlową. Twoim zadaniem jest ich powstrzymanie. Idź i wyeliminuj przywódcę bandytów.",
    1845: "Doskonała robota! Dzięki tobie karawana jest bezpieczna. W imieniu miasta dziękuję ci. Weź tę nagrodę – zasługujesz na nią.",
    1846: "Otrzymałeś nagrodę od Davida.",
    1853: "Wciąż potrzebujemy ludzi takich jak ty. Jeśli będziesz szukał pracy, przyjdź i mnie odwiedź. Do zobaczenia!",
    1860: "Przeklęty jesteś, śmiertelniku! Nie powstrzymasz nas. Nasz mistrz wkrótce powróci, a cały świat stanie w ogniu!",
    1861: "Nasz mistrz powróci...;Wróć!",
    1867: "Witaj, mój przyjacielu. Jestem Tercia, menedżer gildii najemników. Słyszałem, że szukasz sposobu na zarobienie zenów i sławy. Gildia najemników może ci to zaoferować. Co mówisz – chcesz do nas dołączyć?",
    1868: "Gildia najemników?;Powiedz mi więcej.",
    1874: "Jesteśmy organizacją, która przyjmuje prośby od klientów i przekazuje je najemnikom. Za ukończenie prośby dostajesz nagrodę. Im trudniejsza prośba, tym lepsza nagroda. Brzmi dobrze, prawda? Aby dołączyć, wystarczy opłata rejestracyjna.",
    1875: "Ile kosztuje rejestracja?;Zapisz mnie!",
    1881: "Rejestracja kosztuje 1 milion zenów. W zamian dostajesz dostęp do wszystkich prośb gildii i możliwość zarabiania dużych pieniędzy. Warto, prawda? Więc – zapisać cię?",
    1882: "Dobrze, zapisz mnie!;Hmm, 1 milion... nie mam teraz tyle.",
    1888: "Wspaniale! Witaj w gildii najemników! Oto twój pierwszy List Prośby. Przeczytaj go i wykonaj zadanie. Powodzenia!",
    1889: "Zostałeś zarejestrowany w gildii najemników.",
    1892: "Wróć, gdy będziesz miał wystarczająco dużo zenów. Drzwi gildii są zawsze otwarte dla tych, którzy chcą pracować. (Zadanie zostało anulowane.)",
})

# ============================================================
# Build output
# ============================================================

results = []
missing = []
for s in strings:
    sid = s["id"]
    if sid in TR:
        tx = TR[sid]
        # verify semicolon count
        orig_sc = s["en"].count(";")
        tx_sc = tx.count(";")
        if orig_sc != tx_sc:
            print(f"WARNING: id {sid} semicolon mismatch: original={orig_sc} translation={tx_sc}")
        results.append({"id": sid, "tx": tx})
    else:
        missing.append(sid)
        results.append({"id": sid, "tx": s["en"]})  # fallback

print(f"Translated: {len(results)}")
print(f"Missing translations: {len(missing)}")
if missing:
    print(f"Missing IDs: {sorted(missing)}")

output = {"results": results}

os.makedirs(os.path.dirname(OUTPUT), exist_ok=True)
with open(OUTPUT, "w", encoding="utf-8") as f:
    json.dump(output, f, ensure_ascii=False, indent=1)

print(f"Written to {OUTPUT}")

# verify
with open(OUTPUT, "r", encoding="utf-8") as f:
    check = json.load(f)
print(f"Verification: {len(check['results'])} results, valid JSON")
